import baseConfig from '@mission-platform/eslint-config';

export default [
  { ignores: ['assembly/**', 'build/**', 'src/generated/**'] },
  ...baseConfig,
  {
    name: 'mission-platform/phone-number-overrides',
    files: ['src/**/*.ts', 'vite.config.ts'],
    rules: {
      'unicorn/prevent-abbreviations': 'off',
      'unicorn/no-null': 'off',
      'unicorn/prefer-string-raw': 'off',
      'unicorn/switch-case-braces': 'off',
      'unicorn/no-for-loop': 'off',
      'unicorn/no-array-for-each': 'off',
      'unicorn/prefer-code-point': 'off',
      'unicorn/prefer-math-trunc': 'off',
      'unicorn/prefer-string-slice': 'off',
      'unicorn/no-array-reduce': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/prefer-includes': 'off',
      'unicorn/prefer-regexp-test': 'off',
      'unicorn/consistent-function-scoping': 'off',
      'unicorn/no-lonely-if': 'off',
      'unicorn/text-encoding-identifier-case': 'off',
      'unicorn/no-array-callback-reference': 'off',
      'unicorn/number-literal-case': 'off',
      'unicorn/explicit-length-check': 'off',
      'unicorn/no-useless-undefined': 'off',
      'unicorn/no-zero-fractions': 'off',
      'unicorn/no-negated-condition': 'off',
      'unicorn/prefer-spread': 'off',
      'unicorn/prefer-ternary': 'off',
      'unicorn/catch-error-name': 'off',
      'unicorn/prefer-number-properties': 'off',
      'unicorn/error-message': 'off',
      'unicorn/numeric-separators-style': 'off',
      'unicorn/prefer-switch': 'off',
      'unicorn/no-new-array': 'off',
      'import-x/no-useless-path-segments': 'off',
      'import-x/order': 'off',
    },
  },
];
