/**
 * FWS header and extern bindings generator from Web IDL ASTs.
 */

import type {
  FlintBindingOptions,
  WebIdlDictionary,
  WebIdlEnum,
  WebIdlInterface,
  WebIdlModule,
  WebIdlNamespace,
  WebIdlType,
} from './types.js';

export class FlintBindingGenerator {
  private readonly module: WebIdlModule;
  private readonly options: FlintBindingOptions;

  public constructor(module: WebIdlModule, options: FlintBindingOptions = {}) {
    this.module = module;
    this.options = options;
  }

  public generate(): string {
    const lines: string[] = ['// Generated by Flint Web IDL Interop Compiler', '// DO NOT EDIT DIRECTLY', ''];

    const capabilityPrefix = this.options.capabilityPrefix ?? 'web';
    const emitInterfaces = this.options.emitInterfaces ?? true;
    const emitImports = this.options.emitCapabilityImports ?? true;

    // 1. Enums
    const enums = this.module.definitions.filter((d): d is WebIdlEnum => d.kind === 'enum');
    for (const enumDeclaration of enums) {
      lines.push(this.generateEnum(enumDeclaration), '');
    }

    // 2. Dictionaries (structs)
    const dictionaries = this.module.definitions.filter((d): d is WebIdlDictionary => d.kind === 'dictionary');
    for (const dict of dictionaries) {
      lines.push(this.generateDictionary(dict), '');
    }

    // 3. Interfaces
    const interfaces = this.module.definitions.filter((d): d is WebIdlInterface => d.kind === 'interface');
    for (const iface of interfaces) {
      if (emitInterfaces) {
        lines.push(this.generateInterface(iface), '');
      }

      if (emitImports) {
        const importLines = this.generateCapabilityImports(iface, capabilityPrefix);
        if (importLines.length > 0) {
          lines.push(`// Capability imports for ${iface.name}`, ...importLines, '');
        }
      }
    }

    // 4. Namespaces
    const namespaces = this.module.definitions.filter((d): d is WebIdlNamespace => d.kind === 'namespace');
    for (const ns of namespaces) {
      if (emitImports) {
        const importLines = this.generateNamespaceCapabilityImports(ns, capabilityPrefix);
        if (importLines.length > 0) {
          lines.push(`// Capability imports for namespace ${ns.name}`, ...importLines, '');
        }
      }
    }

    return lines.join('\n').trim() + '\n';
  }

  private generateEnum(enumDeclaration: WebIdlEnum): string {
    const lines: string[] = [`export enum ${this.sanitizeIdentifier(enumDeclaration.name)} {`];
    for (const value of enumDeclaration.values) {
      const variantName = this.formatEnumVariant(value);
      lines.push(`  ${variantName},`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  private generateDictionary(dict: WebIdlDictionary): string {
    const lines: string[] = [`struct ${this.sanitizeIdentifier(dict.name)} {`];
    for (const member of dict.members) {
      const fieldName = this.sanitizeIdentifier(member.name);
      let fieldType = this.mapType(member.type);
      if (!member.required && !member.type.nullable) {
        fieldType = `Option<${fieldType}>`;
      }
      lines.push(`  ${fieldName}: ${fieldType};`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  private generateInterface(iface: WebIdlInterface): string {
    const lines: string[] = [`interface ${this.sanitizeIdentifier(iface.name)} {`];

    // Attributes as getter / setter functions
    for (const member of iface.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterName = `get_${this.toSnakeCase(member.name)}`;
        lines.push(`  fn ${getterName}() -> ${attributeType};`);

        if (!member.readonly) {
          const setterName = `set_${this.toSnakeCase(member.name)}`;
          lines.push(`  fn ${setterName}(value: ${attributeType}) -> unit;`);
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = this.toSnakeCase(member.name);
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(`  fn ${opName}(${arguments_}) -> ${returnType};`);
      }
    }

    lines.push('}');
    return lines.join('\n');
  }

  private generateCapabilityImports(iface: WebIdlInterface, prefix: string): string[] {
    const lines: string[] = [];
    const ifaceNameSnake = this.toSnakeCase(iface.name);

    for (const member of iface.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterProperty = `get_${this.toSnakeCase(member.name)}`;
        const getterAlias = `${ifaceNameSnake}_${getterProperty}`;
        lines.push(
          `import capability "${prefix}.${iface.name}.${getterProperty}" as ${getterAlias}() -> ${attributeType};`,
        );

        if (!member.readonly) {
          const setterProperty = `set_${this.toSnakeCase(member.name)}`;
          const setterAlias = `${ifaceNameSnake}_${setterProperty}`;
          lines.push(
            `import capability "${prefix}.${iface.name}.${setterProperty}" as ${setterAlias}(value: ${attributeType}) -> unit;`,
          );
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = member.name;
        const opNameSnake = this.toSnakeCase(opName);
        const alias = `${ifaceNameSnake}_${opNameSnake}`;
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(
          `import capability "${prefix}.${iface.name}.${opName}" as ${alias}(${arguments_}) -> ${returnType};`,
        );
      }
    }

    return lines;
  }

  private generateNamespaceCapabilityImports(ns: WebIdlNamespace, prefix: string): string[] {
    const lines: string[] = [];
    const nsNameSnake = this.toSnakeCase(ns.name);

    for (const member of ns.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterProperty = `get_${this.toSnakeCase(member.name)}`;
        const getterAlias = `${nsNameSnake}_${getterProperty}`;
        lines.push(
          `import capability "${prefix}.${ns.name}.${getterProperty}" as ${getterAlias}() -> ${attributeType};`,
        );

        if (!member.readonly) {
          const setterProperty = `set_${this.toSnakeCase(member.name)}`;
          const setterAlias = `${nsNameSnake}_${setterProperty}`;
          lines.push(
            `import capability "${prefix}.${ns.name}.${setterProperty}" as ${setterAlias}(value: ${attributeType}) -> unit;`,
          );
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = member.name;
        const opNameSnake = this.toSnakeCase(opName);
        const alias = `${nsNameSnake}_${opNameSnake}`;
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(`import capability "${prefix}.${ns.name}.${opName}" as ${alias}(${arguments_}) -> ${returnType};`);
      }
    }

    return lines;
  }

  public mapType(type: WebIdlType): string {
    if (this.options.customTypeMappings?.[type.name] !== undefined) {
      const custom = this.options.customTypeMappings[type.name];
      return type.nullable ? `Option<${custom}>` : custom;
    }

    let result: string;

    switch (type.kind) {
      case 'primitive': {
        result = this.mapPrimitive(type.name);
        break;
      }
      case 'string': {
        result = 'string';
        break;
      }
      case 'buffer': {
        result = 'bytes';
        break;
      }
      case 'sequence':
      case 'frozen-array': {
        const inner = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'u32';
        result = `Vector<${inner}>`;
        break;
      }
      case 'promise': {
        const inner = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'unit';
        result = `Future<${inner}>`;
        break;
      }
      case 'record': {
        const key = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'string';
        const value = type.typeArguments?.[1] ? this.mapType(type.typeArguments[1]) : 'string';
        result = `Map<${key}, ${value}>`;
        break;
      }
      case 'union': {
        // Map union to the first non-null type or string if ambiguous
        const nonNull = type.unionTypes?.filter((u) => u.name !== 'undefined' && u.name !== 'void');
        result = nonNull && nonNull.length > 0 ? this.mapType(nonNull[0]) : 'string';
        break;
      }
      default: {
        result = this.sanitizeIdentifier(type.name);
        break;
      }
    }

    if (type.nullable) {
      return `Option<${result}>`;
    }

    return result;
  }

  private mapPrimitive(name: string): string {
    switch (name) {
      case 'boolean': {
        return 'bool';
      }
      case 'byte':
      case 'short':
      case 'long': {
        return 'i32';
      }
      case 'octet':
      case 'unsigned short':
      case 'unsigned long': {
        return 'u32';
      }
      case 'long long':
      case 'bigint': {
        return 'i64';
      }
      case 'unsigned long long': {
        return 'u64';
      }
      case 'float':
      case 'unrestricted float': {
        return 'f32';
      }
      case 'double':
      case 'unrestricted double': {
        return 'f64';
      }
      case 'void':
      case 'undefined': {
        return 'unit';
      }
      default: {
        return 'u32';
      }
    }
  }

  private sanitizeIdentifier(name: string): string {
    const reserved = new Set([
      'as',
      'break',
      'case',
      'const',
      'continue',
      'do',
      'else',
      'enum',
      'export',
      'fn',
      'for',
      'if',
      'import',
      'in',
      'inline',
      'interface',
      'iter',
      'let',
      'match',
      'module',
      'mut',
      'noinline',
      'record',
      'return',
      'struct',
      'switch',
      'while',
      'yield',
    ]);

    const sanitized = name.replaceAll(/[^a-zA-Z0-9_]/g, '_');
    if (reserved.has(sanitized)) {
      return `_${sanitized}`;
    }
    return sanitized;
  }

  private toSnakeCase(string_: string): string {
    return string_
      .replaceAll(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replaceAll(/[^a-zA-Z0-9_]/g, '_')
      .toLowerCase();
  }

  private formatEnumVariant(value: string): string {
    // Convert string like "readwrite" -> "Readwrite", "aes-gcm" -> "AesGcm"
    const cleaned = value.replaceAll(/[^a-zA-Z0-9]/g, ' ');
    const parts = cleaned.split(/\s+/).filter(Boolean);
    if (parts.length === 0) return 'Variant';

    return parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()).join('');
  }
}

export function generateFlintBindings(module: WebIdlModule, options?: FlintBindingOptions): string {
  return new FlintBindingGenerator(module, options).generate();
}
