/**
 * FLINT header and extern bindings generator from Web IDL ASTs.
 */

import type {
  FlintBindingOptions,
  WebIdlDictionary,
  WebIdlEnum,
  WebIdlInterface,
  WebIdlModule,
  WebIdlNamespace,
  WebIdlType,
} from './types.js';

/**
 * Generates FLINT header struct/interface/capability-import bindings from a parsed Web IDL module.
 */
export class FlintBindingGenerator {
  private readonly module: WebIdlModule;
  private readonly options: FlintBindingOptions;

  /**
   * Creates an FLINT binding generator bound to a parsed Web IDL module.
   *
   * @param module - Parsed Web IDL module to generate bindings from.
   * @param options - Generation options such as capability prefix and custom type mappings.
   */
  public constructor(module: WebIdlModule, options: FlintBindingOptions = {}) {
    this.module = module;
    this.options = options;
  }

  /**
   * Emits `export enum` declarations for every Web IDL enum.
   *
   * @param lines - Output line accumulator.
   */
  private generateEnums(lines: string[]): void {
    const enums = this.module.definitions.filter((d): d is WebIdlEnum => d.kind === 'enum');
    for (const enumDeclaration of enums) {
      lines.push(this.generateEnum(enumDeclaration), '');
    }
  }

  /**
   * Emits `struct` declarations for every Web IDL dictionary.
   *
   * @param lines - Output line accumulator.
   */
  private generateDictionaries(lines: string[]): void {
    const dictionaries = this.module.definitions.filter((d): d is WebIdlDictionary => d.kind === 'dictionary');
    for (const dict of dictionaries) {
      lines.push(this.generateDictionary(dict), '');
    }
  }

  /**
   * Emits the `interface` declaration and, optionally, capability import bindings for a single Web IDL interface.
   *
   * @param iface - Interface AST node to render.
   * @param capabilityPrefix - Host capability namespace prefix.
   * @param emitInterfaces - Whether to emit the structural `interface` declaration.
   * @param emitImports - Whether to emit `import capability` statements.
   * @param lines - Output line accumulator.
   */
  private generateInterfaceSection(
    iface: WebIdlInterface,
    capabilityPrefix: string,
    emitInterfaces: boolean,
    emitImports: boolean,
    lines: string[],
  ): void {
    if (emitInterfaces) {
      lines.push(this.generateInterface(iface), '');
    }

    if (emitImports) {
      const importLines = this.generateCapabilityImports(iface, capabilityPrefix);
      if (importLines.length > 0) {
        lines.push(`// Capability imports for ${iface.name}`, ...importLines, '');
      }
    }
  }

  /**
   * Emits interface declarations and capability imports for every Web IDL interface.
   *
   * @param capabilityPrefix - Host capability namespace prefix.
   * @param emitInterfaces - Whether to emit structural `interface` declarations.
   * @param emitImports - Whether to emit `import capability` statements.
   * @param lines - Output line accumulator.
   */
  private generateInterfaces(
    capabilityPrefix: string,
    emitInterfaces: boolean,
    emitImports: boolean,
    lines: string[],
  ): void {
    const interfaces = this.module.definitions.filter((d): d is WebIdlInterface => d.kind === 'interface');
    for (const iface of interfaces) {
      this.generateInterfaceSection(iface, capabilityPrefix, emitInterfaces, emitImports, lines);
    }
  }

  /**
   * Emits capability imports for every Web IDL namespace, if enabled.
   *
   * @param capabilityPrefix - Host capability namespace prefix.
   * @param emitImports - Whether to emit `import capability` statements.
   * @param lines - Output line accumulator.
   */
  private generateNamespaces(capabilityPrefix: string, emitImports: boolean, lines: string[]): void {
    if (!emitImports) return;

    const namespaces = this.module.definitions.filter((d): d is WebIdlNamespace => d.kind === 'namespace');
    for (const ns of namespaces) {
      const importLines = this.generateNamespaceCapabilityImports(ns, capabilityPrefix);
      if (importLines.length > 0) {
        lines.push(`// Capability imports for namespace ${ns.name}`, ...importLines, '');
      }
    }
  }

  /**
   * Generates the complete FLINT binding output for the bound Web IDL module.
   *
   * @returns The rendered FLINT source text.
   */
  public generate(): string {
    const lines: string[] = ['// Generated by Flint Web IDL Interop Compiler', '// DO NOT EDIT DIRECTLY', ''];

    const capabilityPrefix = this.options.capabilityPrefix ?? 'web';
    const emitInterfaces = this.options.emitInterfaces ?? true;
    const emitImports = this.options.emitCapabilityImports ?? true;

    this.generateEnums(lines);
    this.generateDictionaries(lines);
    this.generateInterfaces(capabilityPrefix, emitInterfaces, emitImports, lines);
    this.generateNamespaces(capabilityPrefix, emitImports, lines);

    return `${lines.join('\n').trim()}\n`;
  }

  /**
   * Renders a single Web IDL enum as an FLINT `export enum` declaration.
   *
   * @param enumDeclaration - Enum AST node to render.
   * @returns The rendered `export enum` declaration text.
   */
  private generateEnum(enumDeclaration: WebIdlEnum): string {
    const lines: string[] = [`export enum ${this.sanitizeIdentifier(enumDeclaration.name)} {`];
    for (const value of enumDeclaration.values) {
      const variantName = this.formatEnumVariant(value);
      lines.push(`  ${variantName},`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Renders a single Web IDL dictionary as an FLINT `struct` declaration.
   *
   * @param dict - Dictionary AST node to render.
   * @returns The rendered `struct` declaration text.
   */
  private generateDictionary(dict: WebIdlDictionary): string {
    const lines: string[] = [`struct ${this.sanitizeIdentifier(dict.name)} {`];
    for (const member of dict.members) {
      const fieldName = this.sanitizeIdentifier(member.name);
      let fieldType = this.mapType(member.type);
      if (!member.required && !member.type.nullable) {
        fieldType = `Option<${fieldType}>`;
      }
      lines.push(`  ${fieldName}: ${fieldType};`);
    }
    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Renders a single Web IDL interface as an FLINT `interface` declaration with getter/setter/operation signatures.
   *
   * @param iface - Interface AST node to render.
   * @returns The rendered `interface` declaration text.
   */
  private generateInterface(iface: WebIdlInterface): string {
    const lines: string[] = [`interface ${this.sanitizeIdentifier(iface.name)} {`];

    // Attributes as getter / setter functions
    for (const member of iface.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterName = `get_${this.toSnakeCase(member.name)}`;
        lines.push(`  fn ${getterName}() -> ${attributeType};`);

        if (!member.readonly) {
          const setterName = `set_${this.toSnakeCase(member.name)}`;
          lines.push(`  fn ${setterName}(value: ${attributeType}) -> unit;`);
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = this.toSnakeCase(member.name);
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(`  fn ${opName}(${arguments_}) -> ${returnType};`);
      }
    }

    lines.push('}');
    return lines.join('\n');
  }

  /**
   * Renders `import capability` bindings for every attribute and operation member of a Web IDL interface.
   *
   * @param iface - Interface AST node whose members become capability imports.
   * @param prefix - Host capability namespace prefix.
   * @returns The rendered `import capability` statement lines.
   */
  private generateCapabilityImports(iface: WebIdlInterface, prefix: string): string[] {
    const lines: string[] = [];
    const ifaceNameSnake = this.toSnakeCase(iface.name);

    for (const member of iface.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterProperty = `get_${this.toSnakeCase(member.name)}`;
        const getterAlias = `${ifaceNameSnake}_${getterProperty}`;
        lines.push(
          `import capability "${prefix}.${iface.name}.${getterProperty}" as ${getterAlias}() -> ${attributeType};`,
        );

        if (!member.readonly) {
          const setterProperty = `set_${this.toSnakeCase(member.name)}`;
          const setterAlias = `${ifaceNameSnake}_${setterProperty}`;
          lines.push(
            `import capability "${prefix}.${iface.name}.${setterProperty}" as ${setterAlias}(value: ${attributeType}) -> unit;`,
          );
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = member.name;
        const opNameSnake = this.toSnakeCase(opName);
        const alias = `${ifaceNameSnake}_${opNameSnake}`;
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(
          `import capability "${prefix}.${iface.name}.${opName}" as ${alias}(${arguments_}) -> ${returnType};`,
        );
      }
    }

    return lines;
  }

  /**
   * Renders `import capability` bindings for every attribute and operation member of a Web IDL namespace.
   *
   * @param ns - Namespace AST node whose members become capability imports.
   * @param prefix - Host capability namespace prefix.
   * @returns The rendered `import capability` statement lines.
   */
  private generateNamespaceCapabilityImports(ns: WebIdlNamespace, prefix: string): string[] {
    const lines: string[] = [];
    const nsNameSnake = this.toSnakeCase(ns.name);

    for (const member of ns.members) {
      if (member.kind === 'attribute') {
        const attributeType = this.mapType(member.type);
        const getterProperty = `get_${this.toSnakeCase(member.name)}`;
        const getterAlias = `${nsNameSnake}_${getterProperty}`;
        lines.push(
          `import capability "${prefix}.${ns.name}.${getterProperty}" as ${getterAlias}() -> ${attributeType};`,
        );

        if (!member.readonly) {
          const setterProperty = `set_${this.toSnakeCase(member.name)}`;
          const setterAlias = `${nsNameSnake}_${setterProperty}`;
          lines.push(
            `import capability "${prefix}.${ns.name}.${setterProperty}" as ${setterAlias}(value: ${attributeType}) -> unit;`,
          );
        }
      } else if (member.kind === 'operation' && member.name !== undefined) {
        const opName = member.name;
        const opNameSnake = this.toSnakeCase(opName);
        const alias = `${nsNameSnake}_${opNameSnake}`;
        const arguments_ = member.arguments
          .map((argument) => `${this.sanitizeIdentifier(argument.name)}: ${this.mapType(argument.type)}`)
          .join(', ');
        const returnType = this.mapType(member.returnType);
        lines.push(`import capability "${prefix}.${ns.name}.${opName}" as ${alias}(${arguments_}) -> ${returnType};`);
      }
    }

    return lines;
  }

  /**
   * Resolves a user-supplied custom type mapping for the given type, if configured.
   *
   * @param type - Web IDL type reference to check.
   * @returns The rendered custom type text, or `undefined` when no custom mapping applies.
   */
  private mapCustomType(type: WebIdlType): string | undefined {
    const custom = this.options.customTypeMappings?.[type.name];
    if (custom === undefined) return undefined;
    return type.nullable ? `Option<${custom}>` : custom;
  }

  /**
   * Maps a Web IDL `sequence<T>`/`FrozenArray<T>` type to an FLINT `Vector<T>` rendering.
   *
   * @param type - Sequence or frozen-array type to map.
   * @returns The rendered `Vector<...>` type text.
   */
  private mapSequenceType(type: WebIdlType): string {
    const inner = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'u32';
    return `Vector<${inner}>`;
  }

  /**
   * Maps a Web IDL `Promise<T>` type to an FLINT `Future<T>` rendering.
   *
   * @param type - Promise type to map.
   * @returns The rendered `Future<...>` type text.
   */
  private mapPromiseType(type: WebIdlType): string {
    const inner = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'unit';
    return `Future<${inner}>`;
  }

  /**
   * Maps a Web IDL `record<K, V>` type to an FLINT `Map<K, V>` rendering.
   *
   * @param type - Record type to map.
   * @returns The rendered `Map<...>` type text.
   */
  private mapRecordType(type: WebIdlType): string {
    const key = type.typeArguments?.[0] ? this.mapType(type.typeArguments[0]) : 'string';
    const value = type.typeArguments?.[1] ? this.mapType(type.typeArguments[1]) : 'string';
    return `Map<${key}, ${value}>`;
  }

  /**
   * Maps a Web IDL union type to the FLINT type of its first non-nullish member, defaulting to `string`.
   *
   * @param type - Union type to map.
   * @returns The rendered FLINT type text.
   */
  private mapUnionType(type: WebIdlType): string {
    const nonNull = type.unionTypes?.filter((u) => u.name !== 'undefined' && u.name !== 'void');
    return nonNull && nonNull.length > 0 ? this.mapType(nonNull[0]) : 'string';
  }

  /**
   * Maps a Web IDL container type (`sequence`/`frozen-array`, `promise`, `record`, or `union`) to its FLINT rendering.
   *
   * @param type - Container type to map.
   * @returns The rendered FLINT type text, without `Option<...>` nullability wrapping.
   */
  private mapContainerType(type: WebIdlType): string {
    switch (type.kind) {
      case 'sequence':
      case 'frozen-array': {
        return this.mapSequenceType(type);
      }
      case 'promise': {
        return this.mapPromiseType(type);
      }
      case 'record': {
        return this.mapRecordType(type);
      }
      case 'union': {
        return this.mapUnionType(type);
      }
      default: {
        return this.sanitizeIdentifier(type.name);
      }
    }
  }

  /**
   * Maps a Web IDL type reference to its FLINT rendering, honoring custom type mappings and nullability.
   *
   * @param type - Web IDL type reference to map.
   * @returns The rendered FLINT type text.
   */
  public mapType(type: WebIdlType): string {
    const custom = this.mapCustomType(type);
    if (custom !== undefined) return custom;

    let result: string;

    switch (type.kind) {
      case 'primitive': {
        result = this.mapPrimitive(type.name);
        break;
      }
      case 'string': {
        result = 'string';
        break;
      }
      case 'buffer': {
        result = 'bytes';
        break;
      }
      default: {
        result = this.mapContainerType(type);
        break;
      }
    }

    if (type.nullable) {
      return `Option<${result}>`;
    }

    return result;
  }

  /**
   * Maps a Web IDL primitive type name to its FLINT scalar type equivalent.
   *
   * @param name - Web IDL primitive type name.
   * @returns The mapped FLINT scalar type name.
   */
  private mapPrimitive(name: string): string {
    return WEB_IDL_TO_FLINT_PRIMITIVE_TYPES[name] ?? 'u32';
  }

  /**
   * Sanitizes a Web IDL identifier for use as an FLINT identifier, escaping reserved keywords.
   *
   * @param name - Source identifier to sanitize.
   * @returns The sanitized FLINT identifier.
   */
  private sanitizeIdentifier(name: string): string {
    const reserved = new Set([
      'as',
      'break',
      'case',
      'const',
      'continue',
      'do',
      'else',
      'enum',
      'export',
      'fn',
      'for',
      'if',
      'import',
      'in',
      'inline',
      'interface',
      'iter',
      'let',
      'match',
      'module',
      'mut',
      'noinline',
      'record',
      'return',
      'struct',
      'switch',
      'while',
      'yield',
    ]);

    const sanitized = name.replaceAll(/[^a-zA-Z0-9_]/g, '_');
    if (reserved.has(sanitized)) {
      return `_${sanitized}`;
    }
    return sanitized;
  }

  /**
   * Converts a camelCase or mixed-case identifier to `snake_case`.
   *
   * @param string_ - Identifier to convert.
   * @returns The converted `snake_case` identifier.
   */
  private toSnakeCase(string_: string): string {
    return string_
      .replaceAll(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replaceAll(/[^a-zA-Z0-9_]/g, '_')
      .toLowerCase();
  }

  /**
   * Formats a raw Web IDL enum value string into a PascalCase FLINT enum variant name.
   *
   * @param value - Raw enum value string (e.g. `'readwrite'`, `'aes-gcm'`).
   * @returns The formatted PascalCase variant name.
   */
  private formatEnumVariant(value: string): string {
    // Convert string like "readwrite" -> "Readwrite", "aes-gcm" -> "AesGcm"
    const cleaned = value.replaceAll(/[^a-zA-Z0-9]/g, ' ');
    const parts = cleaned.split(/\s+/).filter(Boolean);
    if (parts.length === 0) return 'Variant';

    return parts.map((part) => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase()).join('');
  }
}

const WEB_IDL_TO_FLINT_PRIMITIVE_TYPES: Readonly<Record<string, string>> = {
  boolean: 'bool',
  byte: 'i32',
  short: 'i32',
  long: 'i32',
  octet: 'u32',
  'unsigned short': 'u32',
  'unsigned long': 'u32',
  'long long': 'i64',
  bigint: 'i64',
  'unsigned long long': 'u64',
  float: 'f32',
  'unrestricted float': 'f32',
  double: 'f64',
  'unrestricted double': 'f64',
  void: 'unit',
  undefined: 'unit',
};

/**
 * Generates FLINT header struct/interface/capability-import bindings for a parsed Web IDL module.
 *
 * @param module - Parsed Web IDL module to generate bindings from.
 * @param options - Generation options such as capability prefix and custom type mappings.
 * @returns The rendered FLINT source text.
 */
export function generateFlintBindings(module: WebIdlModule, options?: FlintBindingOptions): string {
  return new FlintBindingGenerator(module, options).generate();
}
