//! Reed-Solomon error correction over GF(64) for MaxiCode.
//!
//! MaxiCode uses ZXing's `MAXICODE_FIELD_64` — the field generated by the
//! primitive polynomial `x^6 + x + 1` (`0x43`) with generator `α = 2` and a
//! Reed-Solomon generator polynomial whose roots are `α^1 … α^n` (generator
//! base 1). The arithmetic mirrors the Data Matrix corrector in
//! `matrix-code-common`, only over a 64-element field, and only the blind
//! error corrector is needed (ZXing's MaxiCode decoder does not feed erasures).

/// The MaxiCode primitive polynomial (`x^6 + x + 1`).
const PRIMITIVE: u16 = 0x43;
/// Number of elements in GF(64).
const SIZE: usize = 64;
/// Order of the multiplicative group (`SIZE - 1`).
const ORDER: usize = SIZE - 1;

/// Precomputed exp/log tables for GF(64) arithmetic.
#[derive(Debug)]
struct GaloisField {
    /// `exp[i] = α^i` (`α = 2`), doubled length so multiplication needn't wrap.
    exp: [u8; 2 * SIZE],
    /// `log[x]` such that `α^log[x] = x` (undefined for `x = 0`).
    log: [u8; SIZE],
}

impl GaloisField {
    /// Build the exp/log tables for the MaxiCode field.
    fn new() -> Self {
        let mut exp = [0u8; 2 * SIZE];
        let mut log = [0u8; SIZE];
        let mut value: u16 = 1;
        for power in 0..ORDER {
            exp[power] = value as u8;
            log[value as usize] = power as u8;
            value <<= 1;
            if value & (SIZE as u16) != 0 {
                value ^= PRIMITIVE;
            }
        }
        // Mirror the first `ORDER` entries so `exp[a + b]` is always in range.
        for power in ORDER..(2 * SIZE) {
            exp[power] = exp[power - ORDER];
        }
        GaloisField { exp, log }
    }

    /// Multiply two field elements.
    fn mul(&self, a: u8, b: u8) -> u8 {
        if a == 0 || b == 0 {
            0
        } else {
            self.exp[self.log[a as usize] as usize + self.log[b as usize] as usize]
        }
    }

    /// Multiplicative inverse of a non-zero element (`α^(ORDER - log a)`).
    fn inv(&self, a: u8) -> u8 {
        self.exp[ORDER - self.log[a as usize] as usize]
    }
}

/// Compute the Reed-Solomon generator polynomial of degree `count`, whose roots
/// are `α^1 … α^count`. Returns `count + 1` coefficients, highest degree first.
fn generator(field: &GaloisField, count: usize) -> Vec<u8> {
    let mut poly = vec![1u8];
    for index in 0..count {
        let root = field.exp[index + 1];
        let mut next = vec![0u8; poly.len() + 1];
        for (position, &coefficient) in poly.iter().enumerate() {
            next[position] ^= coefficient;
            next[position + 1] ^= field.mul(coefficient, root);
        }
        poly = next;
    }
    poly
}

/// Compute `count` Reed-Solomon error-correction codewords for `data`.
#[tracing::instrument(skip_all)]
pub fn error_correction(data: &[u8], count: usize) -> Vec<u8> {
    let field = GaloisField::new();
    let gen = generator(&field, count);

    let mut remainder = vec![0u8; count];
    for &byte in data {
        let factor = byte ^ remainder[0];
        remainder.remove(0);
        remainder.push(0);
        if factor != 0 {
            for (index, &coefficient) in gen.iter().enumerate().skip(1) {
                remainder[index - 1] ^= field.mul(coefficient, factor);
            }
        }
    }
    remainder
}

/// Grow `v` to at least `len` elements, zero-filling any new tail.
fn grow(v: &mut Vec<u8>, len: usize) {
    if v.len() < len {
        v.resize(len, 0);
    }
}

/// Correct a MaxiCode Reed-Solomon codeword in place, recovering up to `ecc / 2`
/// symbol errors. `block` holds the `data || ecc` codewords with the
/// highest-degree coefficient first (data codewords, then the error-correction
/// codewords, in the order [`error_correction`] appends them). The generator's
/// first root is `α^1` (generator base 1), so no leading `X^(1-b)` factor appears
/// in the Forney magnitude formula.
///
/// Returns the number of corrected symbols on success, or `None` when the block
/// carries more errors than the code can repair.
#[tracing::instrument(skip_all)]
pub fn correct(block: &mut [u8], ecc: usize) -> Option<usize> {
    let field = GaloisField::new();
    let length = block.len();

    // Syndromes S_i = r(α^(i + 1)); all-zero means the codeword is already valid.
    let mut syndromes = vec![0u8; ecc];
    let mut all_zero = true;
    for (index, syndrome) in syndromes.iter_mut().enumerate() {
        let alpha = field.exp[index + 1];
        let mut value = 0u8;
        for &coefficient in block.iter() {
            value = field.mul(value, alpha) ^ coefficient;
        }
        *syndrome = value;
        if value != 0 {
            all_zero = false;
        }
    }
    if all_zero {
        return Some(0);
    }

    // Berlekamp-Massey: derive the error locator `lambda`.
    let mut lambda = vec![1u8];
    let mut previous = vec![1u8];
    let mut errors = 0usize;
    let mut shift = 1usize;
    let mut discrepancy_previous = 1u8;
    for round in 0..ecc {
        let mut discrepancy = syndromes[round];
        for index in 1..=errors {
            if index < lambda.len() {
                discrepancy ^= field.mul(lambda[index], syndromes[round - index]);
            }
        }
        if discrepancy == 0 {
            shift += 1;
        } else if 2 * errors <= round {
            let saved = lambda.clone();
            let scale = field.mul(discrepancy, field.inv(discrepancy_previous));
            grow(&mut lambda, shift + previous.len());
            for (index, &coefficient) in previous.iter().enumerate() {
                lambda[index + shift] ^= field.mul(scale, coefficient);
            }
            previous = saved;
            errors = round + 1 - errors;
            discrepancy_previous = discrepancy;
            shift = 1;
        } else {
            let scale = field.mul(discrepancy, field.inv(discrepancy_previous));
            grow(&mut lambda, shift + previous.len());
            for (index, &coefficient) in previous.iter().enumerate() {
                lambda[index + shift] ^= field.mul(scale, coefficient);
            }
            shift += 1;
        }
    }

    if 2 * errors > ecc {
        return None;
    }

    // Chien search: a root of Λ at α^(-i) marks an error at codeword position
    // `length - 1 - i` (counting from the highest-degree coefficient).
    let mut positions: Vec<usize> = Vec::new();
    for index in 0..length {
        let x_inverse = field.exp[(ORDER - (index % ORDER)) % ORDER];
        let mut sum = 0u8;
        let mut power = 1u8;
        for &coefficient in lambda.iter() {
            sum ^= field.mul(coefficient, power);
            power = field.mul(power, x_inverse);
        }
        if sum == 0 {
            positions.push(length - 1 - index);
        }
    }
    if positions.len() != errors {
        return None;
    }

    // Forney: errata evaluator Ω(x) = S(x)·Λ(x) mod x^ecc, then each magnitude is
    // Ω(X⁻¹) / Λ'(X⁻¹) (generator base 1 drops the usual `X` factor).
    let mut omega = vec![0u8; ecc];
    for (index, cell) in omega.iter_mut().enumerate() {
        let mut sum = 0u8;
        for tap in 0..=index {
            if tap < lambda.len() {
                sum ^= field.mul(lambda[tap], syndromes[index - tap]);
            }
        }
        *cell = sum;
    }

    for &position in &positions {
        let degree_from_high = length - 1 - position;
        let locator = field.exp[degree_from_high % ORDER];
        let locator_inverse = field.inv(locator);

        let mut omega_value = 0u8;
        let mut power = 1u8;
        for &coefficient in omega.iter() {
            omega_value ^= field.mul(coefficient, power);
            power = field.mul(power, locator_inverse);
        }

        // Formal derivative of Λ: only odd-degree terms survive over GF(2).
        let mut derivative = 0u8;
        let mut power = 1u8;
        for (index, &coefficient) in lambda.iter().enumerate() {
            if index % 2 == 1 {
                derivative ^= field.mul(coefficient, power);
            }
            if index >= 1 {
                power = field.mul(power, locator_inverse);
            }
        }
        if derivative == 0 {
            return None;
        }

        block[position] ^= field.mul(omega_value, field.inv(derivative));
    }

    // Verify the repair by recomputing the syndromes.
    for index in 0..ecc {
        let alpha = field.exp[index + 1];
        let mut value = 0u8;
        for &coefficient in block.iter() {
            value = field.mul(value, alpha) ^ coefficient;
        }
        if value != 0 {
            return None;
        }
    }
    Some(positions.len())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn field_round_trips() {
        let field = GaloisField::new();
        assert_eq!(field.mul(0, 5), 0);
        assert_eq!(field.mul(1, 42), 42);
        assert_eq!(field.exp[field.log[42] as usize], 42);
        // Every non-zero element times its inverse is 1.
        for a in 1..SIZE as u8 {
            assert_eq!(field.mul(a, field.inv(a)), 1);
        }
    }

    /// Build the `data || ecc` codeword the encoder would emit for `data`.
    fn codeword(data: &[u8], ecc: usize) -> Vec<u8> {
        let mut block = data.to_vec();
        block.extend(error_correction(data, ecc));
        block
    }

    #[test]
    fn leaves_a_clean_codeword_untouched() {
        let mut block = codeword(&[1, 2, 3, 4, 5], 10);
        let expected = block.clone();
        assert_eq!(correct(&mut block, 10), Some(0));
        assert_eq!(block, expected);
    }

    #[test]
    fn corrects_up_to_half_the_ecc_codewords() {
        let expected = codeword(&[10, 20, 30, 40, 50, 60], 10);
        let mut block = expected.clone();
        block[0] ^= 0x1f;
        block[3] ^= 0x2a;
        block[9] ^= 0x11;
        block[12] ^= 0x07;
        block[15] ^= 0x30;
        assert_eq!(correct(&mut block, 10), Some(5));
        assert_eq!(block, expected);
    }

    #[test]
    fn reports_uncorrectable_blocks() {
        let mut block = codeword(&[1, 2, 3, 4], 6);
        // 4 errors exceed the 3-symbol capacity of 6 ECC codewords.
        block[0] ^= 0x11;
        block[2] ^= 0x22;
        block[4] ^= 0x14;
        block[6] ^= 0x08;
        assert_eq!(correct(&mut block, 6), None);
    }
}
