packages:
  - apps/**
  - packages/**

catalog:
  '@changesets/cli': ^2.31.0
  '@types/js-yaml': ^4.0.9
  '@vue/compiler-sfc': ^3.5.35
  'js-yaml': ^4.2.0
  'luxon': ^3.7.2
  '@types/luxon': ^3.7.1
  '@floating-ui/vue': ^1.1.11
  'highlight.js': ^11.11.1
  'monaco-editor': ^0.55.1
  marked: ^18.0.5
  nanoid: ^5.1.11
  wrangler: ^4.98.0
  zod: ^4.4.3

catalogs:
  eslint:
    '@intlify/eslint-plugin-vue-i18n': ^4.5.1
    eslint-plugin-unicorn: ^64.0.0
    '@typescript-eslint/eslint-plugin': ^8.60.1
    '@typescript-eslint/parser': ^8.60.1
    eslint: ^10.4.1
    eslint-import-resolver-typescript: ^4.4.5
    eslint-plugin-import-x: ^4.16.2
    eslint-plugin-vue: ^10.9.2
    eslint-plugin-vuejs-accessibility: ^2.5.0
    typescript-eslint: ^8.60.1
    vue-eslint-parser: ^10.4.1

  stylelint:
    postcss-html: ^1.8.1
    postcss-scss: ^4.0.9
    stylelint: ^17.12.0
    stylelint-config-recommended-vue: ^1.6.1
    stylelint-config-standard: ^40.0.0
    stylelint-config-standard-scss: ^17.0.0

  prettier:
    prettier: ^3.8.3

  vue:
    '@intlify/unplugin-vue-i18n': ^11.2.3
    '@vue/test-utils': ^2.4.10
    '@vue/tsconfig': ^0.9.1
    '@vitejs/plugin-vue': ^6.0.7
    '@vitejs/plugin-vue-jsx': ^5.1.5
    vue: ^3.5.35
    vue-i18n: ^11.4.4
    vue-router: ^4.6.4
    vue-tsc: ^3.3.3

  vite:
    autoprefixer: ^10.5.0
    postcss: ^8.5.15
    sass-embedded: ^1.100.0
    vite: ^8.0.16
    vite-plugin-pwa: ^1.3.0

  storybook:
    '@chromatic-com/storybook': ^5.2.1
    "chromatic": "^17.2.0"
    '@storybook/addon-a11y': ^10.4.2
    '@storybook/addon-docs': ^10.4.2
    '@storybook/addon-themes': ^10.4.2
    '@storybook/addon-vitest': ^10.4.2
    '@storybook/vue3-vite': ^10.4.2
    storybook: ^10.4.2

  testing:
    '@vitest/browser-playwright': ^4.1.8
    '@vitest/coverage-v8': ^4.1.8
    jsdom: ^29.1.1
    playwright: ^1.60.0
    vitest: ^4.1.8

  map:
    '@types/geojson': ^7946.0.16
    '@turf/turf': ^7.3.5
    maplibre-gl: ^5.24.0

  typescript:
    '@types/js-yaml': ^4.0.9
    '@types/node': ^24.13.0
    typescript: ~6.0.3

trustPolicy: no-downgrade

registries:
  default: https://registry.npmjs.org/

namedRegistries:
  gh: https://npm.pkg.github.com/

trustPolicyExclude:
  - tinyexec
  - ast-v8-to-istanbul
  - semver@6.3.1
  - '@trickfilm400/rollup-plugin-off-main-thread'

allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: true
  workerd: true

minimumReleaseAgeExclude:
  - vue-eslint-parser@10.4.1
