import { describe, expect, it } from 'vitest';

import { buildRobotsTxt } from './build-robots-txt';

describe('buildRobotsTxt', () => {
  it('emits a default allow-all policy when no input is provided', () => {
    const output = buildRobotsTxt();
    expect(output).toBe('User-agent: *\nDisallow:\n');
  });

  it('serialises a single group with disallow + allow rules', () => {
    const output = buildRobotsTxt({
      groups: [{ userAgent: '*', disallow: ['/admin/', '/private/'], allow: ['/admin/public/'] }],
    });
    expect(output).toBe('User-agent: *\nDisallow: /admin/\nDisallow: /private/\nAllow: /admin/public/\n');
  });

  it('supports multiple user-agent tokens per group separated by blank lines', () => {
    const output = buildRobotsTxt({
      groups: [{ userAgent: ['Googlebot', 'Bingbot'], disallow: ['/no-bots/'] }, { userAgent: '*' }],
    });
    expect(output).toBe(
      'User-agent: Googlebot\nUser-agent: Bingbot\nDisallow: /no-bots/\n\nUser-agent: *\nDisallow:\n',
    );
  });

  it('appends Sitemap, Host, comment, and Crawl-delay directives', () => {
    const output = buildRobotsTxt({
      comments: ['Generated by @mission-platform/seo'],
      groups: [{ userAgent: '*', disallow: ['/tmp/'], crawlDelay: 10 }],
      host: 'example.com',
      sitemaps: ['https://example.com/sitemap.xml', 'https://example.com/sitemap-news.xml'],
    });
    expect(output).toBe(
      [
        '# Generated by @mission-platform/seo',
        '',
        'User-agent: *',
        'Disallow: /tmp/',
        'Crawl-delay: 10',
        '',
        'Host: example.com',
        'Sitemap: https://example.com/sitemap.xml',
        'Sitemap: https://example.com/sitemap-news.xml',
        '',
      ].join('\n'),
    );
  });
});
