// AUTO-GENERATED by @mission-platform/vite-plugin-i18n. Do not edit by hand.
declare module 'virtual:i18n-locales' {
  export const supportedLocales: readonly ['en', 'ar', 'de', 'es', 'fr', 'he', 'it', 'ja', 'ko', 'nl', 'zh'];
  export type SupportedLocale = (typeof supportedLocales)[number];
  export const defaultLocale: 'en';
  const _default: readonly ['en', 'ar', 'de', 'es', 'fr', 'he', 'it', 'ja', 'ko', 'nl', 'zh'];
  export default _default;
}
