/// <reference types="vitest/config" />
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { defineWebComponentAppConfig } from '@mission-platform/vite-config';
import { seoPlugin } from '@mission-platform/vite-plugin-seo';

import {
  buildSitemapUrls,
  collectDocumentSlugs,
  discoverDocumentationRoots,
  SITE_ORIGIN,
} from './src/route-inventory.ts';

// The docs site renders the canonical Markdown that lives in the monorepo
// `docs/` and package-owned `docs/` directories (outside this app's root).
// Allow Vite's dev server to read from the repository root so the direct
// multi-root import in src/documentation.ts works in development as well.
const currentDirectory = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(currentDirectory, '../..');
const documentationRoots = discoverDocumentationRoots(repoRoot);

// ─── SEO / prerender route inventory ─────────────────────────────────────────
// Keep the route list shared by Vite's SEO files and the memory-history
// prerender script. The runtime documentation manifest remains the source of
// page content; this build-time list only determines emitted URLs.
const documentSlugs = collectDocumentSlugs(documentationRoots);

// One sitemap entry per canonical URL. The root/default document gets top
// priority; every other page is slightly lower.
const sitemapUrls = buildSitemapUrls(documentSlugs);

const SITEMAP_URL = `${SITE_ORIGIN}/sitemap.xml`;

const config = defineWebComponentAppConfig({
  overrides: {
    optimizeDeps: {
      include: ['mermaid'],
    },
    // Forge custom elements load their compiled CSS through shadow-root
    // `styleUrls`; keep even small sidecars addressable instead of turning
    // them into data URLs in the client bundle.
    build: {
      assetsInlineLimit: 0,
    },
    // The SEO companion plugin generates `robots.txt` + `sitemap.xml` from the
    // `@mission-platform/seo` builders into the app's `publicDir`, so they are
    // served in dev and copied into the build output. Route HTML is emitted by
    // the package-local memory-history prerender task after the client bundle.
    plugins: [
      seoPlugin({
        sitemap: { urls: sitemapUrls },
        robots: {
          comments: [
            'Mission Platform documentation',
            `Generated by @mission-platform/seo at ${new Date().toISOString()}`,
          ],
          groups: [{ userAgent: '*', allow: ['/'], disallow: ['/search'] }],
          sitemaps: [SITEMAP_URL],
          host: new URL(SITE_ORIGIN).host,
        },
      }),
    ],
    server: {
      fs: {
        allow: [repoRoot],
      },
    },
    test: {
      environment: 'jsdom',
      include: ['src/**/*.test.ts'],
    },
  },
});

export default config;
