export {
  ATTRIBUTE_ALIASES,
  CHILDREN_SNIPPET,
  CLASS_NAMES_HELPER,
  DYNAMIC_TAG,
  flattenSpecifier,
  HTML_CONTENT_TAG,
  HYPERSCRIPT_CALL,
  importBase,
  isComponentTagExpression,
  isEventAttribute,
  renderSnippet,
  SLOT_TAG,
  slotPropName,
  snippetName,
  svelteAttributeName,
  svelteEventName,
  toPascalCase,
} from "./names.js";
export {
  blockStatements,
  callArguments,
  endOfLiteral,
  endOfTypeArguments,
  indexesOfTopLevel,
  indexOfTopLevel,
  isBalanced,
  isIdentifierText,
  isTopLevel,
  isTypeReferenceText,
  memberCall,
  normalizeJsxText,
  parameterName,
  readBinary,
  readCallback,
  readTernary,
  scanSource,
  splitList,
  splitTopLevel,
  splitUnionMembers,
  stripComments,
  stripParentheses,
  stripSemicolon,
} from "./source-text.js";
export type {
  BinaryParts,
  CallbackParts,
  MemberCall,
  SourceScan,
  TernaryParts,
} from "./source-text.js";
