// Internal helper for the scanner façade (`scanner/index.ts`): a lazily-
// instantiated wrapper around the single wasm-bindgen scanner module, plus the
// base64 helper used to instantiate an inlined `data:` URI binary.
//
// This mirrors the identical helper in the sibling encoder/decoder packages so
// the scanner loads its wasm exactly the same way (inlined `data:` URI in the
// shipped build, plain URL in dev/test).

import type { InitInput, SyncInitInput } from './generated/scan/code-scan.js';

/** Async initialiser signature generated by wasm-bindgen (`--target web`). */
export type AsyncInit = (options?: { module_or_path: InitInput }) => Promise<unknown>;
/** Synchronous initialiser signature generated by wasm-bindgen. */
export type SyncInit = (options: { module: SyncInitInput }) => unknown;

/**
 * Decode a base64 string to bytes. Prefers the native `Uint8Array.fromBase64`
 * (available on recent runtimes) and falls back to `Buffer` (Node) or `atob`
 * (browser) so the inlined wasm can be instantiated on any target.
 */
export function decodeBase64(base64: string): Uint8Array {
  const constructor = Uint8Array as typeof Uint8Array & {
    fromBase64?: (value: string) => Uint8Array;
  };
  if (typeof constructor.fromBase64 === 'function') {
    return constructor.fromBase64(base64);
  }
  const runtime = globalThis as {
    Buffer?: { from(input: string, encoding: string): Uint8Array };
    atob?: (data: string) => string;
  };
  if (runtime.Buffer !== undefined) {
    return new Uint8Array(runtime.Buffer.from(base64, 'base64'));
  }
  const binary = runtime.atob!(base64);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

/**
 * A lazily-instantiated wrapper around the scanner wasm module. The module is
 * loaded on first use and cached.
 */
export class WasmModule {
  private initialised = false;
  private initPromise: Promise<void> | undefined;
  private readonly asyncInit: AsyncInit;
  private readonly syncInit: SyncInit;
  private readonly wasmUrl: string;
  private readonly label: string;

  constructor(asyncInit: AsyncInit, syncInit: SyncInit, wasmUrl: string, label: string) {
    this.asyncInit = asyncInit;
    this.syncInit = syncInit;
    this.wasmUrl = wasmUrl;
    this.label = label;
  }

  /** `true` once the module has been instantiated and its exports are live. */
  get ready(): boolean {
    return this.initialised;
  }

  /**
   * Best-effort synchronous init used by the sync entry points. When the bundled
   * wasm is an inlined `data:` URI (the shipped build) its bytes are available
   * immediately, so we can instantiate without any async `fetch`; otherwise this
   * is a no-op and the caller must have initialised the module explicitly.
   */
  ensureSyncInit(): void {
    if (this.initialised || !this.wasmUrl.startsWith('data:')) {
      return;
    }
    this.syncInit({ module: decodeBase64(this.wasmUrl.slice(this.wasmUrl.indexOf(',') + 1)) });
    this.initialised = true;
  }

  /** Instantiate the module synchronously from raw bytes (or a compiled module). */
  instantiateSync(wasm: SyncInitInput): void {
    if (this.initialised) {
      return;
    }
    this.syncInit({ module: wasm });
    this.initialised = true;
  }

  /** Instantiate the module asynchronously, resolving once it is ready. */
  instantiate(input?: InitInput): Promise<void> {
    if (this.initialised) {
      return Promise.resolve();
    }
    if (!this.initPromise) {
      const source: InitInput | undefined =
        input ??
        (this.wasmUrl.startsWith('data:')
          ? decodeBase64(this.wasmUrl.slice(this.wasmUrl.indexOf(',') + 1))
          : this.wasmUrl);
      this.initPromise = this.asyncInit(source === undefined ? undefined : { module_or_path: source })
        .then(() => {
          this.initialised = true;
        })
        .catch((error: unknown) => {
          // Allow a later retry rather than caching the rejection forever.
          this.initPromise = undefined;
          throw error;
        });
    }
    return this.initPromise;
  }

  /** Guard the synchronous entry points with a clear error when uninitialised. */
  assertInitialised(): void {
    if (!this.initialised) {
      throw new Error(
        `The code-scanner ${this.label} WebAssembly module is not initialised. Call ` +
          '`await initCodeScanner()` (or `initCodeScannerSync(bytes)`) before the synchronous ' +
          '`scanImageData`, or use the `*Async` variants.',
      );
    }
  }
}

export { type InitInput, type SyncInitInput } from './generated/scan/code-scan.js';
