/**
 * Astro content-collection schema generation.
 *
 * Astro has no separate per-component schema artifact: the content model is
 * expressed as a `content.config.ts` with one zod collection per component.
 * The neutral field kinds map directly onto zod validators, and `asset` uses
 * Astro's own `image()` helper so the collection benefits from image
 * optimisation.
 */
import { contentFields } from "@mission-platform/forge-cms-plugin-api";

import type {
  ContentComponent,
  ContentField,
} from "@mission-platform/forge-cms-plugin-api";

/** The zod (or `image()`) validator a neutral field kind maps onto. */
export function fieldToZod(field: ContentField): string {
  let validator: string;
  switch (field.kind.kind) {
    case "number": {
      validator = "z.number()";
      break;
    }
    case "boolean": {
      validator = "z.boolean()";
      break;
    }
    case "option": {
      validator = `z.enum([${field.kind.options.map((option) => `'${option}'`).join(", ")}])`;
      break;
    }
    case "asset": {
      validator = "image()";
      break;
    }
    case "link": {
      validator = "z.string().url()";
      break;
    }
    default: {
      validator = "z.string()";
      break;
    }
  }
  if (field.defaultValue !== undefined) {
    const literal =
      typeof field.defaultValue === "string"
        ? `'${field.defaultValue}'`
        : String(field.defaultValue);
    validator = `${validator}.default(${literal})`;
  } else if (!field.required) {
    validator = `${validator}.optional()`;
  }
  return validator;
}

/** The `defineCollection` block for one component. */
function collection(component: ContentComponent): string {
  const fields = contentFields(component);
  const entries = fields.map(
    (field) => `      ${field.prop}: ${fieldToZod(field)},`,
  );
  return [
    `  ${component.names.technicalName}: defineCollection({`,
    "    type: 'data',",
    "    schema: ({ image }) =>",
    "      z.object({",
    ...entries.map((entry) => `  ${entry}`),
    "      }),",
    "  }),",
  ].join("\n");
}

/** Emit an Astro `content.config.ts` with one collection per component. */
export function emitContentConfig(
  components: readonly ContentComponent[],
): string {
  return [
    "// Generated by @mission-platform/forge-cms-astro — do not edit by hand.",
    "import { defineCollection, z } from 'astro:content';",
    "",
    "export const collections = {",
    ...components.map((component) => collection(component)),
    "};",
    "",
  ].join("\n");
}
