// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  'mp.storybook-react': {
    badge: {
      pill: 'Pill badge';
      success: 'Success';
    };
    button: {
      primary: 'Primary';
      secondary: 'Secondary';
      tertiary: 'Notifications';
    };
    components: 'Components';
    description: {
      after: 'Open Storybook to explore the full component library.';
      before: 'A React showcase for';
    };
    title: 'Mission Platform Components';
  };
}
