export {
  assertCompatibleEmailHtml,
  CAN_I_EMAIL_FEATURES_URL,
  CAN_I_EMAIL_INLINE_STYLES_URL,
  CAN_I_EMAIL_MEDIA_QUERIES_URL,
  CAN_I_EMAIL_MAX_WIDTH_URL,
  CAN_I_EMAIL_TABLES_URL,
  COMPATIBILITY_REVIEWED,
  EMAIL_ALLOWED_TAGS,
} from './policy';
