/**
 * A minimal {@link FrameworkOutputPlugin} stub used by the API specifications.
 *
 * The contract and driver tests only care that a framework plugin is present
 * and reports an id, an output language, and source conventions — they must not
 * depend on a real target package, which would invert the dependency direction.
 */
import type {
  FrameworkOutputPlugin,
  GeneratedModule,
  TargetIntentions,
  SemanticModule,
  TargetContext,
} from "@mission-platform/forge-plugin-api";

/** Create a stub framework plugin with an overridable id. */
export function stubFramework(id = "react"): FrameworkOutputPlugin {
  return {
    id,
    outputLanguage: "tsx",
    source: {
      componentExtension: ".tsx",
      componentImportExtension: ".js",
      composableExtension: ".ts",
      entryExtension: ".tsx",
      componentExport: "named",
    },
    lower: (ir: SemanticModule, context: TargetContext): TargetIntentions => ({
      framework: id,
      module: ir,
      context,
    }),
    optimize: (intentions: TargetIntentions): TargetIntentions => intentions,
    generate: (intentions: TargetIntentions): GeneratedModule => ({
      code: `// generated by the ${id} stub for ${intentions.context.componentName ?? "module"}\n`,
      lang: "tsx",
    }),
    build: {},
  };
}
