/**
 * Jekyll data-file and configuration generation.
 *
 * Liquid cannot introspect an include: a template that receives
 * `include.variant` has no way to discover that the argument exists, which
 * options it accepts, or what it falls back to. Jekyll's answer to that is
 * `_data/*.yml` — YAML that Jekyll loads into `site.data` before rendering — so
 * the neutral content model is published there as a machine-readable schema and
 * an editor UI, a link checker, or a component gallery can be driven from it
 * without parsing a single `.html` partial.
 *
 * The YAML is written by hand rather than through a serialiser: the emitted
 * shape is small and fully known, and hand-writing keeps key order, comment
 * banner, and quoting stable across releases — a serialiser's incidental
 * formatting choices would otherwise churn the diff of a generated site. Every
 * string scalar is single-quoted so a value like `no` or `1.0` survives as the
 * string it was in TypeScript.
 */
import { contentFields } from "@mission-platform/forge-cms-plugin-api";

import { DEFAULT_INCLUDE_NAMESPACE, includePath } from "./template.js";

import type {
  ContentComponent,
  ContentDefaultValue,
  ContentField,
  ContentFieldKindName,
} from "@mission-platform/forge-cms-plugin-api";

/** The vocabulary the neutral field kinds are published under in `_data`. */
export type JekyllFieldType = "string" | "number" | "boolean" | "enum" | "slot";

/**
 * The neutral kind → Jekyll type mapping.
 *
 * Jekyll stores content as plain YAML and renders it through Liquid, so it has
 * no richer notion of an asset or a link than "a string a template interpolates
 * into an `src`/`href`". Collapsing `text`/`richtext`/`asset`/`link` onto
 * `string` is therefore lossless for the renderer; the original TypeScript type
 * is still recoverable from the neutral model when a stricter target needs it.
 */
const FIELD_TYPES: Readonly<Record<ContentFieldKindName, JekyllFieldType>> = {
  text: "string",
  richtext: "string",
  asset: "string",
  link: "string",
  number: "number",
  boolean: "boolean",
  option: "enum",
  children: "slot",
};

const GENERATED_BANNER =
  "# Generated by @mission-platform/forge-cms-jekyll — do not edit by hand.";

/** The Jekyll data type a neutral field is published as. */
export function fieldToJekyllType(field: ContentField): JekyllFieldType {
  return FIELD_TYPES[field.kind.kind];
}

/** A single-quoted YAML string, with embedded quotes doubled per the spec. */
function yamlString(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

/** A YAML scalar for a neutral default value. */
export function yamlScalar(value: ContentDefaultValue): string {
  return typeof value === "string" ? yamlString(value) : String(value);
}

/** The YAML block describing one field, indented as a `fields:` sequence item. */
function fieldBlock(field: ContentField): readonly string[] {
  const lines = [
    `    - name: ${yamlString(field.prop)}`,
    `      type: ${fieldToJekyllType(field)}`,
    `      required: ${String(field.required)}`,
  ];
  if (field.defaultValue !== undefined) {
    lines.push(`      default: ${yamlScalar(field.defaultValue)}`);
  }
  if (field.description !== undefined) {
    lines.push(`      description: ${yamlString(field.description)}`);
  }
  if (field.kind.kind === "option") {
    lines.push(
      "      values:",
      ...field.kind.options.map((option) => `        - ${yamlString(option)}`),
    );
  }
  return lines;
}

/** The YAML block describing one component, as a top-level sequence item. */
function componentBlock(
  component: ContentComponent,
  namespace: string,
): readonly string[] {
  return [
    `- name: ${yamlString(component.names.technicalName)}`,
    `  display_name: ${yamlString(component.names.displayName)}`,
    `  include: ${yamlString(includePath(component, namespace))}`,
    ...(component.fields.length === 0
      ? ["  fields: []"]
      : [
          "  fields:",
          ...component.fields.flatMap((field) => fieldBlock(field)),
        ]),
  ];
}

/**
 * Emit `_data/forge-components.yml`: the schema of every emitted include.
 *
 * A top-level sequence is used rather than a mapping so `site.data` iteration
 * preserves the compiler's component order, which is the order a gallery or a
 * generated documentation page should list them in.
 */
export function emitComponentsData(
  components: readonly ContentComponent[],
  namespace: string = DEFAULT_INCLUDE_NAMESPACE,
): string {
  return [
    GENERATED_BANNER,
    ...components.flatMap((component) => componentBlock(component, namespace)),
    "",
  ].join("\n");
}

/**
 * Emit the `_config.yml` fragment registering the generated includes.
 *
 * Jekyll merges site configuration into `site.*`, so publishing the namespace
 * and the per-component defaults here lets a layout build an include path or
 * fill a missing argument without hard-coding either. Defaults are duplicated
 * from the includes on purpose: a site that renders a component from data
 * (rather than from a literal `{% include %}`) never runs the `default:`
 * filters, and would otherwise see empty values.
 */
export function emitJekyllConfig(
  components: readonly ContentComponent[],
  namespace: string = DEFAULT_INCLUDE_NAMESPACE,
): string {
  const defaulted = components
    .map((component) => ({
      technicalName: component.names.technicalName,
      lines: contentFields(component).flatMap((field) =>
        field.defaultValue === undefined
          ? []
          : [`      ${field.prop}: ${yamlScalar(field.defaultValue)}`],
      ),
    }))
    .filter((entry) => entry.lines.length > 0);

  return [
    GENERATED_BANNER,
    "forge:",
    `  include_namespace: ${yamlString(namespace)}`,
    ...(defaulted.length === 0
      ? ["  defaults: {}"]
      : [
          "  defaults:",
          ...defaulted.flatMap((entry) => [
            `    ${entry.technicalName}:`,
            ...entry.lines,
          ]),
        ]),
    "",
  ].join("\n");
}
