export {
  ForgeTypography,
  type TypographyColor,
  type TypographyHorizontalAlign,
  type TypographyLineHeight,
  type TypographyProperties,
  type TypographyStyle,
  type TypographyStyleProperties,
  type TypographySize,
  type TypographyTarget,
  type TypographyUnderline,
  type TypographyVariant,
  type TypographyVerticalAlign,
  type TypographyWeight,
} from './atoms/forge-typography';
