// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  'mp.forms': {
    base_form_builder: {
      remove_rule_label: 'Remove rule';
    };
  };
}
