//! Configurable Reed-Solomon error correction over a binary extension field
//! GF(2^m), for the symbologies whose codeword size (and therefore field) is
//! not fixed at GF(256).
//!
//! Aztec Code is the motivating consumer: its data words are 6, 8, 10 or 12
//! bits wide depending on the symbol size — GF(64), GF(256), GF(1024) or
//! GF(4096) — and its mode message uses GF(16). Every one of those fields uses
//! a Reed-Solomon generator polynomial whose first root is `α^1` (`fcr = 1`),
//! matching the Data Matrix convention of the sibling [`crate::reed_solomon`]
//! module (which is the hard-wired GF(256) special case of this one).
//!
//! Field elements are carried as `u16` (large enough for the 12-bit GF(4096)
//! field). The public surface mirrors [`crate::reed_solomon`]: [`Field`] builds
//! the exp/log tables for a `(primitive, size)` pair, [`Field::error_correction`]
//! appends parity, and [`Field::correct`] repairs a received block in place.

/// A binary extension field GF(2^m) with precomputed exp/log tables.
#[derive(Debug)]
pub struct Field {
    /// The field order `2^m` (e.g. `64`, `256`, `1024`, `4096`).
    size: usize,
    /// The multiplicative group order, `size - 1`.
    order: usize,
    /// `exp[i] = α^i` (with `α = 2`), doubled in length so `exp[a + b]` needn't wrap.
    exp: Vec<u16>,
    /// `log[x]` such that `α^log[x] = x` (undefined for `x = 0`).
    log: Vec<u16>,
}

impl Field {
    /// Build the exp/log tables for GF(2^m) generated by the `primitive`
    /// polynomial (its bit `m` is the implicit leading term) with `size = 2^m`.
    #[tracing::instrument(skip_all)]
    pub fn new(primitive: u16, size: usize) -> Self {
        let order = size - 1;
        let mut exp = vec![0u16; 2 * order];
        let mut log = vec![0u16; size];
        let mut value: usize = 1;
        for power in 0..order {
            exp[power] = value as u16;
            log[value] = power as u16;
            value <<= 1;
            if value & size != 0 {
                value ^= primitive as usize;
            }
        }
        for power in order..2 * order {
            exp[power] = exp[power - order];
        }
        Field {
            size,
            order,
            exp,
            log,
        }
    }

    /// Multiply two field elements.
    #[tracing::instrument(skip_all)]
    pub fn mul(&self, a: u16, b: u16) -> u16 {
        if a == 0 || b == 0 {
            0
        } else {
            self.exp[self.log[a as usize] as usize + self.log[b as usize] as usize]
        }
    }

    /// Multiplicative inverse of a non-zero element (`α^(order - log a)`).
    #[tracing::instrument(skip_all)]
    pub fn inv(&self, a: u16) -> u16 {
        self.exp[self.order - self.log[a as usize] as usize]
    }

    /// `α^power`, wrapping the exponent into the multiplicative group.
    #[tracing::instrument(skip_all)]
    pub fn alpha(&self, power: usize) -> u16 {
        self.exp[power % self.order]
    }

    /// The Reed-Solomon generator polynomial of degree `count`, roots
    /// `α^1 … α^count`, highest degree first.
    #[tracing::instrument(skip_all)]
    fn generator(&self, count: usize) -> Vec<u16> {
        let mut poly = vec![1u16];
        for index in 0..count {
            let root = self.alpha(index + 1);
            let mut next = vec![0u16; poly.len() + 1];
            for (position, &coefficient) in poly.iter().enumerate() {
                next[position] ^= coefficient;
                next[position + 1] ^= self.mul(coefficient, root);
            }
            poly = next;
        }
        poly
    }

    /// Compute `count` Reed-Solomon error-correction symbols for `data`.
    #[tracing::instrument(skip_all)]
    pub fn error_correction(&self, data: &[u16], count: usize) -> Vec<u16> {
        let gen = self.generator(count);
        let mut remainder = vec![0u16; count];
        for &symbol in data {
            let factor = symbol ^ remainder[0];
            remainder.remove(0);
            remainder.push(0);
            if factor != 0 {
                for (index, &coefficient) in gen.iter().enumerate().skip(1) {
                    remainder[index - 1] ^= self.mul(coefficient, factor);
                }
            }
        }
        remainder
    }

    /// Correct a Reed-Solomon `data || ecc` block in place (highest-degree
    /// symbol first), recovering up to `ecc / 2` errors. Returns `true` when the
    /// block is clean or was fully repaired, `false` otherwise. Mirrors the
    /// `fcr = 1` syndrome / Berlekamp-Massey / Chien / Forney pipeline of the
    /// GF(256) [`crate::reed_solomon::correct`].
    #[tracing::instrument(skip_all)]
    pub fn correct(&self, block: &mut [u16], ecc: usize) -> bool {
        let length = block.len();

        let mut syndromes = vec![0u16; ecc];
        let mut all_zero = true;
        for (index, syndrome) in syndromes.iter_mut().enumerate() {
            let alpha = self.alpha(index + 1);
            let mut value = 0u16;
            for &coefficient in block.iter() {
                value = self.mul(value, alpha) ^ coefficient;
            }
            *syndrome = value;
            if value != 0 {
                all_zero = false;
            }
        }
        if all_zero {
            return true;
        }

        // Berlekamp-Massey: derive the error-locator polynomial `lambda`.
        let mut lambda = vec![1u16];
        let mut previous = vec![1u16];
        let mut errors = 0usize;
        let mut shift = 1usize;
        let mut discrepancy_previous = 1u16;
        for round in 0..ecc {
            let mut discrepancy = syndromes[round];
            for index in 1..=errors {
                if index < lambda.len() {
                    discrepancy ^= self.mul(lambda[index], syndromes[round - index]);
                }
            }
            if discrepancy == 0 {
                shift += 1;
            } else if 2 * errors <= round {
                let saved = lambda.clone();
                let scale = self.mul(discrepancy, self.inv(discrepancy_previous));
                grow(&mut lambda, shift + previous.len());
                for (index, &coefficient) in previous.iter().enumerate() {
                    lambda[index + shift] ^= self.mul(scale, coefficient);
                }
                previous = saved;
                errors = round + 1 - errors;
                discrepancy_previous = discrepancy;
                shift = 1;
            } else {
                let scale = self.mul(discrepancy, self.inv(discrepancy_previous));
                grow(&mut lambda, shift + previous.len());
                for (index, &coefficient) in previous.iter().enumerate() {
                    lambda[index + shift] ^= self.mul(scale, coefficient);
                }
                shift += 1;
            }
        }

        if errors == 0 || errors > ecc / 2 {
            return false;
        }

        // Chien search: a root at α^(-i) marks an error at position length-1-i.
        let mut positions: Vec<usize> = Vec::new();
        for index in 0..length {
            let x_inverse = self.exp[(self.order - (index % self.order)) % self.order];
            let mut sum = 0u16;
            let mut power = 1u16;
            for &coefficient in lambda.iter() {
                sum ^= self.mul(coefficient, power);
                power = self.mul(power, x_inverse);
            }
            if sum == 0 {
                positions.push(length - 1 - index);
            }
        }
        if positions.len() != errors {
            return false;
        }

        // Forney: Ω(x) = S(x)·Λ(x) mod x^ecc, magnitude Ω(X⁻¹) / Λ'(X⁻¹).
        let mut omega = vec![0u16; ecc];
        for (index, cell) in omega.iter_mut().enumerate() {
            let mut sum = 0u16;
            for tap in 0..=index {
                if tap < lambda.len() {
                    sum ^= self.mul(lambda[tap], syndromes[index - tap]);
                }
            }
            *cell = sum;
        }

        for &position in &positions {
            let degree_from_high = length - 1 - position;
            let locator = self.alpha(degree_from_high);
            let locator_inverse = self.inv(locator);

            let mut omega_value = 0u16;
            let mut power = 1u16;
            for &coefficient in omega.iter() {
                omega_value ^= self.mul(coefficient, power);
                power = self.mul(power, locator_inverse);
            }

            let mut derivative = 0u16;
            let mut power = 1u16;
            for (index, &coefficient) in lambda.iter().enumerate() {
                if index % 2 == 1 {
                    derivative ^= self.mul(coefficient, power);
                }
                if index >= 1 {
                    power = self.mul(power, locator_inverse);
                }
            }
            if derivative == 0 {
                return false;
            }

            block[position] ^= self.mul(omega_value, self.inv(derivative));
        }

        // Verify the repair by recomputing the syndromes.
        for index in 0..ecc {
            let alpha = self.alpha(index + 1);
            let mut value = 0u16;
            for &coefficient in block.iter() {
                value = self.mul(value, alpha) ^ coefficient;
            }
            if value != 0 {
                return false;
            }
        }
        true
    }

    /// The field order (`2^m`).
    #[tracing::instrument(skip_all)]
    pub fn size(&self) -> usize {
        self.size
    }
}

/// Grow `v` to at least `len` elements, zero-filling any new tail.
#[tracing::instrument(skip_all)]
fn grow(v: &mut Vec<u16>, len: usize) {
    if v.len() < len {
        v.resize(len, 0);
    }
}

#[cfg(test)]
mod tests {
    use super::Field;

    /// GF(256) with the Data Matrix primitive should agree with the hard-wired
    /// `reed_solomon` module on the canonical ECC vector.
    #[test]
    fn gf256_matches_the_data_matrix_reference_vector() {
        let field = Field::new(0x12D, 256);
        let ecc = field.error_correction(&[142, 164, 186], 5);
        assert_eq!(ecc, vec![114, 25, 5, 88, 102]);
    }

    #[test]
    fn gf16_round_trips_and_corrects_one_error() {
        // Aztec's mode-message field.
        let field = Field::new(0x13, 16);
        let data = [5u16, 9, 3];
        let mut block = data.to_vec();
        block.extend(field.error_correction(&data, 4));
        let clean = block.clone();
        assert!(field.correct(&mut block, 4));
        assert_eq!(block, clean, "clean block is unchanged");

        block[1] ^= 0xf;
        assert!(field.correct(&mut block, 4), "one error is within capacity");
        assert_eq!(block, clean, "single error recovered");
    }

    #[test]
    fn gf64_corrects_up_to_half_the_parity() {
        // Aztec's 6-bit data field (also MaxiCode).
        let field = Field::new(0x43, 64);
        let data: Vec<u16> = (0..10).collect();
        let mut block = data.clone();
        block.extend(field.error_correction(&data, 6));
        let clean = block.clone();

        block[0] ^= 0x2a;
        block[7] ^= 0x11;
        block[12] ^= 0x3f;
        assert!(field.correct(&mut block, 6), "three errors within capacity");
        assert_eq!(block, clean, "three errors recovered");
    }

    #[test]
    fn gf1024_builds_a_full_field() {
        // Aztec's 10-bit data field: exercise the table wrap and inverse.
        let field = Field::new(0x409, 1024);
        assert_eq!(field.size(), 1024);
        for value in 1..1024u16 {
            assert_eq!(field.mul(value, field.inv(value)), 1, "value {value} inverts");
        }
    }
}
