//! Reed-Solomon error correction over GF(256) for Data Matrix ECC 200.
//!
//! Data Matrix uses the field generated by the primitive polynomial
//! `x^8 + x^5 + x^3 + x^2 + 1` (`0x12D`) with generator `α = 2`, and a
//! Reed-Solomon generator polynomial whose roots are `α^1 … α^n` (base 1).

/// The Data Matrix primitive polynomial (`x^8 + x^5 + x^3 + x^2 + 1`).
const PRIMITIVE: u16 = 0x12D;

/// Precomputed exp/log tables for GF(256) arithmetic.
#[derive(Debug)]
struct GaloisField {
    /// `exp[i] = α^i` (with `α = 2`), doubled length so multiplication needn't wrap.
    exp: [u8; 512],
    /// `log[x]` such that `α^log[x] = x` (undefined for `x = 0`).
    log: [u8; 256],
}

impl GaloisField {
    /// Build the exp/log tables for the Data Matrix field.
    #[tracing::instrument(skip_all)]
    fn new() -> Self {
        let mut exp = [0u8; 512];
        let mut log = [0u8; 256];
        let mut value: u16 = 1;
        for power in 0..255 {
            exp[power] = value as u8;
            log[value as usize] = power as u8;
            value <<= 1;
            if value & 0x100 != 0 {
                value ^= PRIMITIVE;
            }
        }
        // Mirror the first 255 entries so `exp[a + b]` is always in range.
        for power in 255..512 {
            exp[power] = exp[power - 255];
        }
        GaloisField { exp, log }
    }

    /// Multiply two field elements.
    #[tracing::instrument(skip_all)]
    fn mul(&self, a: u8, b: u8) -> u8 {
        if a == 0 || b == 0 {
            0
        } else {
            self.exp[self.log[a as usize] as usize + self.log[b as usize] as usize]
        }
    }

    /// Multiplicative inverse of a non-zero element (`α^(255 - log a)`).
    #[tracing::instrument(skip_all)]
    fn inv(&self, a: u8) -> u8 {
        self.exp[255 - self.log[a as usize] as usize]
    }

    /// `α^power`, wrapping the exponent into the multiplicative cycle.
    #[inline]
    fn pow(&self, power: usize) -> u8 {
        self.exp[power % 255]
    }

    /// Multiply two polynomials (low-degree-first coefficient order).
    fn poly_mul(&self, a: &[u8], b: &[u8]) -> Vec<u8> {
        let mut out = vec![0u8; a.len() + b.len() - 1];
        for (i, &ai) in a.iter().enumerate() {
            if ai == 0 {
                continue;
            }
            for (j, &bj) in b.iter().enumerate() {
                out[i + j] ^= self.mul(ai, bj);
            }
        }
        out
    }
}

/// Compute the Reed-Solomon generator polynomial of degree `count`, whose roots
/// are `α^1 … α^count`. Returns `count + 1` coefficients, highest degree first.
#[tracing::instrument(skip_all)]
fn generator(field: &GaloisField, count: usize) -> Vec<u8> {
    let mut poly = vec![1u8];
    for index in 0..count {
        // Multiply the running product by `(x - α^(index + 1))`.
        let root = field.exp[index + 1];
        let mut next = vec![0u8; poly.len() + 1];
        for (position, &coefficient) in poly.iter().enumerate() {
            next[position] ^= coefficient; // x term
            next[position + 1] ^= field.mul(coefficient, root); // constant term
        }
        poly = next;
    }
    poly
}

/// Compute `count` Reed-Solomon error-correction codewords for `data`.
#[tracing::instrument(skip_all)]
pub fn error_correction(data: &[u8], count: usize) -> Vec<u8> {
    tracing::trace!(
        "reed-solomon: {} data codeword(s), {count} ecc codeword(s)",
        data.len()
    );
    let field = GaloisField::new();
    let gen = generator(&field, count);

    let mut remainder = vec![0u8; count];
    for &byte in data {
        let factor = byte ^ remainder[0];
        remainder.remove(0);
        remainder.push(0);
        if factor != 0 {
            // `gen[0]` is 1, so skip it and start from the next coefficient.
            for (index, &coefficient) in gen.iter().enumerate().skip(1) {
                remainder[index - 1] ^= field.mul(coefficient, factor);
            }
        }
    }
    remainder
}

/// Grow `v` to at least `len` elements, zero-filling any new tail.
#[tracing::instrument(skip_all)]
fn grow(v: &mut Vec<u8>, len: usize) {
    if v.len() < len {
        v.resize(len, 0);
    }
}

/// Correct a Data Matrix ECC 200 Reed-Solomon codeword in place, recovering up
/// to `ecc / 2` symbol errors. `block` holds the `data || ecc` codewords with
/// the highest-degree coefficient first (i.e. data codewords, then the
/// error-correction codewords, in the order [`error_correction`] appends them).
///
/// Returns `true` when the block is error-free or was fully corrected, and
/// `false` when it carries more errors than the code can repair. The syndromes,
/// Berlekamp-Massey locator, Chien search and Forney evaluator all account for
/// the Data Matrix generator whose first root is `α^1` (`fcr = 1`), so no
/// leading `X^(1-fcr)` factor appears in the magnitude formula.
#[tracing::instrument(skip_all)]
pub fn correct(block: &mut [u8], ecc: usize) -> bool {
    correct_with_erasures(block, ecc, &[])
}

/// Correct a Data Matrix ECC 200 Reed-Solomon codeword in place, treating the
/// codeword indices in `erasures` (0 = highest-degree coefficient) as **known**
/// damaged positions. Errors-and-erasures decoding repairs any mix satisfying
/// the Singleton bound `2·errors + erasures ≤ ecc`, so a symbol whose unreadable
/// modules are flagged as erasures (via low-confidence grey sampling) recovers
/// at up to twice the rate of blind error correction.
///
/// Passing an empty `erasures` slice is exactly the blind error corrector
/// [`correct`] uses. `erasures` indices outside the block are ignored.
#[tracing::instrument(skip_all)]
pub fn correct_with_erasures(block: &mut [u8], ecc: usize, erasures: &[usize]) -> bool {
    let field = GaloisField::new();
    let length = block.len();

    // Syndromes S_i = r(α^(i + 1)); a valid codeword has S(α^j) = 0 for the
    // generator's roots α^1 … α^ecc, so all-zero syndromes mean no errors.
    let mut syndromes = vec![0u8; ecc];
    let mut all_zero = true;
    for (index, syndrome) in syndromes.iter_mut().enumerate() {
        let alpha = field.exp[index + 1];
        let mut value = 0u8;
        for &coefficient in block.iter() {
            value = field.mul(value, alpha) ^ coefficient;
        }
        *syndrome = value;
        if value != 0 {
            all_zero = false;
        }
    }
    if all_zero {
        return true;
    }

    // Deduplicate and bound-check the erasure positions, mapping each to its
    // coefficient degree (position from the highest-degree end).
    let mut erasure_positions: Vec<usize> =
        erasures.iter().copied().filter(|&p| p < length).collect();
    erasure_positions.sort_unstable();
    erasure_positions.dedup();
    let erasure_count = erasure_positions.len();
    if erasure_count > ecc {
        return false;
    }

    // Erasure locator Λ0(x) = ∏(1 + X_e·x), X_e = α^(degree of the erasure).
    let mut erasure_locator = vec![1u8];
    for &position in &erasure_positions {
        let x = field.pow(length - 1 - position);
        erasure_locator = field.poly_mul(&erasure_locator, &[1, x]);
    }

    // Forney syndromes strip the erasures out of the syndrome sequence so the
    // Berlekamp-Massey search below locates only the *unknown* errors.
    let mut forney = syndromes.clone();
    for &position in &erasure_positions {
        let x = field.pow(length - 1 - position);
        for j in 0..forney.len().saturating_sub(1) {
            forney[j] = field.mul(forney[j], x) ^ forney[j + 1];
        }
    }

    // Berlekamp-Massey over the Forney syndromes: derive the (unknown) error
    // locator `lambda`. Only `ecc - erasure_count` syndromes carry error info.
    let rounds = ecc - erasure_count;
    let mut lambda = vec![1u8];
    let mut previous = vec![1u8];
    let mut errors = 0usize;
    let mut shift = 1usize;
    let mut discrepancy_previous = 1u8;
    for round in 0..rounds {
        let mut discrepancy = forney[round];
        for index in 1..=errors {
            if index < lambda.len() {
                discrepancy ^= field.mul(lambda[index], forney[round - index]);
            }
        }
        if discrepancy == 0 {
            shift += 1;
        } else if 2 * errors <= round {
            let saved = lambda.clone();
            let scale = field.mul(discrepancy, field.inv(discrepancy_previous));
            grow(&mut lambda, shift + previous.len());
            for (index, &coefficient) in previous.iter().enumerate() {
                lambda[index + shift] ^= field.mul(scale, coefficient);
            }
            previous = saved;
            errors = round + 1 - errors;
            discrepancy_previous = discrepancy;
            shift = 1;
        } else {
            let scale = field.mul(discrepancy, field.inv(discrepancy_previous));
            grow(&mut lambda, shift + previous.len());
            for (index, &coefficient) in previous.iter().enumerate() {
                lambda[index + shift] ^= field.mul(scale, coefficient);
            }
            shift += 1;
        }
    }

    if 2 * errors + erasure_count > ecc {
        return false;
    }

    // Combine the (unknown) error locator with the erasure locator into the full
    // errata locator Σ(x) = Λ(x)·Λ0(x), whose roots mark *both* errors and
    // erasures.
    let sigma = field.poly_mul(&lambda, &erasure_locator);
    let total_positions = errors + erasure_count;

    // Chien search: a root of Σ at α^(-i) marks an errata at the codeword
    // position `length - 1 - i` (counting from the highest-degree coefficient).
    let mut positions: Vec<usize> = Vec::new();
    for index in 0..length {
        let x_inverse = field.exp[(255 - (index % 255)) % 255];
        let mut sum = 0u8;
        let mut power = 1u8;
        for &coefficient in sigma.iter() {
            sum ^= field.mul(coefficient, power);
            power = field.mul(power, x_inverse);
        }
        if sum == 0 {
            positions.push(length - 1 - index);
        }
    }
    if positions.len() != total_positions {
        return false;
    }

    // Forney: errata evaluator Ω(x) = S(x)·Σ(x) mod x^ecc, then each magnitude is
    // Ω(X⁻¹) / Σ'(X⁻¹) (the `fcr = 1` generator drops the usual `X` factor).
    let mut omega = vec![0u8; ecc];
    for (index, cell) in omega.iter_mut().enumerate() {
        let mut sum = 0u8;
        for tap in 0..=index {
            if tap < sigma.len() {
                sum ^= field.mul(sigma[tap], syndromes[index - tap]);
            }
        }
        *cell = sum;
    }

    for &position in &positions {
        let degree_from_high = length - 1 - position;
        let locator = field.exp[degree_from_high % 255];
        let locator_inverse = field.inv(locator);

        let mut omega_value = 0u8;
        let mut power = 1u8;
        for &coefficient in omega.iter() {
            omega_value ^= field.mul(coefficient, power);
            power = field.mul(power, locator_inverse);
        }

        // Formal derivative of Σ: only the odd-degree terms survive over GF(2),
        // each evaluated at X⁻¹.
        let mut derivative = 0u8;
        let mut power = 1u8;
        for (index, &coefficient) in sigma.iter().enumerate() {
            if index % 2 == 1 {
                derivative ^= field.mul(coefficient, power);
            }
            if index >= 1 {
                power = field.mul(power, locator_inverse);
            }
        }
        if derivative == 0 {
            return false;
        }

        block[position] ^= field.mul(omega_value, field.inv(derivative));
    }

    // Verify the repair by recomputing the syndromes.
    for index in 0..ecc {
        let alpha = field.exp[index + 1];
        let mut value = 0u8;
        for &coefficient in block.iter() {
            value = field.mul(value, alpha) ^ coefficient;
        }
        if value != 0 {
            return false;
        }
    }
    true
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    #[tracing::instrument(skip_all)]
    fn field_multiplication_matches_known_products() {
        let field = GaloisField::new();
        assert_eq!(field.mul(0, 5), 0);
        assert_eq!(field.mul(1, 123), 123);
        // 2 * 2 = 4 in the field (no reduction yet), and log/exp round-trip.
        assert_eq!(field.mul(2, 2), 4);
        assert_eq!(field.exp[field.log[42] as usize], 42);
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn matches_the_reference_data_matrix_ecc_vector() {
        // Canonical ISO/IEC 16022 example: encoding "123456" yields data
        // codewords [142, 164, 186], whose five ECC 200 error-correction
        // codewords are [114, 25, 5, 88, 102].
        let ecc = error_correction(&[142, 164, 186], 5);
        assert_eq!(ecc, vec![114, 25, 5, 88, 102]);
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn produces_the_requested_number_of_codewords() {
        for count in [5usize, 7, 10, 12, 28] {
            assert_eq!(error_correction(&[1, 2, 3], count).len(), count);
        }
    }

    /// Build the `data || ecc` codeword the encoder would emit for `data`.
    #[tracing::instrument(skip_all)]
    fn codeword(data: &[u8], ecc: usize) -> Vec<u8> {
        let mut block = data.to_vec();
        block.extend(error_correction(data, ecc));
        block
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn leaves_an_error_free_codeword_untouched() {
        let mut block = codeword(&[142, 164, 186], 5);
        let expected = block.clone();
        assert!(correct(&mut block, 5));
        assert_eq!(block, expected, "a clean codeword is unchanged");
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn corrects_up_to_half_the_ecc_codewords() {
        // 5 ECC codewords tolerate up to 2 symbol errors.
        let expected = codeword(&[142, 164, 186], 5);
        let mut block = expected.clone();
        block[0] ^= 0x3f;
        block[6] ^= 0xa1;
        assert!(correct(&mut block, 5), "two errors are within capacity");
        assert_eq!(block, expected, "original codeword recovered");
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn reports_uncorrectable_blocks() {
        // Three errors exceed the two-symbol capacity of 5 ECC codewords.
        let mut block = codeword(&[142, 164, 186], 5);
        block[0] ^= 0x11;
        block[3] ^= 0x22;
        block[7] ^= 0x44;
        assert!(!correct(&mut block, 5), "too many errors to repair");
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn corrects_pure_erasures_up_to_the_ecc_count() {
        // With known positions, a symbol tolerates one erasure per ECC codeword
        // — twice the blind error capacity. All 5 codewords erased here.
        let expected = codeword(&[142, 164, 186], 5);
        let mut block = expected.clone();
        let erased = [0usize, 2, 4, 5, 7];
        for &position in &erased {
            block[position] ^= 0xa5;
        }
        assert!(
            correct_with_erasures(&mut block, 5, &erased),
            "five erasures are within the erasure capacity"
        );
        assert_eq!(block, expected, "original codeword recovered from erasures");
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn corrects_a_mix_of_errors_and_erasures() {
        // 2·errors + erasures ≤ ecc: one unknown error (costs 2) plus one known
        // erasure (costs 1) fits inside 5 ECC codewords.
        let expected = codeword(&[142, 164, 186], 5);
        let mut block = expected.clone();
        block[1] ^= 0x3f; // unknown error
        block[6] ^= 0xc4; // known erasure
        assert!(
            correct_with_erasures(&mut block, 5, &[6]),
            "one error + one erasure is within capacity"
        );
        assert_eq!(block, expected, "original codeword recovered");
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn erasures_do_not_help_beyond_the_singleton_bound() {
        // Two unknown errors (cost 4) plus two erasures (cost 2) sum to 6 > 5.
        let expected = codeword(&[142, 164, 186], 5);
        let mut block = expected.clone();
        block[0] ^= 0x11; // unknown error
        block[3] ^= 0x22; // unknown error
        block[6] ^= 0x44; // known erasure
        block[7] ^= 0x88; // known erasure
        assert!(
            !correct_with_erasures(&mut block, 5, &[6, 7]),
            "2·2 + 2 > 5 is beyond the code's reach"
        );
    }

    #[test]
    #[tracing::instrument(skip_all)]
    fn empty_erasures_match_the_blind_corrector() {
        // The erasure entry point with no erasures is exactly `correct`.
        let expected = codeword(&[142, 164, 186], 5);
        let mut block = expected.clone();
        block[0] ^= 0x3f;
        block[6] ^= 0xa1;
        assert!(correct_with_erasures(&mut block, 5, &[]));
        assert_eq!(block, expected);
    }
}
