// Pure helpers for turning the AssemblyScript compiler output into a single,
// self-contained ES module. Kept free of Node/`asc` imports so they can be
// unit-tested in isolation.

/**
 * The AssemblyScript ESM bindings file auto-instantiates from a `.wasm` URL via
 * a trailing `export const { … } = await instantiate(…)`. We keep only the
 * `instantiate(module, imports)` function so the generated module can drive
 * instantiation from an inlined (base64) binary instead of a URL.
 */
export function extractInstantiate(bindingsSource: string): string {
  const marker = 'export const {';
  const markerIndex = bindingsSource.indexOf(marker);
  if (markerIndex === -1) {
    throw new Error('Unexpected AssemblyScript bindings output: instantiation marker not found.');
  }
  return bindingsSource.slice(0, markerIndex).trim();
}

/**
 * Derive a synchronous `instantiateSync` from the async `instantiate` source.
 *
 * The AssemblyScript ESM bindings' `instantiate` is asynchronous solely because
 * of a single `await WebAssembly.instantiate(module, imports)` — every other
 * statement (export adaptation, the lift/lower helpers) is synchronous. Swapping
 * that one call for the synchronous `new WebAssembly.Instance(module, imports)`
 * (which likewise exposes `.exports`) yields an equivalent synchronous factory.
 */
export function deriveSyncInstantiate(instantiateSource: string): string {
  const awaitMarker = 'await WebAssembly.instantiate(';
  if (!instantiateSource.includes('async function instantiate(') || !instantiateSource.includes(awaitMarker)) {
    throw new Error('Unexpected AssemblyScript bindings output: cannot derive a synchronous instantiate.');
  }
  return instantiateSource
    .replace('async function instantiate(', 'function instantiateSync(')
    .replace(awaitMarker, 'new WebAssembly.Instance(');
}

/**
 * Build the self-contained generated module: the wasm binary inlined as base64,
 * a cross-environment base64 decoder, the extracted `instantiate` function
 * (plus a derived synchronous variant) and memoised `loadModule()` /
 * `loadModuleSync()` factories returning the raw wasm exports.
 */
export function buildGeneratedModule(wasmBase64: string, instantiateSource: string): string {
  const syncInstantiateSource = deriveSyncInstantiate(instantiateSource);
  return `// @generated by @mission-platform/vite-plugin-assemblyscript — do not edit by hand.
/* eslint-disable */
// prettier-ignore
const WASM_BASE64 = ${JSON.stringify(wasmBase64)};

function decodeBase64(value) {
  if (typeof Buffer !== 'undefined') {
    return new Uint8Array(Buffer.from(value, 'base64'));
  }
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let i = 0; i < binary.length; i++) {
    bytes[i] = binary.charCodeAt(i);
  }
  return bytes;
}

export ${instantiateSource}

${syncInstantiateSource}

let modulePromise = null;

/**
 * Instantiate the WebAssembly module (memoised) and return its raw exports.
 */
export async function loadModule() {
  if (modulePromise === null) {
    const compiled = await WebAssembly.compile(decodeBase64(WASM_BASE64));
    modulePromise = instantiate(compiled, {});
  }
  return modulePromise;
}

let syncExports = null;

/**
 * Synchronously instantiate the WebAssembly module (memoised) and return its
 * raw exports. Useful where an async boundary is impractical (e.g. rendering).
 */
export function loadModuleSync() {
  if (syncExports === null) {
    const compiled = new WebAssembly.Module(decodeBase64(WASM_BASE64));
    syncExports = instantiateSync(compiled, {});
  }
  return syncExports;
}
`;
}
