/**
 * Generate `public/robots.txt` and `public/sitemap.xml` for My Care Notes
 * using the deterministic builders from `@mission-platform/seo`.
 *
 * Run automatically before `build` via the `prebuild` script in `package.json`
 * so each production bundle ships fresh crawler-facing companion files.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRobotsTxt, buildSitemapXml, type SitemapUrl } from '@mission-platform/seo';

import { APP_LOCALE_BCP47, APP_ORIGIN } from '../src/seo-app.ts';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.resolve(HERE, '..', 'public');

const ROOT_URL = APP_ORIGIN.endsWith('/') ? APP_ORIGIN : `${APP_ORIGIN}/`;
const SITEMAP_URL = `${ROOT_URL}sitemap.xml`;

// Single-route SPA: just advertise the root URL with its locale alternate.
const urls: SitemapUrl[] = [
  {
    loc: ROOT_URL,
    changefreq: 'weekly',
    priority: 1,
    alternates: [
      { hreflang: APP_LOCALE_BCP47, href: ROOT_URL },
      { hreflang: 'x-default', href: ROOT_URL },
    ],
  },
];

const sitemap = buildSitemapXml({ urls });

const robots = buildRobotsTxt({
  comments: ['My Care Notes', `Generated by @mission-platform/seo at ${new Date().toISOString()}`],
  groups: [{ userAgent: '*', allow: ['/'] }],
  sitemaps: [SITEMAP_URL],
  host: new URL(ROOT_URL).host,
});

mkdirSync(PUBLIC_DIR, { recursive: true });
writeFileSync(path.resolve(PUBLIC_DIR, 'sitemap.xml'), sitemap, 'utf8');
writeFileSync(path.resolve(PUBLIC_DIR, 'robots.txt'), robots, 'utf8');

process.stdout.write(`[seo] wrote ${PUBLIC_DIR}/robots.txt and sitemap.xml (${urls.length} URLs)\n`);
