// ─── @mission-platform/icons ───────────────────────────────────────────────
// Icon component library for Mission Platform, authored once in JSX.
//
// Each icon is a framework-neutral JSX component that compiles to both Vue 3 and
// React via the vite-plugin-forge two-stage compiler.
//
// Usage:
//   import { ForgeIconAlert } from '@mission-platform/icons/vue';
//   import { ForgeIconAlert } from '@mission-platform/icons/react';
//
// This file is generated by scripts/generate-icons.js — do not edit by hand.

export { ForgeIconAlert, type IconAlertProperties } from './atoms/forge-icon-alert';
export { ForgeIconAlertCritical, type IconAlertCriticalProperties } from './atoms/forge-icon-alert-critical';
export { ForgeIconAlertInfo, type IconAlertInfoProperties } from './atoms/forge-icon-alert-info';
export { ForgeIconAlertNeutral, type IconAlertNeutralProperties } from './atoms/forge-icon-alert-neutral';
export { ForgeIconAlertWarning, type IconAlertWarningProperties } from './atoms/forge-icon-alert-warning';
export { ForgeIconAlignCenter, type IconAlignCenterProperties } from './atoms/forge-icon-align-center';
export { ForgeIconAlignJustify, type IconAlignJustifyProperties } from './atoms/forge-icon-align-justify';
export { ForgeIconAlignLeft, type IconAlignLeftProperties } from './atoms/forge-icon-align-left';
export { ForgeIconAlignRight, type IconAlignRightProperties } from './atoms/forge-icon-align-right';
export { ForgeIconArrow, type IconArrowProperties, type IconArrowDirection } from './atoms/forge-icon-arrow';
export { ForgeIconBell, type IconBellProperties } from './atoms/forge-icon-bell';
export { ForgeIconBlockquote, type IconBlockquoteProperties } from './atoms/forge-icon-blockquote';
export { ForgeIconBold, type IconBoldProperties } from './atoms/forge-icon-bold';
export { ForgeIconBulletList, type IconBulletListProperties } from './atoms/forge-icon-bullet-list';
export { ForgeIconCalendar, type IconCalendarProperties } from './atoms/forge-icon-calendar';
export { ForgeIconCamera, type IconCameraProperties } from './atoms/forge-icon-camera';
export { ForgeIconChat, type IconChatProperties } from './atoms/forge-icon-chat';
export { ForgeIconCheck, type IconCheckProperties } from './atoms/forge-icon-check';
export { ForgeIconChevron, type IconChevronProperties, type IconDirection } from './atoms/forge-icon-chevron';
export {
  ForgeIconChevrons,
  type IconChevronsProperties,
  type IconChevronsDirection,
} from './atoms/forge-icon-chevrons';
export { ForgeIconClock, type IconClockProperties } from './atoms/forge-icon-clock';
export { ForgeIconClose, type IconCloseProperties } from './atoms/forge-icon-close';
export { ForgeIconCloud, type IconCloudProperties } from './atoms/forge-icon-cloud';
export { ForgeIconCodeBlock, type IconCodeBlockProperties } from './atoms/forge-icon-code-block';
export { ForgeIconCodeInline, type IconCodeInlineProperties } from './atoms/forge-icon-code-inline';
export { ForgeIconCopy, type IconCopyProperties } from './atoms/forge-icon-copy';
export { ForgeIconDebug, type IconDebugProperties } from './atoms/forge-icon-debug';
export { ForgeIconDownload, type IconDownloadProperties } from './atoms/forge-icon-download';
export { ForgeIconDrawCircle, type IconDrawCircleProperties } from './atoms/forge-icon-draw-circle';
export { ForgeIconDrawLine, type IconDrawLineProperties } from './atoms/forge-icon-draw-line';
export { ForgeIconDrawPolygon, type IconDrawPolygonProperties } from './atoms/forge-icon-draw-polygon';
export { ForgeIconDrawSquare, type IconDrawSquareProperties } from './atoms/forge-icon-draw-square';
export { ForgeIconDrawTriangle, type IconDrawTriangleProperties } from './atoms/forge-icon-draw-triangle';
export { ForgeIconEdit, type IconEditProperties } from './atoms/forge-icon-edit';
export { ForgeIconError, type IconErrorProperties } from './atoms/forge-icon-error';
export { ForgeIconExternalLink, type IconExternalLinkProperties } from './atoms/forge-icon-external-link';
export { ForgeIconEye, type IconEyeProperties } from './atoms/forge-icon-eye';
export { ForgeIconEyeOff, type IconEyeOffProperties } from './atoms/forge-icon-eye-off';
export { ForgeIconFilter, type IconFilterProperties } from './atoms/forge-icon-filter';
export { ForgeIconGeodesic, type IconGeodesicProperties } from './atoms/forge-icon-geodesic';
export { ForgeIconGlobe, type IconGlobeProperties } from './atoms/forge-icon-globe';
export { ForgeIconHeading, type IconHeadingProperties } from './atoms/forge-icon-heading';
export { ForgeIconHeadingFive, type IconHeadingFiveProperties } from './atoms/forge-icon-heading-five';
export { ForgeIconHeadingFour, type IconHeadingFourProperties } from './atoms/forge-icon-heading-four';
export { ForgeIconHeadingOne, type IconHeadingOneProperties } from './atoms/forge-icon-heading-one';
export { ForgeIconHeadingSix, type IconHeadingSixProperties } from './atoms/forge-icon-heading-six';
export { ForgeIconHeadingThree, type IconHeadingThreeProperties } from './atoms/forge-icon-heading-three';
export { ForgeIconHeadingTwo, type IconHeadingTwoProperties } from './atoms/forge-icon-heading-two';
export { ForgeIconHeart, type IconHeartProperties } from './atoms/forge-icon-heart';
export { ForgeIconHome, type IconHomeProperties } from './atoms/forge-icon-home';
export { ForgeIconImage, type IconImageProperties } from './atoms/forge-icon-image';
export { ForgeIconInfo, type IconInfoProperties } from './atoms/forge-icon-info';
export { ForgeIconItalic, type IconItalicProperties } from './atoms/forge-icon-italic';
export { ForgeIconJoin, type IconJoinProperties } from './atoms/forge-icon-join';
export { ForgeIconLanguage, type IconLanguageProperties } from './atoms/forge-icon-language';
export { ForgeIconLightning, type IconLightningProperties } from './atoms/forge-icon-lightning';
export { ForgeIconLink, type IconLinkProperties } from './atoms/forge-icon-link';
export { ForgeIconLock, type IconLockProperties } from './atoms/forge-icon-lock';
export { ForgeIconLockOpen, type IconLockOpenProperties } from './atoms/forge-icon-lock-open';
export { ForgeIconMail, type IconMailProperties } from './atoms/forge-icon-mail';
export { ForgeIconMapPin, type IconMapPinProperties } from './atoms/forge-icon-map-pin';
export { ForgeIconMenu, type IconMenuProperties } from './atoms/forge-icon-menu';
export { ForgeIconMinus, type IconMinusProperties } from './atoms/forge-icon-minus';
export { ForgeIconMove, type IconMoveProperties } from './atoms/forge-icon-move';
export { ForgeIconNotice, type IconNoticeProperties } from './atoms/forge-icon-notice';
export { ForgeIconNumberedList, type IconNumberedListProperties } from './atoms/forge-icon-numbered-list';
export { ForgeIconPalette, type IconPaletteProperties } from './atoms/forge-icon-palette';
export { ForgeIconPause, type IconPauseProperties } from './atoms/forge-icon-pause';
export { ForgeIconPencil, type IconPencilProperties } from './atoms/forge-icon-pencil';
export { ForgeIconPhone, type IconPhoneProperties } from './atoms/forge-icon-phone';
export { ForgeIconPlay, type IconPlayProperties } from './atoms/forge-icon-play';
export { ForgeIconPlus, type IconPlusProperties } from './atoms/forge-icon-plus';
export { ForgeIconPuzzle, type IconPuzzleProperties } from './atoms/forge-icon-puzzle';
export { ForgeIconQrCode, type IconQrCodeProperties } from './atoms/forge-icon-qr-code';
export { ForgeIconRefresh, type IconRefreshProperties } from './atoms/forge-icon-refresh';
export { ForgeIconRotateCcw, type IconRotateCcwProperties } from './atoms/forge-icon-rotate-ccw';
export { ForgeIconRotateCw, type IconRotateCwProperties } from './atoms/forge-icon-rotate-cw';
export { ForgeIconScaleDown, type IconScaleDownProperties } from './atoms/forge-icon-scale-down';
export { ForgeIconScaleUp, type IconScaleUpProperties } from './atoms/forge-icon-scale-up';
export { ForgeIconSearch, type IconSearchProperties } from './atoms/forge-icon-search';
export { ForgeIconSend, type IconSendProperties } from './atoms/forge-icon-send';
export { ForgeIconSettings, type IconSettingsProperties } from './atoms/forge-icon-settings';
export { ForgeIconShare, type IconShareProperties } from './atoms/forge-icon-share';
export { ForgeIconSort, type IconSortProperties, type SortDirection } from './atoms/forge-icon-sort';
export { ForgeIconSplit, type IconSplitProperties } from './atoms/forge-icon-split';
export { ForgeIconStar, type IconStarProperties } from './atoms/forge-icon-star';
export { ForgeIconStrikethrough, type IconStrikethroughProperties } from './atoms/forge-icon-strikethrough';
export { ForgeIconTable, type IconTableProperties } from './atoms/forge-icon-table';
export { ForgeIconTableColumnAdd, type IconTableColumnAddProperties } from './atoms/forge-icon-table-column-add';
export {
  ForgeIconTableColumnRemove,
  type IconTableColumnRemoveProperties,
} from './atoms/forge-icon-table-column-remove';
export { ForgeIconTableRowAdd, type IconTableRowAddProperties } from './atoms/forge-icon-table-row-add';
export { ForgeIconTableRowRemove, type IconTableRowRemoveProperties } from './atoms/forge-icon-table-row-remove';
export { ForgeIconTrash, type IconTrashProperties } from './atoms/forge-icon-trash';
export { ForgeIconUnderline, type IconUnderlineProperties } from './atoms/forge-icon-underline';
export { ForgeIconUpload, type IconUploadProperties } from './atoms/forge-icon-upload';
export { ForgeIconUser, type IconUserProperties } from './atoms/forge-icon-user';
export { ForgeIconWarning, type IconWarningProperties } from './atoms/forge-icon-warning';
export { ForgeIconWrench, type IconWrenchProperties } from './atoms/forge-icon-wrench';
