// ─── @mission-platform/icons ───────────────────────────────────────────────
// Icon component library for Mission Platform, authored once in JSX.
//
// Each icon is a framework-neutral JSX component that compiles to both Vue 3 and
// React via the vite-plugin-jsx two-stage compiler.
//
// Usage:
//   import { IconAlert } from '@mission-platform/icons/vue';
//   import { IconAlert } from '@mission-platform/icons/react';
//
// This file is generated by scripts/generate-icons.js — do not edit by hand.

export { IconAlert, type IconAlertProperties } from './icon-alert';
export { IconAlertCritical, type IconAlertCriticalProperties } from './icon-alert-critical';
export { IconAlertInfo, type IconAlertInfoProperties } from './icon-alert-info';
export { IconAlertNeutral, type IconAlertNeutralProperties } from './icon-alert-neutral';
export { IconAlertWarning, type IconAlertWarningProperties } from './icon-alert-warning';
export { IconAlignCenter, type IconAlignCenterProperties } from './icon-align-center';
export { IconAlignJustify, type IconAlignJustifyProperties } from './icon-align-justify';
export { IconAlignLeft, type IconAlignLeftProperties } from './icon-align-left';
export { IconAlignRight, type IconAlignRightProperties } from './icon-align-right';
export { IconArrow, type IconArrowProperties, type IconArrowDirection } from './icon-arrow';
export { IconBell, type IconBellProperties } from './icon-bell';
export { IconBlockquote, type IconBlockquoteProperties } from './icon-blockquote';
export { IconBold, type IconBoldProperties } from './icon-bold';
export { IconBulletList, type IconBulletListProperties } from './icon-bullet-list';
export { IconCalendar, type IconCalendarProperties } from './icon-calendar';
export { IconCamera, type IconCameraProperties } from './icon-camera';
export { IconChat, type IconChatProperties } from './icon-chat';
export { IconCheck, type IconCheckProperties } from './icon-check';
export { IconChevron, type IconChevronProperties, type IconDirection } from './icon-chevron';
export { IconChevrons, type IconChevronsProperties, type IconChevronsDirection } from './icon-chevrons';
export { IconClock, type IconClockProperties } from './icon-clock';
export { IconClose, type IconCloseProperties } from './icon-close';
export { IconCloud, type IconCloudProperties } from './icon-cloud';
export { IconCodeBlock, type IconCodeBlockProperties } from './icon-code-block';
export { IconCodeInline, type IconCodeInlineProperties } from './icon-code-inline';
export { IconCopy, type IconCopyProperties } from './icon-copy';
export { IconDebug, type IconDebugProperties } from './icon-debug';
export { IconDownload, type IconDownloadProperties } from './icon-download';
export { IconDrawCircle, type IconDrawCircleProperties } from './icon-draw-circle';
export { IconDrawLine, type IconDrawLineProperties } from './icon-draw-line';
export { IconDrawPolygon, type IconDrawPolygonProperties } from './icon-draw-polygon';
export { IconDrawSquare, type IconDrawSquareProperties } from './icon-draw-square';
export { IconDrawTriangle, type IconDrawTriangleProperties } from './icon-draw-triangle';
export { IconEdit, type IconEditProperties } from './icon-edit';
export { IconError, type IconErrorProperties } from './icon-error';
export { IconExternalLink, type IconExternalLinkProperties } from './icon-external-link';
export { IconEye, type IconEyeProperties } from './icon-eye';
export { IconEyeOff, type IconEyeOffProperties } from './icon-eye-off';
export { IconFilter, type IconFilterProperties } from './icon-filter';
export { IconGeodesic, type IconGeodesicProperties } from './icon-geodesic';
export { IconGlobe, type IconGlobeProperties } from './icon-globe';
export { IconHeading, type IconHeadingProperties } from './icon-heading';
export { IconHeadingFive, type IconHeadingFiveProperties } from './icon-heading-five';
export { IconHeadingFour, type IconHeadingFourProperties } from './icon-heading-four';
export { IconHeadingOne, type IconHeadingOneProperties } from './icon-heading-one';
export { IconHeadingSix, type IconHeadingSixProperties } from './icon-heading-six';
export { IconHeadingThree, type IconHeadingThreeProperties } from './icon-heading-three';
export { IconHeadingTwo, type IconHeadingTwoProperties } from './icon-heading-two';
export { IconHeart, type IconHeartProperties } from './icon-heart';
export { IconHome, type IconHomeProperties } from './icon-home';
export { IconImage, type IconImageProperties } from './icon-image';
export { IconInfo, type IconInfoProperties } from './icon-info';
export { IconItalic, type IconItalicProperties } from './icon-italic';
export { IconJoin, type IconJoinProperties } from './icon-join';
export { IconLanguage, type IconLanguageProperties } from './icon-language';
export { IconLightning, type IconLightningProperties } from './icon-lightning';
export { IconLink, type IconLinkProperties } from './icon-link';
export { IconLock, type IconLockProperties } from './icon-lock';
export { IconLockOpen, type IconLockOpenProperties } from './icon-lock-open';
export { IconMail, type IconMailProperties } from './icon-mail';
export { IconMapPin, type IconMapPinProperties } from './icon-map-pin';
export { IconMenu, type IconMenuProperties } from './icon-menu';
export { IconMinus, type IconMinusProperties } from './icon-minus';
export { IconMove, type IconMoveProperties } from './icon-move';
export { IconNotice, type IconNoticeProperties } from './icon-notice';
export { IconNumberedList, type IconNumberedListProperties } from './icon-numbered-list';
export { IconPalette, type IconPaletteProperties } from './icon-palette';
export { IconPause, type IconPauseProperties } from './icon-pause';
export { IconPencil, type IconPencilProperties } from './icon-pencil';
export { IconPhone, type IconPhoneProperties } from './icon-phone';
export { IconPlay, type IconPlayProperties } from './icon-play';
export { IconPlus, type IconPlusProperties } from './icon-plus';
export { IconPuzzle, type IconPuzzleProperties } from './icon-puzzle';
export { IconQrCode, type IconQrCodeProperties } from './icon-qr-code';
export { IconRefresh, type IconRefreshProperties } from './icon-refresh';
export { IconRotateCcw, type IconRotateCcwProperties } from './icon-rotate-ccw';
export { IconRotateCw, type IconRotateCwProperties } from './icon-rotate-cw';
export { IconScaleDown, type IconScaleDownProperties } from './icon-scale-down';
export { IconScaleUp, type IconScaleUpProperties } from './icon-scale-up';
export { IconSearch, type IconSearchProperties } from './icon-search';
export { IconSend, type IconSendProperties } from './icon-send';
export { IconSettings, type IconSettingsProperties } from './icon-settings';
export { IconShare, type IconShareProperties } from './icon-share';
export { IconSort, type IconSortProperties, type SortDirection } from './icon-sort';
export { IconSplit, type IconSplitProperties } from './icon-split';
export { IconStar, type IconStarProperties } from './icon-star';
export { IconTable, type IconTableProperties } from './icon-table';
export { IconTableColumnAdd, type IconTableColumnAddProperties } from './icon-table-column-add';
export { IconTableColumnRemove, type IconTableColumnRemoveProperties } from './icon-table-column-remove';
export { IconTableRowAdd, type IconTableRowAddProperties } from './icon-table-row-add';
export { IconTableRowRemove, type IconTableRowRemoveProperties } from './icon-table-row-remove';
export { IconTrash, type IconTrashProperties } from './icon-trash';
export { IconUpload, type IconUploadProperties } from './icon-upload';
export { IconUser, type IconUserProperties } from './icon-user';
export { IconWarning, type IconWarningProperties } from './icon-warning';
export { IconWrench, type IconWrenchProperties } from './icon-wrench';
