// SCSS / CSS emitters. Each generated `scss/<file>.scss` is self-contained:
// structural sources (including the colour palette) emit their `$`-variables, the
// `:root { --mp-* }` custom properties, and the matching `@property` registrations
// (whose `initial-value` resolves to the local `$`-variable in the same file). The
// composite typography is flattened to per-field tokens and emitted through the
// same structural path (referencing the primitive `var(--mp-font-*)` tokens). The
// two theme sources are merged into a single `light-dark()` partial.

import {
  aliasToCssVariable,
  compareTokens,
  dashedName,
  type DtcgGroup,
  type DtcgToken,
  flattenTokens,
  formatCssValue,
  groupLabel,
  isAlias,
  type TokenRecord,
} from '../dtcg.js';

const SCSS_HEADER = `// Generated by @mission-platform/vite-plugin-tokens from the DTCG sources in tokens/.
// Do not edit manually — edit tokens/*.tokens.json.`;

const CSS_HEADER = `/* Generated by @mission-platform/vite-plugin-tokens from the DTCG sources in tokens/. */
/* Do not edit manually — edit tokens/*.tokens.json. */`;

/**
 * Build a CSS-free `$`-variables-only partial (header + the {@link buildScssVariables}
 * body, no `:root`/`@property` CSS). Emitted as `scss/_<file>-vars.scss` so internal
 * consumers (e.g. `scss/_mixins.scss`) can read a token's `$`-value at compile time
 * without `@use`-ing the full partial — which would leak its `:root`/`@property` CSS
 * into every consuming stylesheet.
 */
export function buildScssVariablesScss(
  records: TokenRecord[],
  prefix = 'mp',
  cssNamespace?: string,
  componentNamespaces?: ReadonlySet<string>,
): string {
  return `${SCSS_HEADER}\n\n${buildScssVariables(records, prefix, cssNamespace, componentNamespaces)}\n`;
}

/**
 * Build the body (no header) of unprefixed `$`-variables, grouped by their
 * top-level DTCG group (`// Border Width`, `// Color`, …) and sorted by dashed
 * name. Each variable is preceded by a `///` doc comment when described.
 */
function projectedName(record: TokenRecord, cssNamespace?: string): string {
  return cssNamespace && record.path[0] === 'component'
    ? [cssNamespace, ...record.path.slice(2)].join('-')
    : dashedName(record);
}

function projectedAlias(alias: string, prefix: string, componentNamespaces?: ReadonlySet<string>): string {
  if (!isAlias(alias)) return alias;
  const segments = alias.slice(1, -1).split('.');
  if (segments[0] === 'component' && segments[1] && componentNamespaces?.has(segments[1])) {
    return aliasToCssVariable(`{${[segments[1], ...segments.slice(2)].join('.')}}`, prefix);
  }
  return aliasToCssVariable(alias, prefix);
}

export function buildScssVariables(
  records: TokenRecord[],
  prefix = 'mp',
  cssNamespace?: string,
  componentNamespaces?: ReadonlySet<string>,
): string {
  const groups = new Map<string, TokenRecord[]>();
  for (const record of records) {
    const list = groups.get(record.group) ?? [];
    list.push(record);
    groups.set(record.group, list);
  }
  const sections = [...groups.keys()].toSorted().map((key) => {
    const lines = (groups.get(key) ?? [])
      .toSorted((a, b) => projectedName(a, cssNamespace).localeCompare(projectedName(b, cssNamespace)))
      .flatMap((record) => {
        const value = isAlias(record.value)
          ? projectedAlias(record.value, prefix, componentNamespaces)
          : formatCssValue(record.value);
        const declaration = `$${projectedName(record, cssNamespace)}: ${value};`;
        return record.description ? [`/// ${record.description}`, declaration] : [declaration];
      });
    return `// ${groupLabel(key)}\n${lines.join('\n')}`;
  });
  return sections.join('\n\n');
}

/**
 * Token `$type` → CSS `@property` `syntax` descriptor. The keys cover both the
 * DTCG type names actually used by the sources and the broader set of CSS value
 * data types that a registered custom property can declare
 * (https://developer.mozilla.org/en-US/docs/Web/CSS/Reference/Values/Data_types),
 * so a token authored with any of them gets a typed registration. Only types
 * whose values are computationally-independent literals are mapped; everything
 * else (the synthetic `typography` `var()` references, plus `shadow`/`cubicBezier`
 * easing/font-family stacks, which have no single valid `@property` syntax) falls
 * back to the universal `'*'` syntax with no `initial-value` (see
 * {@link buildPropertyRule}).
 */
const PROPERTY_SYNTAX_BY_TYPE: Record<string, string> = {
  // DTCG types used by the sources.
  color: '<color>',
  dimension: '<length>',
  number: '<number>',
  fontWeight: '<number>',
  duration: '<time>',
  // Additional CSS `@property`-supported data types (forward-looking).
  angle: '<angle>',
  integer: '<integer>',
  length: '<length>',
  lengthPercentage: '<length-percentage>',
  'length-percentage': '<length-percentage>',
  percentage: '<percentage>',
  resolution: '<resolution>',
  time: '<time>',
  url: '<url>',
  image: '<image>',
  transform: '<transform-list>',
  transformList: '<transform-list>',
  'transform-list': '<transform-list>',
  transformFunction: '<transform-function>',
  'transform-function': '<transform-function>',
};

/** Syntaxes that omit the `initial-value` descriptor (see {@link buildPropertyRule}). */
const SYNTAXES_WITHOUT_INITIAL_VALUE = new Set(['*']);

/**
 * Build the CSS `@property` registration for a single custom property.
 *
 * When `useScssVariable` is set the `initial-value` resolves to the matching
 * local `$`-variable (`$<token>`) emitted in the same file, keeping the
 * registration in sync with the `$`-variable source of truth; otherwise the
 * literal `$value` is inlined.
 *
 * A non-universal `@property` requires a computationally-independent
 * `initial-value` (no `var()`, `light-dark()` or relative units), so the
 * universal `*` syntax omits it. Everything whose value is a `var()` reference
 * (the typography fields) or a non-typeable literal (shadows, easing curves,
 * font-family stacks) therefore registers under `*` without an `initial-value`.
 */
export function buildPropertyRule(
  record: TokenRecord,
  prefix: string,
  useScssVariable = false,
  cssNamespace?: string,
): string {
  const tokenName = projectedName(record, cssNamespace);
  const name = `--${prefix}-${tokenName}`;
  // Aliases are emitted as `var()` references in SCSS. CSS custom-property
  // registrations cannot use those references as computationally-independent
  // typed initial values, so register aliased values with the universal syntax.
  const syntax = isAlias(record.value) ? '*' : (PROPERTY_SYNTAX_BY_TYPE[record.type ?? ''] ?? '*');
  const lines = [`@property ${name} {`, `  syntax: '${syntax}';`, '  inherits: true;'];
  if (!SYNTAXES_WITHOUT_INITIAL_VALUE.has(syntax)) {
    const initialValue = useScssVariable ? `vars.$${tokenName}` : formatCssValue(record.value);
    lines.push(`  initial-value: ${initialValue};`);
  }
  lines.push('}');
  return lines.join('\n');
}

/**
 * Build the sorted `--<prefix>-*: #{$<token>};` declaration lines for the
 * `:root` block. The value interpolates the matching local `$`-variable (the
 * single source of truth in the same partial) rather than inlining the literal,
 * so the custom property and the `$`-variable always stay in sync. Interpolation
 * (`#{…}`) is required: a bare `$<token>` inside a custom-property value is *not*
 * evaluated by Sass and would emit the literal text `$<token>`.
 */
function customPropertyDeclarations(records: TokenRecord[], prefix: string, cssNamespace?: string): string[] {
  return records.toSorted(compareTokens).flatMap((record) => {
    const name = projectedName(record, cssNamespace);
    const declaration = `  --${prefix}-${name}: #{vars.$${name}};`;
    return record.description ? [`  /* ${record.description} */`, declaration] : [declaration];
  });
}

/**
 * Build a structural SCSS partial: the `:root { --<prefix>-* }` custom properties
 * and a matching `@property` registration for every token (with `initial-value`s
 * resolved to the matching `$`-variable), both wrapped in the `mp.tokens` cascade
 * layer. The `$`-variables themselves live in the companion CSS-free
 * `_<file>-vars.scss` partial (see {@link buildScssVariablesScss}); this partial
 * `@use`s it (to interpolate the values into the `:root`/`@property` blocks) and
 * `@forward`s it (so downstream consumers of `_<file>.scss` still see the
 * `$`-variables). The colour palette and the composite typography are both emitted
 * through this path.
 *
 * `file` is the source/output base name (e.g. `'radius'`), used to reference the
 * companion `'<file>-vars'` partial.
 */
export function buildStructuralScss(records: TokenRecord[], prefix = 'mp', file = '', cssNamespace?: string): string {
  const declarations = customPropertyDeclarations(records, prefix, cssNamespace).map((line) => `  ${line}`);
  const root = `  :root {\n${declarations.join('\n')}\n  }`;
  const propertyRules = records
    .toSorted(compareTokens)
    .map((record) =>
      buildPropertyRule(record, prefix, true, cssNamespace)
        .split('\n')
        .map((line) => `  ${line}`)
        .join('\n'),
    )
    .join('\n\n');
  // Both the `@property` registrations and the `:root` custom properties live in
  // the `mp.tokens` cascade layer so unlayered application styles win over them.
  // The `@property` rules are emitted first so the properties are registered
  // before the `:root` block assigns their values.
  const layer = `@layer mp.tokens {\n${propertyRules}\n\n${root}\n}`;
  // `@forward` re-exports the `$`-variables for downstream consumers; `@use … as
  // vars` brings them into scope (under the `vars` namespace) so the `:root`/
  // `@property` blocks can interpolate them (`vars.$<token>`).
  const dependencies = `@forward '${file}-vars';\n@use '${file}-vars' as vars;`;
  return `${SCSS_HEADER}\n\n${dependencies}\n\n${layer}\n`;
}

/**
 * Build the single combined theme partial. The light and dark semantic colour
 * sources (whose `$value`s are palette aliases) are merged into one
 * `:root { color-scheme: light dark; --<prefix>-color-*: light-dark(<light>, <dark>); }`
 * block where each light/dark value is a `var(--<prefix>-*)` reference to the
 * matching palette custom property. No `@property` registrations are emitted —
 * `light-dark()`/`var()` are not computationally-independent `initial-value`s.
 *
 * The partial also emits the opt-in `[data-theme]`/`.theme-*` scheme pins
 * directly, so importing `scss/tokens` is enough to pin a subtree (or the whole
 * document) to one scheme — no separate `scss/themes/{light,dark}` import is
 * required and the behaviour no longer depends on import order. Because the
 * `light-dark()` colour tokens above resolve against the *used* `color-scheme`,
 * setting it on a `[data-theme]` element re-themes that element and all its
 * descendants without redefining a single colour custom property.
 */
export function buildLightDarkThemeScss(lightDocument: DtcgGroup, darkDocument: DtcgGroup, prefix = 'mp'): string {
  const lightRecords = flattenTokens(lightDocument).toSorted(compareTokens);
  const darkByName = new Map(flattenTokens(darkDocument).map((record) => [dashedName(record), record.value]));
  const declarations = lightRecords.map((record) => {
    const name = dashedName(record);
    const lightReference = aliasToCssVariable(String(record.value), prefix);
    const darkValue = darkByName.get(name);
    const darkReference = darkValue === undefined ? lightReference : aliasToCssVariable(String(darkValue), prefix);
    return `  --${prefix}-${name}: light-dark(${lightReference}, ${darkReference});`;
  });
  const indented = declarations.map((line) => `  ${line}`);
  const root = `  :root {\n    color-scheme: light dark;\n${indented.join('\n')}\n  }`;
  // Opt-in scheme pinning — force one scheme on a subtree (or the document) by
  // adding `data-theme="light|dark"` (or the `.theme-light`/`.theme-dark`
  // classes). The `light-dark()` colour tokens resolve against this used
  // `color-scheme`, so no colour custom property has to be redeclared.
  const lightPin = "  [data-theme='light'],\n  .theme-light {\n    color-scheme: light;\n  }";
  const darkPin = "  [data-theme='dark'],\n  .theme-dark {\n    color-scheme: dark;\n  }";
  const block = `@layer mp.tokens {\n${root}\n\n${lightPin}\n\n${darkPin}\n}`;
  return `${CSS_HEADER}\n\n${block}\n`;
}

// ─── Composite typography expansion ─────────────────────────────────────────────
// Composite `typography` tokens are flattened here into per-field tokens — one
// `typography-<variant>-<field>` token per `fontFamily`/`fontSize`/… field — whose
// value is a `var(--<prefix>-*)` reference to the matching primitive token. The
// resulting records are emitted through the structural path (`buildStructuralScss`),
// so typography is handled exactly like any other structural source.

/** DTCG composite typography value: a map of style fields to alias references. */
type TypographyValue = Record<string, string>;

/** Ordered map of DTCG composite typography fields to the generated CSS declaration name. */
const TYPOGRAPHY_CSS_FIELDS: ReadonlyArray<{ dtcg: string; css: string }> = [
  { dtcg: 'fontFamily', css: 'font-family' },
  { dtcg: 'fontSize', css: 'font-size' },
  { dtcg: 'fontWeight', css: 'font-weight' },
  { dtcg: 'lineHeight', css: 'line-height' },
  { dtcg: 'letterSpacing', css: 'letter-spacing' },
  { dtcg: 'marginBlock', css: 'margin-block' },
  { dtcg: 'marginInline', css: 'margin-inline' },
];

/** Return `[variant, value]` entries for a DTCG composite typography group. */
export function typographyEntries(group: DtcgGroup): Array<[string, TypographyValue]> {
  return Object.entries(group)
    .filter(
      (entry): entry is [string, DtcgToken] =>
        !entry[0].startsWith('$') && (entry[1] as DtcgToken)?.$value !== undefined,
    )
    .map(([variant, token]) => [variant, token.$value as TypographyValue]);
}

/**
 * Flatten a DTCG composite typography group into per-field {@link TokenRecord}s.
 * Each field becomes a `typography-<variant>-<field>` token whose value is the
 * `var(--<prefix>-*)` reference to the matching primitive (e.g.
 * `typography-h1-font-size` → `var(--mp-font-size-4xl)`). The synthetic
 * `typography` `$type` is unmapped, so every field registers under the universal
 * `*` `@property` syntax (a `var()` reference cannot carry a typed
 * `initial-value`). The records feed {@link buildStructuralScss}.
 */
export function buildTypographyRecords(typographyGroup: DtcgGroup, prefix = 'mp'): TokenRecord[] {
  return typographyEntries(typographyGroup).flatMap(([variant, value]) =>
    TYPOGRAPHY_CSS_FIELDS.filter((field) => isAlias(value[field.dtcg])).map((field) => ({
      path: ['typography', variant, field.css],
      group: 'typography',
      type: 'typography',
      value: aliasToCssVariable(value[field.dtcg], prefix),
    })),
  );
}
