import { describe, expect, it } from 'vitest';

import { flattenTokens } from '../dtcg.js';

import {
  buildLightDarkThemeScss,
  buildPropertyRule,
  buildScssVariables,
  buildScssVariablesScss,
  buildStructuralScss,
  buildTypographyRecords,
  typographyEntries,
} from './scss.js';

describe('buildScssVariables', () => {
  const records = flattenTokens({
    'border-width': { $type: 'dimension', thin: { $value: '1px', $description: 'hairline' } },
    color: { $type: 'color', white: { $value: { colorSpace: 'oklab', components: [1, 0, 0] } } },
  });
  const scss = buildScssVariables(records);

  it('groups by title-cased group key with `///` doc comments and unprefixed `$` names', () => {
    expect(scss).toContain('// Border Width');
    expect(scss).toContain('/// hairline');
    expect(scss).toContain('$border-width-thin: 1px;');
    expect(scss).toContain('$color-white: oklab(1 0 0);');
  });

  it('orders the groups by ASCII group key and omits any file header', () => {
    expect(scss.indexOf('// Border Width')).toBeLessThan(scss.indexOf('// Color'));
    expect(scss).not.toContain('Generated by');
  });
});

describe('buildScssVariablesScss', () => {
  const records = flattenTokens({
    font: { size: { $type: 'dimension', base: { $value: '14px', $description: 'root' } } },
  });
  const scss = buildScssVariablesScss(records);

  it('emits the header + `$`-variables only, with no `:root`/`@property`/`@layer` CSS', () => {
    expect(scss.startsWith('// Generated by')).toBe(true);
    expect(scss).toContain('$font-size-base: 14px;');
    expect(scss).not.toContain(':root');
    expect(scss).not.toContain('@property');
    expect(scss).not.toContain('@layer');
  });
});

describe('buildPropertyRule', () => {
  const radius = { path: ['radius', 'md'], group: 'radius', type: 'dimension', value: '0.429rem' };

  it('inlines the literal initial-value by default', () => {
    expect(buildPropertyRule(radius, 'mp')).toContain('initial-value: 0.429rem;');
  });

  it('resolves the initial-value to the local `$`-variable when requested', () => {
    expect(
      buildPropertyRule(
        { path: ['size', 'radius', '2xl'], group: 'size', type: 'dimension', value: '0.857rem' },
        'mp',
        true,
      ),
    ).toBe(
      [
        '@property --mp-size-radius-2xl {',
        "  syntax: '<length>';",
        '  inherits: true;',
        '  initial-value: vars.$size-radius-2xl;',
        '}',
      ].join('\n'),
    );
  });

  it('uses the universal `*` syntax without an initial-value for shadows', () => {
    const rule = buildPropertyRule(
      { path: ['shadow', 'md'], group: 'shadow', type: 'shadow', value: '0 1px 2px #000' },
      'mp',
      true,
    );
    expect(rule).toContain("syntax: '*';");
    expect(rule).not.toContain('initial-value');
  });

  it('maps the broader CSS data types to their `@property` syntax', () => {
    const cases: Array<[string, string]> = [
      ['angle', '<angle>'],
      ['integer', '<integer>'],
      ['percentage', '<percentage>'],
      ['resolution', '<resolution>'],
      ['time', '<time>'],
      ['url', '<url>'],
      ['image', '<image>'],
      ['transform', '<transform-list>'],
      ['length-percentage', '<length-percentage>'],
    ];
    for (const [type, syntax] of cases) {
      const rule = buildPropertyRule({ path: ['x'], group: 'x', type, value: '0' }, 'mp');
      expect(rule).toContain(`syntax: '${syntax}';`);
    }
  });

  it('uses the universal `*` syntax without an initial-value for var()-referencing typography fields', () => {
    const rule = buildPropertyRule(
      {
        path: ['typography', 'h1', 'font-size'],
        group: 'typography',
        type: 'typography',
        value: 'var(--mp-font-size-4xl)',
      },
      'mp',
    );
    expect(rule).toContain("syntax: '*';");
    expect(rule).not.toContain('initial-value');
  });

  it('uses the universal `*` syntax without an initial-value for aliased values', () => {
    const rule = buildPropertyRule(
      {
        path: ['component', 'button', 'background'],
        group: 'component',
        type: 'color',
        value: '{color.primary.default}',
      },
      'mp',
    );
    expect(rule).toContain("syntax: '*';");
    expect(rule).not.toContain('initial-value');
  });
});

describe('buildStructuralScss', () => {
  const records = flattenTokens({
    radius: { $type: 'dimension', md: { $value: '0.429rem', $description: 'default' } },
  });
  const scss = buildStructuralScss(records, 'mp', 'radius');

  it('forwards/uses the companion vars partial and emits `:root` + local-var `@property` rules', () => {
    expect(scss.startsWith('// Generated by')).toBe(true);
    // The `$`-variables are sourced from the companion `_<file>-vars.scss`, not inlined.
    expect(scss).toContain("@forward 'radius-vars';");
    expect(scss).toContain("@use 'radius-vars' as vars;");
    expect(scss).not.toContain('$radius-md: 0.429rem;');
    expect(scss).toContain(':root {');
    expect(scss).toContain('--mp-radius-md: #{vars.$radius-md};');
    expect(scss).toContain('@property --mp-radius-md {');
    expect(scss).toContain('initial-value: vars.$radius-md;');
  });

  it('wraps both the `@property` registrations and the `:root` block in the `mp.tokens` layer (props first)', () => {
    // The `@property` registrations come first, indented inside the layer…
    expect(scss).toMatch(/@layer mp\.tokens \{\n {2}@property --mp-radius-md \{\n {4}syntax: '<length>';/);
    // …followed by the `:root` block, also inside the layer.
    expect(scss).toMatch(/\n {2}:root \{/);
    expect(scss.indexOf('@property --mp-radius-md {')).toBeLessThan(scss.indexOf(':root {'));
    // `@property` is never emitted at the top level (always inside the layer).
    expect(scss).not.toMatch(/^@property/m);
  });
});

describe('component alias SCSS emission', () => {
  it('converts DTCG aliases to prefixed CSS variables in the vars partial', () => {
    const records = flattenTokens({ component: { button: { background: { $value: '{color.primary.default}' } } } });
    expect(buildScssVariables(records, 'custom')).toContain(
      '$component-button-background: var(--custom-color-primary-default);',
    );
  });
});

describe('buildLightDarkThemeScss', () => {
  const light = { color: { $type: 'color', bg: { base: { $value: '{color.forge-light}' } } } };
  const dark = { color: { $type: 'color', bg: { base: { $value: '{color.cyan.950}' } } } };
  const scss = buildLightDarkThemeScss(light, dark, 'mp');

  it('emits a :root block with `color-scheme` and `light-dark()` values referencing palette vars', () => {
    expect(scss).toContain(':root {');
    expect(scss).toContain('color-scheme: light dark;');
    expect(scss).toContain('--mp-color-bg-base: light-dark(var(--mp-color-forge-light), var(--mp-color-cyan-950));');
  });

  it('wraps the theme `:root` block in the `mp.tokens` cascade layer', () => {
    expect(scss).toMatch(/@layer mp\.tokens \{\n {2}:root \{/);
  });

  it('emits no `@property` registrations (light-dark()/var() are not valid initial-values)', () => {
    expect(scss).not.toContain('@property');
  });

  it('emits the opt-in `[data-theme]`/`.theme-*` scheme pins inside the layer (so `scss/tokens` alone can pin a scheme)', () => {
    expect(scss).toContain("[data-theme='light'],");
    expect(scss).toContain('.theme-light {');
    expect(scss).toContain("[data-theme='dark'],");
    expect(scss).toContain('.theme-dark {');
    expect(scss).toContain('color-scheme: light;');
    expect(scss).toContain('color-scheme: dark;');
    // The pins come after the `:root` block and stay within the cascade layer.
    expect(scss.indexOf(':root {')).toBeLessThan(scss.indexOf("[data-theme='light']"));
    expect(scss.trimEnd().endsWith('}')).toBe(true);
  });
});

describe('buildTypographyRecords / typographyEntries', () => {
  const group = {
    h1: { $value: { fontFamily: '{font.family.sans}', fontSize: '{font.size.4xl}', fontWeight: '{font.weight.bold}' } },
  };

  it('flattens each aliased field into a `typography` token whose value is a `var(--mp-*)` reference', () => {
    const records = buildTypographyRecords(group, 'mp');
    const byName = Object.fromEntries(records.map((record) => [record.path.join('-'), record.value]));
    expect(byName['typography-h1-font-family']).toBe('var(--mp-font-family-sans)');
    expect(byName['typography-h1-font-size']).toBe('var(--mp-font-size-4xl)');
    expect(records.every((record) => record.type === 'typography')).toBe(true);
  });

  it('feeds the structural path: `var()` custom properties + a universal `*` `@property` without initial-value', () => {
    const scss = buildStructuralScss(buildTypographyRecords(group, 'mp'), 'mp', 'typography');
    expect(scss).toContain("@forward 'typography-vars';");
    expect(scss).toContain("@use 'typography-vars' as vars;");
    expect(scss).toContain('--mp-typography-h1-font-size: #{vars.$typography-h1-font-size};');
    expect(scss).toMatch(
      / {2}@property --mp-typography-h1-font-size \{\n {4}syntax: '\*';\n {4}inherits: true;\n {2}\}/,
    );
    expect(scss).not.toContain('initial-value');
  });

  it('returns `[variant, value]` entries', () => {
    expect(typographyEntries(group).map(([variant]) => variant)).toEqual(['h1']);
  });

  it('flattens the `marginBlock`/`marginInline` logical-margin fields to `var(--mp-spacing-*)` references', () => {
    const withMargins = {
      h1: {
        $value: {
          fontSize: '{font.size.4xl}',
          marginBlock: '{spacing.3}',
          marginInline: '{spacing.0}',
        },
      },
    };
    const byName = Object.fromEntries(
      buildTypographyRecords(withMargins, 'mp').map((record) => [record.path.join('-'), record.value]),
    );
    expect(byName['typography-h1-margin-block']).toBe('var(--mp-spacing-3)');
    expect(byName['typography-h1-margin-inline']).toBe('var(--mp-spacing-0)');
  });
});
