// TypeScript module emitters. Every `ts/<file>.ts` exports a single nested
// `as const` object mirroring its DTCG source (colours resolved to `oklab(...)`
// strings, aliases resolved to their literal primitive values). `tokens.ts` is a
// pure re-export barrel of those per-file modules.

import { camelCase, type DtcgGroup, formatColorValue, isAlias, isColorValue, isToken, resolveAlias } from '../dtcg.js';

const TS_HEADER = `// Generated by @mission-platform/vite-plugin-tokens from the DTCG sources in tokens/.
// Do not edit manually — edit tokens/*.tokens.json.`;

/** A resolved, JSON-serialisable token value tree. */
type ResolvedValue = string | number | boolean | ResolvedValue[] | { [key: string]: ResolvedValue };

/**
 * Resolve a DTCG `$value` to a literal JSON-serialisable value: colours become
 * their `oklab(...)` string, numbers stay numbers, aliases are followed against
 * `aliasDocument`, and composite objects/arrays are resolved field by field.
 */
function resolveValue(value: unknown, aliasDocument?: DtcgGroup): ResolvedValue {
  if (isColorValue(value)) return formatColorValue(value);
  if (typeof value === 'number' || typeof value === 'boolean') return value;
  if (typeof value === 'string') {
    if (isAlias(value) && aliasDocument) return resolveValue(resolveAlias(value, aliasDocument), aliasDocument);
    return value;
  }
  if (Array.isArray(value)) return value.map((entry) => resolveValue(entry, aliasDocument));
  if (typeof value === 'object' && value !== null) {
    const out: Record<string, ResolvedValue> = {};
    for (const [key, entry] of Object.entries(value)) out[key] = resolveValue(entry, aliasDocument);
    return out;
  }
  return String(value);
}

/** Recursively resolve a DTCG group into a nested object of literal values. */
function resolveNode(node: DtcgGroup, aliasDocument?: DtcgGroup): Record<string, ResolvedValue> {
  const out: Record<string, ResolvedValue> = {};
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    out[key] = isToken(child)
      ? resolveValue(child.$value, aliasDocument)
      : resolveNode(child as DtcgGroup, aliasDocument);
  }
  return out;
}

/**
 * Build a per-file TypeScript module exporting one nested `as const` object named
 * after the source file (camelCased). When the document has a single top-level
 * group whose key equals `basename`, that wrapper group is unwrapped so the export
 * mirrors the scale directly (e.g. `size.icon.md`); otherwise the full document is
 * preserved (e.g. `palette.color.*`, `font.font.*` / `font['line-height']`).
 *
 * Pass `aliasDocument` for sources whose `$value`s contain DTCG aliases (the
 * composite `typography` source resolves its `{font.*}` references against it).
 */
export function buildTokenModule(basename: string, document_: DtcgGroup, aliasDocument?: DtcgGroup): string {
  const exportName = camelCase(basename);
  const topGroups = Object.keys(document_).filter((key) => !key.startsWith('$'));
  const resolved = resolveNode(document_, aliasDocument);
  const value = topGroups.length === 1 && topGroups[0] === basename ? resolved[topGroups[0]] : resolved;
  return `${TS_HEADER}\n\nexport const ${exportName} = ${JSON.stringify(value, undefined, 2)} as const;\n`;
}

/** Build the `tokens.ts` barrel that re-exports every per-file module. */
export function buildBarrelModule(basenames: string[]): string {
  const lines = basenames.toSorted().map((basename) => `export * from './ts/${basename}.js';`);
  return `${TS_HEADER}\n\n${lines.join('\n')}\n`;
}
