/**
 * Extract public TypeScript and Forge Web Script declarations into package-owned
 * reference documentation.
 *
 * Usage:
 *   node --experimental-strip-types scripts/extract-package-docs.ts --package .
 *   node --experimental-strip-types scripts/extract-package-docs.ts --all
 */
import { readFile, readdir, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import { parseSync } from 'oxc-parser';

export type ExtractedSymbolKind = 'function' | 'class' | 'interface' | 'type' | 'constant' | 'component' | 'fws-export';

export interface ExtractedParameter {
  readonly name: string;
  readonly description?: string;
  readonly type?: string;
}

export interface ExtractedSymbol {
  readonly name: string;
  readonly kind: ExtractedSymbolKind;
  readonly signature: string;
  readonly description: string;
  readonly parameters: readonly ExtractedParameter[];
  readonly tags: readonly { readonly name: string; readonly text: string }[];
  readonly sourceModule: string;
}

export interface PackageDocumentation {
  readonly packageName: string;
  readonly packageRoot: string;
  readonly symbols: readonly ExtractedSymbol[];
}

interface PackageManifest {
  readonly name?: string;
  readonly types?: string;
  readonly main?: string;
  readonly module?: string;
  readonly exports?: unknown;
}

const packageDirectories = ['packages', 'configs', 'forge-plugins', 'vite-plugins', 'workers', 'extensions'] as const;
const sourceExtensions = ['.ts', '.tsx', '.mts', '.cts', '.d.ts'] as const;
const generatedMarker = '<!-- Generated by scripts/extract-package-docs.ts. Do not edit. -->';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function walk(directory: string, predicate: (path: string) => boolean): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths: string[] = [];
  for (const entry of entries.toSorted((left, right) => left.name.localeCompare(right.name))) {
    if (entry.isSymbolicLink() || entry.name === 'node_modules' || entry.name === 'dist' || entry.name.startsWith('.'))
      continue;
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) paths.push(...(await walk(path, predicate)));
    else if (entry.isFile() && predicate(path)) paths.push(path);
  }
  return paths;
}

async function readManifest(packageRoot: string): Promise<PackageManifest | undefined> {
  const path = resolve(packageRoot, 'package.json');
  if (!(await fileExists(path))) return undefined;
  return JSON.parse(await readFile(path, 'utf8')) as PackageManifest;
}

/** Find package roots in the publishable workspace directories. */
export async function discoverPackageRoots(repoRoot: string): Promise<readonly string[]> {
  const roots: string[] = [];
  for (const directory of packageDirectories) {
    const base = resolve(repoRoot, directory);
    if (await fileExists(resolve(base, 'package.json'))) {
      const manifest = await readManifest(base);
      if (manifest?.name !== undefined) roots.push(base);
    } else {
      const manifests = await walk(base, (path) => path.endsWith(`${sep}package.json`));
      for (const manifestPath of manifests) {
        const manifest = await readManifest(dirname(manifestPath));
        if (manifest?.name !== undefined) roots.push(dirname(manifestPath));
      }
    }
  }
  return roots.sort();
}

function exportTargets(value: unknown, targets: string[]): void {
  if (typeof value === 'string') {
    targets.push(value);
    return;
  }
  if (!isRecord(value)) return;
  // Prefer declaration-bearing paths, then recurse through conditions and
  // subpath exports. Duplicates are removed after source mapping.
  for (const key of ['types', 'typings', 'import', 'default']) {
    if (key in value) exportTargets(value[key], targets);
  }
  for (const [key, entry] of Object.entries(value)) {
    if (!['types', 'typings', 'import', 'default'].includes(key)) exportTargets(entry, targets);
  }
}

function sourceCandidates(packageRoot: string, target: string): string[] {
  const normalized = target.replaceAll('\\', '/').replace(/^\.\//u, '');
  const sourceTarget = normalized.startsWith('dist/') ? `src/${normalized.slice('dist/'.length)}` : normalized;
  const withoutDeclaration = sourceTarget.replace(/\.d\.(?:mts|cts|ts)$/u, '').replace(/\.[mc]?js$/u, '');
  const candidates = [withoutDeclaration, sourceTarget].flatMap((candidate) => [
    candidate,
    ...sourceExtensions.map((extension) => `${candidate}${extension}`),
    ...sourceExtensions.map((extension) => `${candidate}/index${extension}`),
  ]);
  return candidates.map((candidate) => resolve(packageRoot, candidate));
}

async function typeScriptEntries(packageRoot: string, manifest: PackageManifest): Promise<readonly string[]> {
  const targets: string[] = [];
  exportTargets(manifest.exports, targets);
  for (const fallback of [manifest.types, manifest.module, manifest.main, './src/index.ts']) {
    if (fallback !== undefined) targets.push(fallback);
  }
  const entries: string[] = [];
  for (const target of targets) {
    for (const candidate of sourceCandidates(packageRoot, target)) {
      if (sourceExtensions.some((extension) => candidate.endsWith(extension)) && (await fileExists(candidate)))
        entries.push(candidate);
    }
  }
  return entries.toSorted().filter((entry, index, all) => all.indexOf(entry) === index);
}

interface OxcNode {
  readonly type: string;
  readonly start: number;
  readonly end: number;
  readonly [key: string]: unknown;
}

interface OxcComment {
  readonly type: string;
  readonly value: string;
  readonly start: number;
  readonly end: number;
}

interface ParsedModule {
  readonly fileName: string;
  readonly source: string;
  readonly program: OxcNode;
  readonly comments: readonly OxcComment[];
}

interface ParsedDocumentation {
  readonly description: string;
  readonly tags: readonly { readonly name: string; readonly text: string }[];
  readonly parameterDescriptions: ReadonlyMap<string, string>;
}

interface ScannedDeclaration {
  readonly name: string;
  readonly kind: ExtractedSymbolKind;
  readonly node: OxcNode;
  readonly signatureNode: OxcNode;
  readonly module: ParsedModule;
  readonly documentation: ParsedDocumentation;
  readonly sourceModule: string;
  readonly defaultExport?: boolean;
}

interface ExportBinding {
  readonly exportedName: string;
  readonly localName?: string;
  readonly source?: string;
  readonly star: boolean;
}

interface ScannedModule {
  readonly parsed: ParsedModule;
  readonly declarations: ReadonlyMap<string, ScannedDeclaration>;
  readonly exports: readonly ExportBinding[];
}

function oxcObject(node: OxcNode | undefined, key: string): OxcNode | undefined {
  const value = node?.[key];
  return typeof value === 'object' && value !== null && typeof (value as { type?: unknown }).type === 'string'
    ? (value as OxcNode)
    : undefined;
}

function oxcArray(node: OxcNode | undefined, key: string): readonly OxcNode[] {
  const value = node?.[key];
  return Array.isArray(value)
    ? value.filter(
        (entry): entry is OxcNode =>
          typeof entry === 'object' && entry !== null && typeof (entry as { type?: unknown }).type === 'string',
      )
    : [];
}

function oxcName(node: OxcNode | undefined): string | undefined {
  if (node === undefined) return undefined;
  const name = node.name;
  return typeof name === 'string' ? name : undefined;
}

function oxcLiteral(node: OxcNode | undefined): string | undefined {
  const value = node?.value;
  return typeof value === 'string' ? value : undefined;
}

function parserLanguage(fileName: string): 'ts' | 'tsx' {
  return /\.tsx$/u.test(fileName) ? 'tsx' : 'ts';
}

function parseSource(fileName: string, source: string): ParsedModule {
  const result = parseSync(fileName, source, { lang: parserLanguage(fileName), sourceType: 'module', astType: 'ts' });
  return {
    fileName,
    source,
    program: result.program as unknown as OxcNode,
    comments: (result.comments ?? []) as OxcComment[],
  };
}

function documentationFor(module: ParsedModule, start: number): ParsedDocumentation {
  const comment = module.comments
    .filter((candidate) => candidate.type === 'Block' && candidate.value.startsWith('*') && candidate.end <= start)
    .toSorted((left, right) => right.end - left.end)
    .find((candidate) => module.source.slice(candidate.end, start).trim() === '');
  if (comment === undefined) return { description: '', tags: [], parameterDescriptions: new Map() };

  const lines = comment.value.split('\n').map((line) => line.replace(/^\s*\* ?/u, '').trimEnd());
  while (lines[0]?.trim() === '') lines.shift();
  while (lines.at(-1)?.trim() === '') lines.pop();
  const description: string[] = [];
  const tags: { name: string; text: string }[] = [];
  const parameterDescriptions = new Map<string, string>();
  let currentTag: { name: string; text: string } | undefined;
  for (const line of lines) {
    const tag = /^@(\S+)(?:\s+(.*))?$/u.exec(line.trim());
    if (tag !== null) {
      currentTag = { name: tag[1], text: tag[2]?.trim() ?? '' };
      tags.push(currentTag);
      if (['param', 'parameter', 'arg', 'argument'].includes(currentTag.name)) {
        const parameter = /^(?:\{[^}]+\}\s+)?([^\s]+)(?:\s+(.*))?$/u.exec(currentTag.text);
        const subject = parameter?.[1] ?? currentTag.text;
        const text = parameter?.[2]?.trim() ?? '';
        currentTag.text = text;
        if (subject !== '') parameterDescriptions.set(subject, text);
      } else if (/^(?:returns?|throws?|exception|type|extends|implements|template)$/u.test(currentTag.name)) {
        currentTag.text = currentTag.text.replace(/^\{[^}]+\}(?:\s+|$)/u, '').trim();
      }
    } else if (currentTag === undefined) {
      description.push(line);
    } else if (line.trim() !== '') {
      currentTag.text = `${currentTag.text}\n${line.trim()}`.trim();
    }
  }
  return { description: description.join('\n').trim(), tags, parameterDescriptions };
}

function declarationKind(node: OxcNode): ExtractedSymbolKind | undefined {
  switch (node.type) {
    case 'FunctionDeclaration': {
      return 'function';
    }
    case 'TSDeclareFunction': {
      return 'function';
    }
    case 'ClassDeclaration': {
      return 'class';
    }
    case 'TSInterfaceDeclaration': {
      return 'interface';
    }
    case 'TSTypeAliasDeclaration': {
      return 'type';
    }
    case 'TSEnumDeclaration': {
      return 'type';
    }
    case 'VariableDeclarator': {
      return 'constant';
    }
    default: {
      return undefined;
    }
  }
}

function declarationSignature(module: ParsedModule, declaration: ScannedDeclaration): string {
  const node = declaration.node;
  if (declaration.kind === 'function') {
    const name = oxcName(oxcObject(node, 'id')) ?? '<anonymous>';
    const parameters = oxcArray(node, 'params')
      .map((parameter) => module.source.slice(parameter.start, parameter.end))
      .join(', ');
    const returnType = oxcObject(node, 'returnType');
    const returnText =
      returnType === undefined ? '' : `: ${module.source.slice(returnType.start + 1, returnType.end).trim()}`;
    return `function ${name}(${parameters})${returnText}`;
  }
  if (declaration.kind === 'constant') {
    const variableDeclaration = declaration.signatureNode;
    const keyword =
      variableDeclaration.kind === 'let' || variableDeclaration.kind === 'var' ? variableDeclaration.kind : 'const';
    const name = oxcName(oxcObject(node, 'id')) ?? node.name;
    const typeAnnotation =
      oxcObject(node, 'id') === undefined ? undefined : oxcObject(oxcObject(node, 'id'), 'typeAnnotation');
    const typeText =
      typeAnnotation === undefined
        ? ''
        : `: ${module.source.slice(typeAnnotation.start + 1, typeAnnotation.end).trim()}`;
    return `export ${keyword} ${name}${typeText}`;
  }
  const text = module.source.slice(node.start, node.end).replaceAll(/\s+/gu, ' ').trim();
  const bodyStart = text.indexOf('{');
  const signature = bodyStart === -1 ? text : text.slice(0, bodyStart).trim();
  const exportedSignature = signature.startsWith('export ') ? signature : `export ${signature}`;
  return declaration.defaultExport === true && !exportedSignature.startsWith('export default ')
    ? exportedSignature.replace(/^export\s+/u, 'export default ')
    : exportedSignature;
}

function parameterBinding(parameter: OxcNode): OxcNode {
  let binding = parameter;
  while (binding.type === 'AssignmentPattern' || binding.type === 'RestElement') {
    const next = oxcObject(binding, binding.type === 'AssignmentPattern' ? 'left' : 'argument');
    if (next === undefined) break;
    binding = next;
  }
  return binding;
}

function parameterDetails(
  module: ParsedModule,
  parameter: OxcNode,
): {
  readonly name: string;
  readonly typeAnnotation?: OxcNode;
} {
  const binding = parameterBinding(parameter);
  const name = oxcName(binding) ?? module.source.slice(binding.start, binding.end).trim();
  const typeAnnotation = oxcObject(parameter, 'typeAnnotation') ?? oxcObject(binding, 'typeAnnotation');
  return { name, ...(typeAnnotation === undefined ? {} : { typeAnnotation }) };
}

function parametersFor(module: ParsedModule, declaration: ScannedDeclaration): readonly ExtractedParameter[] {
  const parameters = oxcArray(declaration.node, 'params');
  return parameters.map((parameter) => {
    const { name, typeAnnotation } = parameterDetails(module, parameter);
    return {
      name,
      ...(typeAnnotation === undefined
        ? {}
        : { type: module.source.slice(typeAnnotation.start + 1, typeAnnotation.end).trim() }),
      ...(declaration.documentation.parameterDescriptions.get(name) === undefined
        ? {}
        : { description: declaration.documentation.parameterDescriptions.get(name) }),
    };
  });
}

function sourceModule(packageRoot: string, fileName: string): string {
  return relative(packageRoot, fileName)
    .replaceAll(sep, '/')
    .replace(/\.[^.]+$/u, '');
}

function scanModule(module: ParsedModule, packageRoot: string): ScannedModule {
  const declarations = new Map<string, ScannedDeclaration>();
  const exports: ExportBinding[] = [];
  const body = Array.isArray(module.program.body) ? (module.program.body as OxcNode[]) : [];
  for (const statement of body) {
    const declaration = oxcObject(statement, 'declaration') ?? statement;
    const unwrapped = oxcObject(statement, 'declaration') === undefined ? statement : declaration;
    if (unwrapped.type === 'VariableDeclaration') {
      for (const variable of oxcArray(unwrapped, 'declarations')) {
        const name = oxcName(oxcObject(variable, 'id'));
        if (name === undefined) continue;
        const kind = declarationKind(variable);
        if (kind === undefined) continue;
        declarations.set(name, {
          name,
          kind: name.startsWith('Mp') ? 'component' : kind,
          node: variable,
          signatureNode: unwrapped,
          module,
          documentation: documentationFor(module, statement.start),
          sourceModule: sourceModule(packageRoot, module.fileName),
        });
        if (statement.type === 'ExportNamedDeclaration')
          exports.push({ exportedName: name, localName: name, star: false });
      }
      continue;
    }
    const name =
      oxcName(oxcObject(unwrapped, 'id')) ?? (unwrapped.type === 'Identifier' ? oxcName(unwrapped) : undefined);
    const kind = declarationKind(unwrapped);
    if (kind !== undefined && name !== undefined) {
      declarations.set(name, {
        name,
        kind: name.startsWith('Mp') ? 'component' : kind,
        node: unwrapped,
        signatureNode: unwrapped,
        module,
        documentation: documentationFor(module, statement.start),
        sourceModule: sourceModule(packageRoot, module.fileName),
      });
      if (statement.type === 'ExportNamedDeclaration')
        exports.push({ exportedName: name, localName: name, star: false });
    }
    if (statement.type === 'ExportDefaultDeclaration') {
      const defaultName = name ?? 'default';
      const existing = declarations.get(defaultName) ?? (name === undefined ? undefined : declarations.get(name));
      if (existing !== undefined) {
        declarations.set('default', { ...existing, defaultExport: true });
        exports.push({ exportedName: 'default', localName: 'default', star: false });
      }
    }
    if (statement.type === 'ExportNamedDeclaration' || statement.type === 'ExportDefaultDeclaration') {
      const source = oxcLiteral(oxcObject(statement, 'source'));
      for (const specifier of oxcArray(statement, 'specifiers')) {
        const localName = oxcName(oxcObject(specifier, 'local'));
        const exportedName = oxcName(oxcObject(specifier, 'exported'));
        if (localName !== undefined && exportedName !== undefined)
          exports.push({ exportedName, localName, ...(source === undefined ? {} : { source }), star: false });
      }
    }
    if (statement.type === 'ExportAllDeclaration') {
      const source = oxcLiteral(oxcObject(statement, 'source'));
      if (source !== undefined) exports.push({ exportedName: '', source, star: true });
    }
  }
  return { parsed: module, declarations, exports };
}

function relativeModuleCandidates(fileName: string, specifier: string): string[] {
  const base = resolve(dirname(fileName), specifier.replace(/\.[mc]?js$/u, ''));
  return [
    base,
    ...sourceExtensions.map((extension) => `${base}${extension}`),
    ...sourceExtensions.map((extension) => `${base}/index${extension}`),
  ];
}

async function resolveLocalModule(
  fileName: string,
  packageRoot: string,
  specifier: string,
): Promise<string | undefined> {
  if (!specifier.startsWith('.')) return undefined;
  for (const candidate of relativeModuleCandidates(fileName, specifier)) {
    if (!candidate.startsWith(`${resolve(packageRoot)}${sep}`)) continue;
    if (await fileExists(candidate)) return candidate;
  }
  return undefined;
}

async function exportedDeclarations(
  fileName: string,
  packageRoot: string,
  modules: Map<string, ScannedModule>,
  resolving: Set<string>,
): Promise<ReadonlyMap<string, ScannedDeclaration>> {
  if (resolving.has(fileName)) return new Map();
  let module = modules.get(fileName);
  if (module === undefined) {
    module = scanModule(parseSource(fileName, await readFile(fileName, 'utf8')), packageRoot);
    modules.set(fileName, module);
  }
  const nextResolving = new Set(resolving).add(fileName);
  const result = new Map<string, ScannedDeclaration>();
  for (const binding of module.exports) {
    if (binding.source === undefined) {
      const declaration = module.declarations.get(binding.localName ?? binding.exportedName);
      if (declaration !== undefined) result.set(binding.exportedName, declaration);
      continue;
    }
    const targetFile = await resolveLocalModule(fileName, packageRoot, binding.source);
    if (targetFile === undefined) continue;
    const target = await exportedDeclarations(targetFile, packageRoot, modules, nextResolving);
    if (binding.star) {
      for (const [name, declaration] of target) if (name !== 'default') result.set(name, declaration);
    } else {
      const declaration = target.get(binding.localName ?? binding.exportedName);
      if (declaration !== undefined) result.set(binding.exportedName, declaration);
    }
  }
  return result;
}

/** Extract exported declarations from the package's TypeScript entrypoints. */
export async function extractTypeScriptSymbols(
  packageRoot: string,
  manifest: PackageManifest,
): Promise<readonly ExtractedSymbol[]> {
  const entries = await typeScriptEntries(packageRoot, manifest);
  if (entries.length === 0) return [];
  const modules = new Map<string, ScannedModule>();
  const symbolGroups = await Promise.all(
    entries.map(async (entry) => {
      const declarations = await exportedDeclarations(entry, packageRoot, modules, new Set());
      return [...declarations].map(([name, declaration]) => ({
        name,
        kind: declaration.kind,
        signature: declarationSignature(declaration.module, declaration),
        description: declaration.documentation.description || 'No description provided.',
        parameters: parametersFor(declaration.module, declaration),
        tags: declaration.documentation.tags,
        sourceModule: declaration.sourceModule,
      }));
    }),
  );
  const symbols = symbolGroups.flat();
  const seen = new Set<string>();
  const sortedSymbols = symbols.toSorted((left, right) =>
    `${left.sourceModule}:${left.name}`.localeCompare(`${right.sourceModule}:${right.name}`),
  );
  return sortedSymbols.filter((symbol) => {
    const key = `${symbol.sourceModule}:${symbol.name}:${symbol.kind}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

interface FwsDocumentation {
  readonly description: string;
  readonly tags: readonly { readonly name: string; readonly subject?: string; readonly text: string }[];
}

interface FwsSymbolLike {
  readonly kind: string;
  readonly name: string;
  readonly documentation?: FwsDocumentation;
  readonly exported?: boolean;
  readonly parameters?: readonly { readonly name: string; readonly type: unknown }[];
  readonly result?: unknown;
  readonly iterable?: boolean;
}

function fwsTypeNameToString(type: unknown): string {
  if (typeof type === 'string') return type;
  if (!isRecord(type)) return 'unknown';
  const name =
    typeof type.reference === 'string' ? type.reference : typeof type.name === 'string' ? type.name : 'unknown';
  const argumentsList = Array.isArray(type.arguments)
    ? `<${type.arguments.map((argument) => fwsTypeNameToString(argument)).join(', ')}>`
    : '';
  const length = typeof type.length === 'number' ? `[${type.length}]` : '';
  return `${name}${argumentsList}${length}`;
}

function fwsParameters(parameters: readonly { readonly name: string; readonly type: unknown }[]): string {
  return parameters.map((parameter) => `${parameter.name}: ${fwsTypeNameToString(parameter.type)}`).join(', ');
}

function fwsDocumentationTags(
  documentation: FwsDocumentation,
): readonly { readonly name: string; readonly text: string }[] {
  return documentation.tags.map(({ name, subject, text }) => ({
    name,
    text: subject === undefined ? text : `${subject} ${text}`.trim(),
  }));
}

function fwsSignature(declaration: FwsSymbolLike): string {
  if (declaration.kind === 'function') {
    const exportPrefix = declaration.exported === false ? '' : 'export ';
    return `${exportPrefix}${declaration.iterable === true ? 'iter ' : ''}fn ${declaration.name}(${fwsParameters(declaration.parameters ?? [])}) -> ${fwsTypeNameToString(declaration.result)}`;
  }
  if (declaration.kind === 'enum') {
    return `${declaration.exported === false ? '' : 'export '}enum ${declaration.name}`;
  }
  if (declaration.kind === 'struct') return `struct ${declaration.name}`;
  return `interface ${declaration.name}`;
}

function documentedFwsDeclarations(module: {
  readonly functions: readonly FwsSymbolLike[];
  readonly enums: readonly FwsSymbolLike[];
  readonly structs: readonly FwsSymbolLike[];
  readonly interfaces: readonly FwsSymbolLike[];
}): readonly FwsSymbolLike[] {
  // Documented top-level declarations form the public FWS reference surface.
  // Export is preferred for ABI boundaries but is not required for package-owned
  // declaration modules such as the standard library sources.
  return [...module.functions, ...module.enums, ...module.structs, ...module.interfaces].filter(
    (declaration) => declaration.documentation !== undefined,
  );
}

async function loadForgeWebScriptParser(repoRoot: string): Promise<ForgeWebScriptParseFunction | undefined> {
  const candidates = [
    resolve(repoRoot, 'packages/forge-web-script/dist/parser.js'),
    resolve(repoRoot, 'packages/forge-web-script/dist/index.js'),
  ];
  for (const parserPath of candidates) {
    if (!(await fileExists(parserPath))) continue;
    const parserModule = (await import(pathToFileURL(parserPath).href)) as {
      readonly parseForgeWebScript?: ForgeWebScriptParseFunction;
    };
    if (typeof parserModule.parseForgeWebScript === 'function') return parserModule.parseForgeWebScript;
  }
  return undefined;
}

/** Extract documented public Forge Web Script declarations from package `.fws` sources. */
export async function extractFwsSymbols(
  packageRoot: string,
  options: { readonly repoRoot?: string; readonly parseForgeWebScript?: ForgeWebScriptParseFunction } = {},
): Promise<readonly ExtractedSymbol[]> {
  const files = await walk(
    packageRoot,
    (path) => path.endsWith('.fws') && !path.includes(`${sep}fixtures${sep}`) && !path.endsWith('.spec.fws'),
  );
  if (files.length === 0) return [];

  const repoRoot = options.repoRoot ?? resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const parseForgeWebScript = options.parseForgeWebScript ?? (await loadForgeWebScriptParser(repoRoot));
  if (parseForgeWebScript === undefined) {
    // Package prebuilds can run before forge-web-script itself is rebuilt. The
    // docs-site all-workspace extraction runs after builds and regenerates FWS
    // references once packages/forge-web-script/dist/parser.js is available.
    console.warn(
      `Skipping FWS extraction for ${relative(repoRoot, packageRoot)}: build @mission-platform/forge-web-script first so packages/forge-web-script/dist/parser.js is available.`,
    );
    return [];
  }

  const symbols: ExtractedSymbol[] = [];
  for (const file of files) {
    const source = await readFile(file, 'utf8');
    const parserResult = parseForgeWebScript(source, file, { root: packageRoot });
    const errors = parserResult.diagnostics.filter(({ severity }) => severity === 'error');
    if (errors.length > 0) {
      if (!source.includes('/**')) continue;
      throw new Error(
        `Cannot extract ${relative(packageRoot, file)}: ${errors.map(({ message }) => message).join('; ')}`,
      );
    }
    if (parserResult.module === undefined) continue;
    const sourceModule = relative(packageRoot, file)
      .replaceAll(sep, '/')
      .replace(/\.fws$/u, '');
    for (const declaration of documentedFwsDeclarations(parserResult.module)) {
      const docs = declaration.documentation;
      if (docs === undefined) continue;
      symbols.push({
        name: declaration.name,
        kind: 'fws-export',
        signature: fwsSignature(declaration),
        description: docs.description || 'No description provided.',
        parameters:
          declaration.kind === 'function'
            ? (declaration.parameters ?? []).map(({ name, type }) => ({
                name,
                type: fwsTypeNameToString(type),
                ...Object.fromEntries(
                  docs.tags
                    .filter(
                      (tag) => ['param', 'parameter', 'arg', 'argument'].includes(tag.name) && tag.subject === name,
                    )
                    .map((tag) => ['description', tag.text] as const),
                ),
              }))
            : [],
        tags: fwsDocumentationTags(docs),
        sourceModule,
      });
    }
  }
  return symbols.sort((left, right) =>
    `${left.sourceModule}:${left.name}`.localeCompare(`${right.sourceModule}:${right.name}`),
  );
}

type ForgeWebScriptParseResult = {
  readonly module?: {
    readonly functions: readonly FwsSymbolLike[];
    readonly enums: readonly FwsSymbolLike[];
    readonly structs: readonly FwsSymbolLike[];
    readonly interfaces: readonly FwsSymbolLike[];
  };
  readonly diagnostics: readonly { readonly severity: string; readonly message: string }[];
};

type ForgeWebScriptParseFunction = (
  source: string,
  fileName?: string,
  options?: { readonly root?: string },
) => ForgeWebScriptParseResult;

function markdownTableCell(value: string): string {
  return value.replaceAll('|', String.raw`\|`).replaceAll('\n', ' ');
}

/** Render deterministic generated Markdown for a package. */
export function renderReferenceMarkdown(documentation: PackageDocumentation): string {
  const lines = [
    `# ${documentation.packageName} API reference`,
    '',
    generatedMarker,
    '',
    'Generated from public source declarations in `' + documentation.packageName + '`.',
    '',
  ];
  let currentModule: string | undefined;
  for (const symbol of documentation.symbols) {
    if (symbol.sourceModule !== currentModule) {
      currentModule = symbol.sourceModule;
      lines.push('## `' + currentModule + '`', '');
    }
    lines.push(
      `### ${symbol.name}`,
      '',
      `**Kind:** ${symbol.kind}`,
      '',
      '```typescript',
      symbol.signature,
      '```',
      '',
      symbol.description,
      '',
    );
    if (symbol.parameters.length > 0) {
      lines.push('#### Parameters', '', '| Name | Type | Description |', '| --- | --- | --- |');
      for (const parameter of symbol.parameters)
        lines.push(
          `| ${markdownTableCell(parameter.name)} | ${markdownTableCell(parameter.type ?? '')} | ${markdownTableCell(parameter.description ?? '')} |`,
        );
      lines.push('');
    }
    if (symbol.tags.length > 0) {
      lines.push('#### Contract', '');
      for (const tag of symbol.tags) lines.push(`- **@${tag.name}:** ${tag.text}`);
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

async function extractPackage(packageRoot: string, repoRoot: string): Promise<PackageDocumentation> {
  const manifest = await readManifest(packageRoot);
  if (manifest?.name === undefined)
    throw new Error(`Missing package name in ${relative(repoRoot, packageRoot)}/package.json`);
  const symbols = [
    ...(await extractTypeScriptSymbols(packageRoot, manifest)),
    ...(await extractFwsSymbols(packageRoot, { repoRoot })),
  ].sort((left, right) =>
    `${left.sourceModule}:${left.name}:${left.kind}`.localeCompare(`${right.sourceModule}:${right.name}:${right.kind}`),
  );
  return { packageName: manifest.name, packageRoot, symbols };
}

async function writePackageDocumentation(documentation: PackageDocumentation): Promise<void> {
  const outputDirectory = resolve(documentation.packageRoot, 'docs/reference/generated');
  await mkdir(outputDirectory, { recursive: true });
  for (const entry of await readdir(outputDirectory, { withFileTypes: true })) {
    if (entry.isFile() && extname(entry.name) === '.md') await rm(resolve(outputDirectory, entry.name));
  }
  await writeFile(resolve(outputDirectory, 'api.md'), renderReferenceMarkdown(documentation), 'utf8');
}

export async function extractPackageDocs(repoRoot: string, packageRoot: string): Promise<PackageDocumentation> {
  const documentation = await extractPackage(packageRoot, repoRoot);
  await writePackageDocumentation(documentation);
  return documentation;
}

async function main(): Promise<void> {
  const repoRoot = resolve(import.meta.dirname, '..');
  const inlinePackageArgument = process.argv
    .find((argument) => argument.startsWith('--package='))
    ?.slice('--package='.length);
  const packageFlagIndex = process.argv.indexOf('--package');
  const packageArgument =
    inlinePackageArgument ?? (packageFlagIndex === -1 ? undefined : process.argv[packageFlagIndex + 1]);
  if (packageArgument === undefined || process.argv.includes('--all')) {
    const packageRoots = await discoverPackageRoots(repoRoot);
    await Promise.all(packageRoots.map((packageRoot) => extractPackageDocs(repoRoot, packageRoot)));
    return;
  }
  await extractPackageDocs(repoRoot, resolve(process.cwd(), packageArgument));
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === resolve(import.meta.filename)) await main();
