/**
 * Extract public TypeScript and Forge Web Script declarations into package-owned
 * reference documentation.
 *
 * Usage:
 *   node --experimental-strip-types scripts/extract-package-docs.ts --package .
 *   node --experimental-strip-types scripts/extract-package-docs.ts --all
 */
import { readFile, readdir, mkdir, rm, writeFile } from 'node:fs/promises';
import { dirname, extname, relative, resolve, sep } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

import ts from 'typescript';

export type ExtractedSymbolKind = 'function' | 'class' | 'interface' | 'type' | 'constant' | 'component' | 'fws-export';

export interface ExtractedParameter {
  readonly name: string;
  readonly description?: string;
  readonly type?: string;
}

export interface ExtractedSymbol {
  readonly name: string;
  readonly kind: ExtractedSymbolKind;
  readonly signature: string;
  readonly description: string;
  readonly parameters: readonly ExtractedParameter[];
  readonly tags: readonly { readonly name: string; readonly text: string }[];
  readonly sourceModule: string;
}

export interface PackageDocumentation {
  readonly packageName: string;
  readonly packageRoot: string;
  readonly symbols: readonly ExtractedSymbol[];
}

interface PackageManifest {
  readonly name?: string;
  readonly types?: string;
  readonly main?: string;
  readonly module?: string;
  readonly exports?: unknown;
}

const packageDirectories = ['packages', 'configs', 'forge-plugins', 'vite-plugins', 'workers', 'extensions'] as const;
const sourceExtensions = ['.ts', '.tsx', '.mts', '.cts', '.d.ts'] as const;
const generatedMarker = '<!-- Generated by scripts/extract-package-docs.ts. Do not edit. -->';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await readFile(path);
    return true;
  } catch {
    return false;
  }
}

async function walk(directory: string, predicate: (path: string) => boolean): Promise<string[]> {
  const entries = await readdir(directory, { withFileTypes: true });
  const paths: string[] = [];
  for (const entry of entries.toSorted((left, right) => left.name.localeCompare(right.name))) {
    if (entry.isSymbolicLink() || entry.name === 'node_modules' || entry.name === 'dist' || entry.name.startsWith('.'))
      continue;
    const path = resolve(directory, entry.name);
    if (entry.isDirectory()) paths.push(...(await walk(path, predicate)));
    else if (entry.isFile() && predicate(path)) paths.push(path);
  }
  return paths;
}

async function readManifest(packageRoot: string): Promise<PackageManifest | undefined> {
  const path = resolve(packageRoot, 'package.json');
  if (!(await fileExists(path))) return undefined;
  return JSON.parse(await readFile(path, 'utf8')) as PackageManifest;
}

/** Find package roots in the publishable workspace directories. */
export async function discoverPackageRoots(repoRoot: string): Promise<readonly string[]> {
  const roots: string[] = [];
  for (const directory of packageDirectories) {
    const base = resolve(repoRoot, directory);
    if (await fileExists(resolve(base, 'package.json'))) {
      const manifest = await readManifest(base);
      if (manifest?.name !== undefined) roots.push(base);
    } else {
      const manifests = await walk(base, (path) => path.endsWith(`${sep}package.json`));
      for (const manifestPath of manifests) {
        const manifest = await readManifest(dirname(manifestPath));
        if (manifest?.name !== undefined) roots.push(dirname(manifestPath));
      }
    }
  }
  return roots.sort();
}

function exportTargets(value: unknown, targets: string[]): void {
  if (typeof value === 'string') {
    targets.push(value);
    return;
  }
  if (!isRecord(value)) return;
  // Prefer declaration-bearing paths, then recurse through conditions and
  // subpath exports. Duplicates are removed after source mapping.
  for (const key of ['types', 'typings', 'import', 'default']) {
    if (key in value) exportTargets(value[key], targets);
  }
  for (const [key, entry] of Object.entries(value)) {
    if (!['types', 'typings', 'import', 'default'].includes(key)) exportTargets(entry, targets);
  }
}

function sourceCandidates(packageRoot: string, target: string): string[] {
  const normalized = target.replaceAll('\\', '/').replace(/^\.\//u, '');
  const sourceTarget = normalized.startsWith('dist/') ? `src/${normalized.slice('dist/'.length)}` : normalized;
  const withoutDeclaration = sourceTarget.replace(/\.d\.(?:mts|cts|ts)$/u, '').replace(/\.[mc]?js$/u, '');
  const candidates = [withoutDeclaration, sourceTarget].flatMap((candidate) => [
    candidate,
    ...sourceExtensions.map((extension) => `${candidate}${extension}`),
  ]);
  return candidates.map((candidate) => resolve(packageRoot, candidate));
}

async function typeScriptEntries(packageRoot: string, manifest: PackageManifest): Promise<readonly string[]> {
  const targets: string[] = [];
  exportTargets(manifest.exports, targets);
  for (const fallback of [manifest.types, manifest.module, manifest.main, './src/index.ts']) {
    if (fallback !== undefined) targets.push(fallback);
  }
  const entries: string[] = [];
  for (const target of targets) {
    for (const candidate of sourceCandidates(packageRoot, target)) {
      if (sourceExtensions.some((extension) => candidate.endsWith(extension)) && (await fileExists(candidate)))
        entries.push(candidate);
    }
  }
  return entries.toSorted().filter((entry, index, all) => all.indexOf(entry) === index);
}

function jsDocTags(node: ts.Node): readonly { readonly name: string; readonly text: string }[] {
  return ts.getJSDocTags(node).map((tag) => ({
    name: tag.tagName.text,
    text: typeof tag.comment === 'string' ? tag.comment.trim() : (ts.getTextOfJSDocComment(tag.comment)?.trim() ?? ''),
  }));
}

function jsDocDescription(node: ts.Node): string {
  const documentation = ts.getJSDocCommentsAndTags(node).find((entry): entry is ts.JSDoc => ts.isJSDoc(entry));
  if (documentation === undefined) return '';
  const text =
    typeof documentation.comment === 'string' ? documentation.comment : ts.getTextOfJSDocComment(documentation.comment);
  return text?.trim() ?? '';
}

function declarationFor(checker: ts.TypeChecker, symbol: ts.Symbol, packageRoot: string): ts.Declaration | undefined {
  const resolved = (symbol.flags & ts.SymbolFlags.Alias) === 0 ? symbol : checker.getAliasedSymbol(symbol);
  return resolved.declarations?.find((declaration) => {
    const path = resolve(declaration.getSourceFile().fileName);
    return (
      path.startsWith(`${resolve(packageRoot)}${sep}`) &&
      !path.includes(`${sep}test${sep}`) &&
      !path.endsWith('.spec.ts')
    );
  });
}

function symbolKind(node: ts.Declaration): ExtractedSymbolKind | undefined {
  if (ts.isFunctionDeclaration(node) || ts.isMethodDeclaration(node)) return 'function';
  if (ts.isClassDeclaration(node) || ts.isClassExpression(node)) return 'class';
  if (ts.isInterfaceDeclaration(node)) return 'interface';
  if (ts.isTypeAliasDeclaration(node) || ts.isEnumDeclaration(node)) return 'type';
  if (ts.isVariableDeclaration(node)) return 'constant';
  return undefined;
}

function declarationSignature(node: ts.Declaration): string {
  if (ts.isFunctionDeclaration(node) || ts.isMethodDeclaration(node)) {
    const name = node.name?.getText() ?? '<anonymous>';
    const parameters = node.parameters.map((parameter) => parameter.getText()).join(', ');
    return `function ${name}(${parameters})${node.type === undefined ? '' : `: ${node.type.getText()}`}`;
  }
  if (ts.isVariableDeclaration(node)) {
    const list = node.parent;
    const flags = ts.isVariableDeclarationList(list) ? list.flags : 0;
    const keyword = (flags & ts.NodeFlags.Const) === 0 ? ((flags & ts.NodeFlags.Let) === 0 ? 'var' : 'let') : 'const';
    const name = node.name.getText();
    const type = node.type === undefined ? '' : `: ${node.type.getText()}`;
    return `export ${keyword} ${name}${type}`;
  }
  const text = node.getText().replaceAll(/\s+/gu, ' ').trim();
  const bodyStart = text.indexOf('{');
  return bodyStart === -1 ? text : text.slice(0, bodyStart).trim();
}

function parametersFor(
  node: ts.Declaration,
  tags: readonly { readonly name: string; readonly text: string }[],
): readonly ExtractedParameter[] {
  if (!('parameters' in node) || !Array.isArray(node.parameters)) return [];
  const parameterTags = new Map(
    tags
      .filter(({ name }) => ['param', 'parameter', 'arg', 'argument'].includes(name))
      .map((tag) => [tag.name, tag.text]),
  );
  return node.parameters.map((parameter) => ({
    name: parameter.name.getText(),
    ...(parameter.type === undefined ? {} : { type: parameter.type.getText() }),
    ...(parameterTags.get(parameter.name.getText()) === undefined
      ? {}
      : { description: parameterTags.get(parameter.name.getText()) }),
  }));
}

function extractSourceFile(sourceFile: ts.SourceFile, checker: ts.TypeChecker, packageRoot: string): ExtractedSymbol[] {
  const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
  if (moduleSymbol === undefined) return [];
  return checker.getExportsOfModule(moduleSymbol).flatMap((exported) => {
    const declaration = declarationFor(checker, exported, packageRoot);
    const kind = declaration === undefined ? undefined : symbolKind(declaration);
    if (declaration === undefined || kind === undefined) return [];
    const tags = jsDocTags(declaration);
    const description = jsDocDescription(declaration) || 'No description provided.';
    const sourceModule = relative(packageRoot, declaration.getSourceFile().fileName)
      .replaceAll(sep, '/')
      .replace(/\.[^.]+$/u, '');
    return [
      {
        name: exported.name,
        kind: (declaration as ts.NamedDeclaration).name?.getText().startsWith('Mp') === true ? 'component' : kind,
        signature: declarationSignature(declaration),
        description,
        parameters: parametersFor(declaration, tags),
        tags,
        sourceModule,
      },
    ];
  });
}

/** Extract exported declarations from the package's TypeScript entrypoints. */
export async function extractTypeScriptSymbols(
  packageRoot: string,
  manifest: PackageManifest,
): Promise<readonly ExtractedSymbol[]> {
  const entries = await typeScriptEntries(packageRoot, manifest);
  if (entries.length === 0) return [];
  const options: ts.CompilerOptions = {
    allowJs: false,
    jsx: ts.JsxEmit.Preserve,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    noEmit: true,
    skipLibCheck: true,
    target: ts.ScriptTarget.ES2022,
  };
  const host = ts.createCompilerHost(options);
  host.resolveModuleNames = (moduleNames, containingFile) =>
    moduleNames.map((moduleName) => {
      const resolved = ts.resolveModuleName(moduleName, containingFile, options, host).resolvedModule;
      if (resolved === undefined || !resolve(resolved.resolvedFileName).startsWith(`${resolve(packageRoot)}${sep}`))
        return;
      return resolved;
    });
  const program = ts.createProgram(entries, options, host);
  const checker = program.getTypeChecker();
  const symbols = entries.flatMap((entry) => {
    const sourceFile = program.getSourceFile(entry);
    return sourceFile === undefined ? [] : extractSourceFile(sourceFile, checker, packageRoot);
  });
  const seen = new Set<string>();
  const sortedSymbols = symbols.toSorted((left, right) =>
    `${left.sourceModule}:${left.name}`.localeCompare(`${right.sourceModule}:${right.name}`),
  );
  return sortedSymbols.filter((symbol) => {
    const key = `${symbol.sourceModule}:${symbol.name}:${symbol.kind}`;
    if (seen.has(key)) return false;
    seen.add(key);
    return true;
  });
}

interface FwsDocumentation {
  readonly description: string;
  readonly tags: readonly { readonly name: string; readonly subject?: string; readonly text: string }[];
}

interface FwsSymbolLike {
  readonly kind: string;
  readonly name: string;
  readonly documentation?: FwsDocumentation;
  readonly exported?: boolean;
  readonly parameters?: readonly { readonly name: string; readonly type: unknown }[];
  readonly result?: unknown;
  readonly iterable?: boolean;
}

function fwsTypeNameToString(type: unknown): string {
  if (typeof type === 'string') return type;
  if (!isRecord(type)) return 'unknown';
  const name =
    typeof type.reference === 'string' ? type.reference : typeof type.name === 'string' ? type.name : 'unknown';
  const argumentsList = Array.isArray(type.arguments)
    ? `<${type.arguments.map((argument) => fwsTypeNameToString(argument)).join(', ')}>`
    : '';
  const length = typeof type.length === 'number' ? `[${type.length}]` : '';
  return `${name}${argumentsList}${length}`;
}

function fwsParameters(parameters: readonly { readonly name: string; readonly type: unknown }[]): string {
  return parameters.map((parameter) => `${parameter.name}: ${fwsTypeNameToString(parameter.type)}`).join(', ');
}

function fwsDocumentationTags(
  documentation: FwsDocumentation,
): readonly { readonly name: string; readonly text: string }[] {
  return documentation.tags.map(({ name, subject, text }) => ({
    name,
    text: subject === undefined ? text : `${subject} ${text}`.trim(),
  }));
}

function fwsSignature(declaration: FwsSymbolLike): string {
  if (declaration.kind === 'function') {
    const exportPrefix = declaration.exported === false ? '' : 'export ';
    return `${exportPrefix}${declaration.iterable === true ? 'iter ' : ''}fn ${declaration.name}(${fwsParameters(declaration.parameters ?? [])}) -> ${fwsTypeNameToString(declaration.result)}`;
  }
  if (declaration.kind === 'enum') {
    return `${declaration.exported === false ? '' : 'export '}enum ${declaration.name}`;
  }
  if (declaration.kind === 'struct') return `struct ${declaration.name}`;
  return `interface ${declaration.name}`;
}

function documentedFwsDeclarations(module: {
  readonly functions: readonly FwsSymbolLike[];
  readonly enums: readonly FwsSymbolLike[];
  readonly structs: readonly FwsSymbolLike[];
  readonly interfaces: readonly FwsSymbolLike[];
}): readonly FwsSymbolLike[] {
  // Documented top-level declarations form the public FWS reference surface.
  // Export is preferred for ABI boundaries but is not required for package-owned
  // declaration modules such as the standard library sources.
  return [...module.functions, ...module.enums, ...module.structs, ...module.interfaces].filter(
    (declaration) => declaration.documentation !== undefined,
  );
}

async function loadForgeWebScriptParser(repoRoot: string): Promise<ForgeWebScriptParseFunction | undefined> {
  const candidates = [
    resolve(repoRoot, 'packages/forge-web-script/dist/parser.js'),
    resolve(repoRoot, 'packages/forge-web-script/dist/index.js'),
  ];
  for (const parserPath of candidates) {
    if (!(await fileExists(parserPath))) continue;
    const parserModule = (await import(pathToFileURL(parserPath).href)) as {
      readonly parseForgeWebScript?: ForgeWebScriptParseFunction;
    };
    if (typeof parserModule.parseForgeWebScript === 'function') return parserModule.parseForgeWebScript;
  }
  return undefined;
}

/** Extract documented public Forge Web Script declarations from package `.fws` sources. */
export async function extractFwsSymbols(
  packageRoot: string,
  options: { readonly repoRoot?: string; readonly parseForgeWebScript?: ForgeWebScriptParseFunction } = {},
): Promise<readonly ExtractedSymbol[]> {
  const files = await walk(
    packageRoot,
    (path) => path.endsWith('.fws') && !path.includes(`${sep}fixtures${sep}`) && !path.endsWith('.spec.fws'),
  );
  if (files.length === 0) return [];

  const repoRoot = options.repoRoot ?? resolve(dirname(fileURLToPath(import.meta.url)), '..');
  const parseForgeWebScript = options.parseForgeWebScript ?? (await loadForgeWebScriptParser(repoRoot));
  if (parseForgeWebScript === undefined) {
    // Package prebuilds can run before forge-web-script itself is rebuilt. The
    // docs-site all-workspace extraction runs after builds and regenerates FWS
    // references once packages/forge-web-script/dist/parser.js is available.
    console.warn(
      `Skipping FWS extraction for ${relative(repoRoot, packageRoot)}: build @mission-platform/forge-web-script first so packages/forge-web-script/dist/parser.js is available.`,
    );
    return [];
  }

  const symbols: ExtractedSymbol[] = [];
  for (const file of files) {
    const source = await readFile(file, 'utf8');
    const parserResult = parseForgeWebScript(source, file, { root: packageRoot });
    const errors = parserResult.diagnostics.filter(({ severity }) => severity === 'error');
    if (errors.length > 0) {
      if (!source.includes('/**')) continue;
      throw new Error(
        `Cannot extract ${relative(packageRoot, file)}: ${errors.map(({ message }) => message).join('; ')}`,
      );
    }
    if (parserResult.module === undefined) continue;
    const sourceModule = relative(packageRoot, file)
      .replaceAll(sep, '/')
      .replace(/\.fws$/u, '');
    for (const declaration of documentedFwsDeclarations(parserResult.module)) {
      const docs = declaration.documentation;
      if (docs === undefined) continue;
      symbols.push({
        name: declaration.name,
        kind: 'fws-export',
        signature: fwsSignature(declaration),
        description: docs.description || 'No description provided.',
        parameters:
          declaration.kind === 'function'
            ? (declaration.parameters ?? []).map(({ name, type }) => ({
                name,
                type: fwsTypeNameToString(type),
                ...Object.fromEntries(
                  docs.tags
                    .filter(
                      (tag) => ['param', 'parameter', 'arg', 'argument'].includes(tag.name) && tag.subject === name,
                    )
                    .map((tag) => ['description', tag.text] as const),
                ),
              }))
            : [],
        tags: fwsDocumentationTags(docs),
        sourceModule,
      });
    }
  }
  return symbols.sort((left, right) =>
    `${left.sourceModule}:${left.name}`.localeCompare(`${right.sourceModule}:${right.name}`),
  );
}

type ForgeWebScriptParseResult = {
  readonly module?: {
    readonly functions: readonly FwsSymbolLike[];
    readonly enums: readonly FwsSymbolLike[];
    readonly structs: readonly FwsSymbolLike[];
    readonly interfaces: readonly FwsSymbolLike[];
  };
  readonly diagnostics: readonly { readonly severity: string; readonly message: string }[];
};

type ForgeWebScriptParseFunction = (
  source: string,
  fileName?: string,
  options?: { readonly root?: string },
) => ForgeWebScriptParseResult;

function markdownTableCell(value: string): string {
  return value.replaceAll('|', String.raw`\|`).replaceAll('\n', ' ');
}

/** Render deterministic generated Markdown for a package. */
export function renderReferenceMarkdown(documentation: PackageDocumentation): string {
  const lines = [
    `# ${documentation.packageName} API reference`,
    '',
    generatedMarker,
    '',
    'Generated from public source declarations in `' + documentation.packageName + '`.',
    '',
  ];
  let currentModule: string | undefined;
  for (const symbol of documentation.symbols) {
    if (symbol.sourceModule !== currentModule) {
      currentModule = symbol.sourceModule;
      lines.push('## `' + currentModule + '`', '');
    }
    lines.push(
      `### ${symbol.name}`,
      '',
      `**Kind:** ${symbol.kind}`,
      '',
      '```typescript',
      symbol.signature,
      '```',
      '',
      symbol.description,
      '',
    );
    if (symbol.parameters.length > 0) {
      lines.push('#### Parameters', '', '| Name | Type | Description |', '| --- | --- | --- |');
      for (const parameter of symbol.parameters)
        lines.push(
          `| ${markdownTableCell(parameter.name)} | ${markdownTableCell(parameter.type ?? '')} | ${markdownTableCell(parameter.description ?? '')} |`,
        );
      lines.push('');
    }
    if (symbol.tags.length > 0) {
      lines.push('#### Contract', '');
      for (const tag of symbol.tags) lines.push(`- **@${tag.name}:** ${tag.text}`);
      lines.push('');
    }
  }
  return `${lines.join('\n').trimEnd()}\n`;
}

async function extractPackage(packageRoot: string, repoRoot: string): Promise<PackageDocumentation> {
  const manifest = await readManifest(packageRoot);
  if (manifest?.name === undefined)
    throw new Error(`Missing package name in ${relative(repoRoot, packageRoot)}/package.json`);
  const symbols = [
    ...(await extractTypeScriptSymbols(packageRoot, manifest)),
    ...(await extractFwsSymbols(packageRoot, { repoRoot })),
  ].sort((left, right) =>
    `${left.sourceModule}:${left.name}:${left.kind}`.localeCompare(`${right.sourceModule}:${right.name}:${right.kind}`),
  );
  return { packageName: manifest.name, packageRoot, symbols };
}

async function writePackageDocumentation(documentation: PackageDocumentation): Promise<void> {
  const outputDirectory = resolve(documentation.packageRoot, 'docs/reference/generated');
  await mkdir(outputDirectory, { recursive: true });
  for (const entry of await readdir(outputDirectory, { withFileTypes: true })) {
    if (entry.isFile() && extname(entry.name) === '.md') await rm(resolve(outputDirectory, entry.name));
  }
  await writeFile(resolve(outputDirectory, 'api.md'), renderReferenceMarkdown(documentation), 'utf8');
}

export async function extractPackageDocs(repoRoot: string, packageRoot: string): Promise<PackageDocumentation> {
  const documentation = await extractPackage(packageRoot, repoRoot);
  await writePackageDocumentation(documentation);
  return documentation;
}

async function main(): Promise<void> {
  const repoRoot = resolve(import.meta.dirname, '..');
  const inlinePackageArgument = process.argv
    .find((argument) => argument.startsWith('--package='))
    ?.slice('--package='.length);
  const packageFlagIndex = process.argv.indexOf('--package');
  const packageArgument =
    inlinePackageArgument ?? (packageFlagIndex === -1 ? undefined : process.argv[packageFlagIndex + 1]);
  if (packageArgument === undefined || process.argv.includes('--all')) {
    await Promise.all((await discoverPackageRoots(repoRoot)).map((packageRoot) => extractPackageDocs(repoRoot, packageRoot)));
    return;
  }
  await extractPackageDocs(repoRoot, resolve(process.cwd(), packageArgument));
}

if (process.argv[1] !== undefined && resolve(process.argv[1]) === resolve(import.meta.filename)) await main();
