/**
 * TypeScript declaration (.d.ts) generator from Web IDL ASTs.
 * Emits type definitions matching Wasm module exports and host capability contracts.
 */

import type {
  DtsOptions,
  WebIdlDictionary,
  WebIdlEnum,
  WebIdlInterface,
  WebIdlModule,
  WebIdlType,
  WebIdlTypedef,
} from './types.js';

export class DtsGenerator {
  private readonly module: WebIdlModule;
  private readonly options: DtsOptions;

  public constructor(module: WebIdlModule, options: DtsOptions = {}) {
    this.module = module;
    this.options = options;
  }

  public generate(): string {
    const lines: string[] = [
      '// Generated by Forge Web Script Web IDL Type Declaration Generator',
      '// DO NOT EDIT DIRECTLY',
      '',
    ];

    const prefix = this.options.capabilityPrefix ?? 'web';

    // 1. Typedefs
    const typedefs = this.module.definitions.filter((d): d is WebIdlTypedef => d.kind === 'typedef');
    for (const td of typedefs) {
      lines.push(`export type ${td.name} = ${this.mapTsType(td.type)};`);
    }
    if (typedefs.length > 0) lines.push('');

    // 2. Enums
    const enums = this.module.definitions.filter((d): d is WebIdlEnum => d.kind === 'enum');
    for (const enumDeclaration of enums) {
      const variants = enumDeclaration.values.map((v) => `'${v}'`).join(' | ');
      lines.push(`export type ${enumDeclaration.name} = ${variants || 'string'};`);
    }
    if (enums.length > 0) lines.push('');

    // 3. Dictionaries
    const dictionaries = this.module.definitions.filter((d): d is WebIdlDictionary => d.kind === 'dictionary');
    for (const dict of dictionaries) {
      const heritage = dict.parent ? ` extends ${dict.parent}` : '';
      lines.push(`export interface ${dict.name}${heritage} {`);
      for (const member of dict.members) {
        const optional = member.required ? '' : '?';
        lines.push(`  readonly ${member.name}${optional}: ${this.mapTsType(member.type)};`);
      }
      lines.push('}', '');
    }

    // 4. Interfaces
    const interfaces = this.module.definitions.filter((d): d is WebIdlInterface => d.kind === 'interface');
    for (const iface of interfaces) {
      const heritage = iface.parent ? ` extends ${iface.parent}` : '';
      lines.push(`export interface ${iface.name}${heritage} {`);

      for (const member of iface.members) {
        if (member.kind === 'attribute') {
          const readonly = member.readonly ? 'readonly ' : '';
          lines.push(`  ${readonly}${member.name}: ${this.mapTsType(member.type)};`);
        } else if (member.kind === 'operation' && member.name !== undefined) {
          const arguments_ = member.arguments
            .map((argument) => `${argument.name}${argument.optional ? '?' : ''}: ${this.mapTsType(argument.type)}`)
            .join(', ');
          lines.push(`  ${member.name}(${arguments_}): ${this.mapTsType(member.returnType)};`);
        }
      }

      lines.push('}', '');
    }

    // 5. Host capability imports descriptor interface
    lines.push('export interface WasmHostCapabilities {');
    for (const iface of interfaces) {
      lines.push(`  readonly '${prefix}.${iface.name}': {`);
      for (const member of iface.members) {
        if (member.kind === 'attribute') {
          const getterProperty = `get_${this.toSnakeCase(member.name)}`;
          lines.push(`    readonly '${getterProperty}': () => ${this.mapTsType(member.type)};`);
          if (!member.readonly) {
            const setterProperty = `set_${this.toSnakeCase(member.name)}`;
            lines.push(`    readonly '${setterProperty}': (value: ${this.mapTsType(member.type)}) => void;`);
          }
        } else if (member.kind === 'operation' && member.name !== undefined) {
          const arguments_ = member.arguments
            .map((argument) => `${argument.name}: ${this.mapWasmAbiType(argument.type)}`)
            .join(', ');
          lines.push(`    readonly '${member.name}': (${arguments_}) => ${this.mapWasmAbiType(member.returnType)};`);
        }
      }
      lines.push('  };');
    }
    lines.push('}', '');

    return lines.join('\n').trim() + '\n';
  }

  private mapTsType(type: WebIdlType): string {
    let result: string;

    switch (type.kind) {
      case 'primitive': {
        result = this.mapPrimitive(type.name);
        break;
      }
      case 'string': {
        result = 'string';
        break;
      }
      case 'buffer': {
        result = type.name === 'ArrayBuffer' ? 'ArrayBuffer' : 'Uint8Array';
        break;
      }
      case 'sequence':
      case 'frozen-array': {
        const inner = type.typeArguments?.[0] ? this.mapTsType(type.typeArguments[0]) : 'unknown';
        result = `readonly (${inner})[]`;
        break;
      }
      case 'promise': {
        const inner = type.typeArguments?.[0] ? this.mapTsType(type.typeArguments[0]) : 'void';
        result = `Promise<${inner}>`;
        break;
      }
      case 'record': {
        const key = type.typeArguments?.[0] ? this.mapTsType(type.typeArguments[0]) : 'string';
        const value = type.typeArguments?.[1] ? this.mapTsType(type.typeArguments[1]) : 'unknown';
        result = `Record<${key}, ${value}>`;
        break;
      }
      case 'union': {
        result = type.unionTypes ? type.unionTypes.map((u) => this.mapTsType(u)).join(' | ') : 'unknown';
        break;
      }
      default: {
        result = type.name;
        break;
      }
    }

    if (type.nullable) {
      return `${result} | null | undefined`;
    }

    return result;
  }

  private mapPrimitive(name: string): string {
    switch (name) {
      case 'boolean': {
        return 'boolean';
      }
      case 'byte':
      case 'short':
      case 'long':
      case 'octet':
      case 'unsigned short':
      case 'unsigned long':
      case 'float':
      case 'unrestricted float':
      case 'double':
      case 'unrestricted double': {
        return 'number';
      }
      case 'long long':
      case 'unsigned long long':
      case 'bigint': {
        return 'bigint';
      }
      case 'void':
      case 'undefined': {
        return 'void';
      }
      default: {
        return 'any';
      }
    }
  }

  private mapWasmAbiType(type: WebIdlType): string {
    if (type.kind === 'buffer' || type.kind === 'string') {
      return 'number'; // Pointer offset into linear memory
    }
    if (type.kind === 'primitive') {
      if (type.name === 'void' || type.name === 'undefined') return 'void';
      if (type.name === 'bigint' || type.name === 'long long' || type.name === 'unsigned long long') return 'bigint';
      return 'number';
    }
    return 'number';
  }

  private toSnakeCase(string_: string): string {
    return string_
      .replaceAll(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replaceAll(/[^a-zA-Z0-9_]/g, '_')
      .toLowerCase();
  }
}

export function generateTypeDeclarations(module: WebIdlModule, options?: DtsOptions): string {
  return new DtsGenerator(module, options).generate();
}
