/**
 * Zero-copy host JavaScript / TypeScript binding and shim generator for Web IDL interop.
 * Enables direct Uint8Array views into Wasm interop memory (Memory 1) with zero serialization overhead.
 */

import type { HostShimOptions, WebIdlInterface, WebIdlModule, WebIdlNamespace, WebIdlOperation } from './types.js';

export class HostShimGenerator {
  private readonly module: WebIdlModule;
  private readonly options: HostShimOptions;

  public constructor(module: WebIdlModule, options: HostShimOptions = {}) {
    this.module = module;
    this.options = options;
  }

  public generate(): string {
    const memoryName = this.options.memoryExportName ?? 'memory';
    const memoryIndex = this.options.memoryIndex ?? 1;
    const allocName = this.options.allocatorExportName ?? 'fws_alloc';
    const deallocName = this.options.deallocatorExportName ?? 'fws_dealloc';
    const prefix = this.options.capabilityPrefix ?? 'web';
    const isTs = this.options.targetLanguage !== 'javascript';

    const lines: string[] = [
      '// Generated by Forge Web Script Web IDL Zero-Copy Host Binding Generator',
      '// DO NOT EDIT DIRECTLY',
      '',
      this.generateMemoryManagerClass(allocName, deallocName, isTs),
      '',
      this.generateHostImportsFactory(prefix, isTs),
      '',
      this.generateWasmAdapterClass(memoryName, memoryIndex, isTs),
    ];

    return lines.join('\n').trim() + '\n';
  }

  private generateMemoryManagerClass(allocExport: string, deallocExport: string, isTs: boolean): string {
    const typeAnnot = (annot: string) => (isTs ? annot : '');

    return `
/**
 * Manages zero-copy access into WebAssembly linear memory (Memory 1 / Interop Buffer).
 * Slices are directly backed by the instance memory buffer without copying or serialization.
 */
export class WasmInteropMemory {
  ${isTs ? 'private memory: WebAssembly.Memory;' : ''}
  ${isTs ? 'private allocFn?: (size: number) => number;' : ''}
  ${isTs ? 'private deallocFn?: (ptr: number, size: number) => void;' : ''}
  ${isTs ? 'private textDecoder = new TextDecoder();' : ''}
  ${isTs ? 'private textEncoder = new TextEncoder();' : ''}

  constructor(
    memory${typeAnnot(': WebAssembly.Memory')},
    allocFn${typeAnnot('?: (size: number) => number')},
    deallocFn${typeAnnot('?: (ptr: number, size: number) => void')},
  ) {
    this.memory = memory;
    this.allocFn = allocFn;
    this.deallocFn = deallocFn;
    ${isTs ? '' : 'this.textDecoder = new TextDecoder();\n    this.textEncoder = new TextEncoder();'}
  }

  /**
   * Return the raw underlying WebAssembly.Memory instance.
   */
  get rawMemory()${typeAnnot(': WebAssembly.Memory')} {
    return this.memory;
  }

  /**
   * Return the current ArrayBuffer of the linear memory.
   */
  get buffer()${typeAnnot(': ArrayBuffer')} {
    return this.memory.buffer;
  }

  /**
   * Creates a direct, zero-copy Uint8Array view into Wasm linear memory.
   * Throws RangeError if the requested slice is out of bounds.
   */
  getView(ptr${typeAnnot(': number')}, len${typeAnnot(': number')})${typeAnnot(': Uint8Array')} {
    if (ptr < 0 || len < 0 || ptr + len > this.memory.buffer.byteLength) {
      throw new RangeError(
        \`Zero-copy memory access out of bounds: ptr=\${ptr}, len=\${len}, bufferSize=\${this.memory.buffer.byteLength}\`,
      );
    }
    return new Uint8Array(this.memory.buffer, ptr, len);
  }

  /**
   * Reads a UTF-8 string directly from Wasm memory without intermediate buffer copies.
   */
  readString(ptr${typeAnnot(': number')}, len${typeAnnot(': number')})${typeAnnot(': string')} {
    return this.textDecoder.decode(this.getView(ptr, len));
  }

  /**
   * Writes a string into Wasm memory at ptr.
   * Returns the number of bytes written.
   */
  writeString(ptr${typeAnnot(': number')}, str${typeAnnot(': string')})${typeAnnot(': number')} {
    const encoded = this.textEncoder.encode(str);
    const view = this.getView(ptr, encoded.length);
    view.set(encoded);
    return encoded.length;
  }

  /**
   * Zero-copy transfer of host bytes into Wasm linear memory.
   */
  writeBytes(ptr${typeAnnot(': number')}, bytes${typeAnnot(': Uint8Array')})${typeAnnot(': void')} {
    const view = this.getView(ptr, bytes.length);
    view.set(bytes);
  }

  /**
   * Allocate memory using the Wasm module's exported allocator if available.
   */
  allocate(size${typeAnnot(': number')})${typeAnnot(': number')} {
    if (this.allocFn === undefined) {
      throw new Error('Wasm allocator export (${allocExport}) is not available on this instance');
    }
    return this.allocFn(size);
  }

  /**
   * Deallocate memory using the Wasm module's exported deallocator (${deallocExport}) if available.
   */
  deallocate(ptr${typeAnnot(': number')}, size${typeAnnot(': number')})${typeAnnot(': void')} {
    if (this.deallocFn !== undefined) {
      this.deallocFn(ptr, size);
    }
  }
}
`.trim();
  }

  private generateHostImportsFactory(prefix: string, isTs: boolean): string {
    const lines: string[] = [];
    const typeAnnot = (annot: string) => (isTs ? annot : '');

    lines.push(`
/**
 * Factory for creating host capability imports required by the Wasm module.
 * Directs zero-copy memory operations to host Web APIs.
 */
export function createHostImports(
  env${typeAnnot(': Record<string, any>')},
  interopMemory${typeAnnot(': WasmInteropMemory')},
)${typeAnnot(': Record<string, Record<string, (...args: any[]) => any>>')} {
  const imports${typeAnnot(': Record<string, Record<string, (...args: any[]) => any>>')} = {};
`);

    const interfaces = this.module.definitions.filter((d): d is WebIdlInterface => d.kind === 'interface');
    for (const iface of interfaces) {
      const namespaceKey = `${prefix}.${iface.name}`;
      lines.push(`  imports['${namespaceKey}'] = {`);

      for (const member of iface.members) {
        if (member.kind === 'attribute') {
          const getterProperty = `get_${this.toSnakeCase(member.name)}`;
          const attributeName = member.name;
          lines.push(
            `    '${getterProperty}': () => {`,
            `      const target = env['${iface.name}'] ?? globalThis['${iface.name}'];`,
            `      return target ? target['${attributeName}'] : 0;`,
            '    },',
          );

          if (!member.readonly) {
            const setterProperty = `set_${this.toSnakeCase(member.name)}`;
            lines.push(
              `    '${setterProperty}': (value${typeAnnot(': any')}) => {`,
              `      const target = env['${iface.name}'] ?? globalThis['${iface.name}'];`,
              `      if (target) target['${attributeName}'] = value;`,
              '    },',
            );
          }
        } else if (member.kind === 'operation' && member.name !== undefined) {
          const opName = member.name;
          lines.push(this.generateOperationShim(iface.name, opName, member, isTs));
        }
      }

      lines.push('  };');
    }

    const namespaces = this.module.definitions.filter((d): d is WebIdlNamespace => d.kind === 'namespace');
    for (const ns of namespaces) {
      const namespaceKey = `${prefix}.${ns.name}`;
      lines.push(`  imports['${namespaceKey}'] = {`);

      for (const member of ns.members) {
        if (member.kind === 'operation' && member.name !== undefined) {
          const opName = member.name;
          lines.push(this.generateOperationShim(ns.name, opName, member, isTs));
        }
      }

      lines.push('  };');
    }

    lines.push('  return imports;\n}');
    return lines.join('\n');
  }

  private generateOperationShim(targetName: string, opName: string, op: WebIdlOperation, isTs: boolean): string {
    const typeAnnot = (annot: string) => (isTs ? annot : '');

    // Build argument list for Wasm call:
    // For buffers: ptr, len
    // For strings: ptr, len
    // For scalars: val
    const wasmArgumentNames: string[] = [];
    const hostCallArguments: string[] = [];

    for (const argument of op.arguments) {
      if (argument.type.kind === 'buffer') {
        const ptrName = `${argument.name}Ptr`;
        const lengthName = `${argument.name}Len`;
        wasmArgumentNames.push(`${ptrName}${typeAnnot(': number')}`, `${lengthName}${typeAnnot(': number')}`);
        hostCallArguments.push(`interopMemory.getView(${ptrName}, ${lengthName})`);
      } else if (argument.type.kind === 'string') {
        const ptrName = `${argument.name}Ptr`;
        const lengthName = `${argument.name}Len`;
        wasmArgumentNames.push(`${ptrName}${typeAnnot(': number')}`, `${lengthName}${typeAnnot(': number')}`);
        hostCallArguments.push(`interopMemory.readString(${ptrName}, ${lengthName})`);
      } else {
        wasmArgumentNames.push(`${argument.name}${typeAnnot(': any')}`);
        hostCallArguments.push(argument.name);
      }
    }

    return `    '${opName}': (${wasmArgumentNames.join(', ')}) => {
      const target = env['${targetName}'] ?? globalThis['${targetName}'];
      if (!target || typeof target['${opName}'] !== 'function') {
        throw new Error(\`Host API \${'${targetName}'}.\${'${opName}'} is not available in environment\`);
      }
      return target['${opName}'](${hostCallArguments.join(', ')});
    },`;
  }

  private generateWasmAdapterClass(memoryExport: string, memoryIndex: number, isTs: boolean): string {
    const typeAnnot = (annot: string) => (isTs ? annot : '');

    return `
/**
 * High-level wrapper connecting a WebAssembly instance with zero-copy host interop bindings.
 */
export class WasmInteropAdapter {
  ${isTs ? 'public readonly memory: WasmInteropMemory;' : ''}
  ${isTs ? 'public readonly instance: WebAssembly.Instance;' : ''}

  constructor(instance${typeAnnot(': WebAssembly.Instance')}, memoryName = '${memoryExport}') {
    this.instance = instance;
    const exports = instance.exports as Record<string, any>;
    const rawMemory = (exports[memoryName] ?? exports['memory${memoryIndex}']) as WebAssembly.Memory;

    if (!rawMemory) {
      throw new Error(\`WebAssembly instance does not export linear memory '\${memoryName}'\`);
    }

    const allocFn = typeof exports['fws_alloc'] === 'function' ? exports['fws_alloc'] : undefined;
    const deallocFn = typeof exports['fws_dealloc'] === 'function' ? exports['fws_dealloc'] : undefined;

    this.memory = new WasmInteropMemory(rawMemory, allocFn, deallocFn);
  }

  /**
   * Helper to instantiate a Wasm module with automated host imports.
   */
  static async instantiate(
    moduleOrBytes${typeAnnot(': BufferSource | WebAssembly.Module')},
    env${typeAnnot(': Record<string, any>')},
    additionalImports${typeAnnot(': WebAssembly.Imports = {}')},
  )${typeAnnot(': Promise<{ adapter: WasmInteropAdapter; instance: WebAssembly.Instance }>')} {
    // Stage 1: Create a placeholder interop memory if required before instantiation
    const memory = new WebAssembly.Memory({ initial: 16, maximum: 256 });
    const interopMemory = new WasmInteropMemory(memory);
    const hostImports = createHostImports(env, interopMemory);

    const mergedImports = {
      ...additionalImports,
      ...hostImports,
    };

    let instance${typeAnnot(': WebAssembly.Instance')};
    if (moduleOrBytes instanceof WebAssembly.Module) {
      instance = await WebAssembly.instantiate(moduleOrBytes, mergedImports);
    } else {
      const res = await WebAssembly.instantiate(moduleOrBytes, mergedImports);
      instance = res.instance;
    }

    const adapter = new WasmInteropAdapter(instance);
    return { adapter, instance };
  }
}
`.trim();
  }

  private toSnakeCase(string_: string): string {
    return string_
      .replaceAll(/([a-z0-9])([A-Z])/g, '$1_$2')
      .replaceAll(/[^a-zA-Z0-9_]/g, '_')
      .toLowerCase();
  }
}

export function generateHostShims(module: WebIdlModule, options?: HostShimOptions): string {
  return new HostShimGenerator(module, options).generate();
}
