/// <reference types="vitest/config" />
import { defineAppConfig } from '@mission-platform/vite-config';
import { seoPlugin } from '@mission-platform/vite-plugin-seo';
import { VitePWA } from 'vite-plugin-pwa';

import { APP_LOCALE_BCP47, APP_ORIGIN } from './src/seo-app';

const ROOT_URL = APP_ORIGIN.endsWith('/') ? APP_ORIGIN : `${APP_ORIGIN}/`;
const SITEMAP_URL = `${ROOT_URL}sitemap.xml`;

export default defineAppConfig({
  overrides: {
    plugins: [
      // Single-route SPA: advertise the root URL with its locale alternate.
      seoPlugin({
        sitemap: {
          urls: [
            {
              loc: ROOT_URL,
              changefreq: 'weekly',
              priority: 1,
              alternates: [
                { hreflang: APP_LOCALE_BCP47, href: ROOT_URL },
                { hreflang: 'x-default', href: ROOT_URL },
              ],
            },
          ],
        },
        robots: {
          comments: ['My Care Notes', `Generated by @mission-platform/seo at ${new Date().toISOString()}`],
          groups: [{ userAgent: '*', allow: ['/'] }],
          sitemaps: [SITEMAP_URL],
          host: new URL(ROOT_URL).host,
        },
      }),
      VitePWA({
        registerType: 'autoUpdate',
        injectRegister: 'auto',
        workbox: {
          globPatterns: ['**/*.{js,css,html,svg,png,ico,woff,woff2}'],
          maximumFileSizeToCacheInBytes: 64 * 1024 * 1024,
          runtimeCaching: [
            {
              urlPattern: /\.wasm$/i,
              handler: 'CacheFirst',
              options: {
                cacheName: 'wasm-cache',
                expiration: {
                  maxEntries: 10,
                  maxAgeSeconds: 60 * 60 * 24 * 30,
                },
              },
            },
          ],
        },
        manifest: {
          name: 'My Care Notes',
          short_name: 'Care Notes',
          description: 'A clinical notes editor that works offline',
          theme_color: '#4a9ebe',
          background_color: '#ffffff',
          display: 'standalone',
          start_url: '/',
          icons: [
            {
              src: '/pwa-192x192.png',
              sizes: '192x192',
              type: 'image/png',
            },
            {
              src: '/pwa-512x512.png',
              sizes: '512x512',
              type: 'image/png',
              purpose: 'any maskable',
            },
          ],
        },
      }),
    ],
    build: {
      rolldownOptions: {
        output: {
          manualChunks(id) {
            if (id.includes('monaco-editor')) {
              return 'monaco-editor';
            }
          },
        },
      },
    },
    worker: {
      format: 'es',
    },
    test: {
      environment: 'jsdom',
      include: ['src/**/*.test.ts'],
    },
  },
});
