// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  'mp.breakpoints': {
    breakpoint: 'breakpoint:';
    debug_px: '({breakpoint}px)';
    separator: '|';
  };
}
