/// <reference types="vitest/config" />
import postcssConfig from '@mission-platform/postcss-config';
import { frameworkResolveConditions, ignoreVueI18nBlocksPlugin } from '@mission-platform/vite-config';
import i18nPlugin from '@mission-platform/vite-plugin-i18n';
import { seoPlugin } from '@mission-platform/vite-plugin-seo';
import vue from '@vitejs/plugin-vue';
import { defineConfig, type UserConfig } from 'vite';

import type { SitemapAlternate, SitemapUrl } from '@mission-platform/seo';

// `vite-ssg` reads `ssgOptions` off the resolved Vite config but does not
// ship a module augmentation for Vite's own `UserConfig` type, so we cast
// our config through an intersection that includes the extra property.
interface BeastiesOptions {
  preload?: 'body' | 'media' | 'swap' | 'swap-high' | 'js' | 'js-lazy';
  pruneSource?: boolean;
  inlineFonts?: boolean;
  preloadFonts?: boolean;
  fonts?: boolean;
  compress?: boolean;
  logLevel?: 'info' | 'warn' | 'error' | 'silent' | 'debug' | 'trace';
  reduceInlineStyles?: boolean;
  mergeStylesheets?: boolean;
  additionalStylesheets?: string[];
  [key: string]: unknown;
}

interface SsgUserConfig extends UserConfig {
  ssgOptions?: {
    includedRoutes?: () => string[] | Promise<string[]>;
    formatting?: 'minify' | 'prettify' | 'none';
    dirStyle?: 'flat' | 'nested';
    beastiesOptions?: BeastiesOptions | false;
  };
}

// ─── SEO companion files (robots.txt + sitemap.xml) ──────────────────────────
// Inlined locale table — keep in sync with `SUPPORTED_LOCALES` / `LOCALE_BCP47`
// in `src/router/index.ts` and `src/seo-site.ts`. The `@mission-platform/seo`
// builders run via the `seoPlugin` Vite plugin at build (and dev-server) time.
const SUPPORTED_LOCALES = ['en', 'es', 'fr', 'nl', 'it', 'de', 'ko', 'ja', 'zh', 'ar', 'he'] as const;
type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];
const DEFAULT_LOCALE: SupportedLocale = 'en';

const SITE_ORIGIN = 'https://mission-platform.dev';
const SITEMAP_URL = `${SITE_ORIGIN}/sitemap.xml`;

const LOCALE_BCP47: Record<SupportedLocale, string> = {
  en: 'en-AU',
  es: 'es-ES',
  fr: 'fr-FR',
  nl: 'nl-NL',
  it: 'it-IT',
  de: 'de-DE',
  ko: 'ko-KR',
  ja: 'ja-JP',
  zh: 'zh-CN',
  ar: 'ar',
  he: 'he-IL',
};

/** Build the canonical URL for a locale (the default locale maps to the site root). */
const canonicalFor = (locale: SupportedLocale): string =>
  locale === DEFAULT_LOCALE ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}/${locale}/`;

const sitemapAlternates: SitemapAlternate[] = [
  ...SUPPORTED_LOCALES.map((locale: SupportedLocale) => ({
    hreflang: LOCALE_BCP47[locale],
    href: canonicalFor(locale),
  })),
  { hreflang: 'x-default', href: canonicalFor(DEFAULT_LOCALE) },
];

const HASH_ANCHORS: Array<{ hash: string; changefreq: SitemapUrl['changefreq']; priority: number }> = [
  { hash: '#features', changefreq: 'weekly', priority: 0.8 },
  { hash: '#packages', changefreq: 'weekly', priority: 0.8 },
  { hash: '#about', changefreq: 'monthly', priority: 0.6 },
  { hash: '#faq', changefreq: 'monthly', priority: 0.6 },
];

const sitemapUrls: SitemapUrl[] = [
  {
    loc: canonicalFor(DEFAULT_LOCALE),
    changefreq: 'weekly',
    priority: 1,
    alternates: sitemapAlternates,
  },
  ...SUPPORTED_LOCALES.filter((locale) => locale !== DEFAULT_LOCALE).map<SitemapUrl>((locale) => ({
    loc: canonicalFor(locale),
    changefreq: 'weekly',
    priority: 0.9,
  })),
  ...HASH_ANCHORS.map<SitemapUrl>((entry) => ({
    loc: `${canonicalFor(DEFAULT_LOCALE)}${entry.hash}`,
    changefreq: entry.changefreq,
    priority: entry.priority,
  })),
];

// We don't use `defineAppConfig` here so the SEO companion plugin can be
// ordered alongside the Vue plugin without producing duplicate Vue plugin
// instances. Locale YAML bundles under `src/locales/` are imported as raw
// strings (`?raw`) and parsed with js-yaml at runtime, so no i18n-specific
// Vite plugin is required.
// This app targets Vue, so bare `@mission-platform/<pkg>` imports must resolve
// to each package's Vue build. Mirror the `defineFrameworkAppConfig` wiring
// here (client `resolve.conditions` + the SSR/prerender condition set, with the
// workspace packages bundled) since this app hand-rolls its Vite config.
const frameworkConditions = frameworkResolveConditions('vue');

const config: SsgUserConfig = {
  css: {
    postcss: postcssConfig,
  },
  resolve: {
    conditions: frameworkConditions,
  },
  ssr: {
    noExternal: [/^@mission-platform\//],
    resolve: {
      conditions: frameworkConditions,
      externalConditions: frameworkConditions,
    },
  },
  plugins: [
    i18nPlugin({ defaultLocale: 'en' }),
    seoPlugin({
      sitemap: { urls: sitemapUrls },
      robots: {
        comments: ['Mission Platform website', `Generated by @mission-platform/seo at ${new Date().toISOString()}`],
        groups: [{ userAgent: '*', allow: ['/'] }],
        sitemaps: [SITEMAP_URL],
        host: new URL(SITE_ORIGIN).host,
      },
    }),
    vue(),
    ignoreVueI18nBlocksPlugin(),
  ],
  // `vite-ssg` reads this property at build time. It is not part of Vite's
  // own `UserConfig`, so we extend the type locally via `SsgUserConfig`.
  ssgOptions: {
    // Default locale at `/`, plus one prerendered route per prefixed locale.
    // Keep this in sync with `SUPPORTED_LOCALES` / `PREFIXED_LOCALES` in
    // `src/router/index.ts`.
    includedRoutes: () => ['/', '/es', '/fr', '/nl', '/it', '/de', '/ko', '/ja', '/zh', '/ar', '/he'],
    // Emit `dist/es/index.html` (rather than `dist/es.html`) so prefixed
    // locales work cleanly behind a static file server / SPA worker.
    dirStyle: 'nested',
    // Minify each generated HTML file.
    formatting: 'minify',
    // Inline critical CSS into each prerendered HTML file and lazy-load the
    // rest, via `beasties` (the maintained fork of `critters`). `vite-ssg`
    // auto-detects `beasties` from the workspace and runs it during the SSG
    // pass; we pass through explicit options so the behaviour is pinned in
    // config rather than implicit defaults.
    beastiesOptions: {
      // Lazy-load the non-critical stylesheet via a media-swap `<link>` so
      // the browser fetches it without blocking first paint, then upgrades
      // to `rel="stylesheet"` once loaded.
      preload: 'swap-high',
      // Keep the original full stylesheets in the bundle so client-side
      // navigation (SPA hydration after the initial route) can apply any
      // styles that were not critical for the prerendered HTML.
      pruneSource: false,
      noscriptFallback: true,
      // Inline `@font-face` declarations referenced by critical CSS so web
      // fonts start loading from the inlined `<style>` block.
      inlineFonts: false,
      preloadFonts: false,
      // Only surface real problems during the build log.
      logLevel: 'warn',
    },
  },
  test: {
    environment: 'jsdom',
    include: ['src/**/*.test.ts'],
  },
};

export default defineConfig(config as UserConfig);
