// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  'mp.website': {
    about: {
      lead: 'The Mission Platform is a composable monorepo of reusable UI building blocks, WebAssembly modules and tooling — author once in Forge and build for every framework.';
      projects: {
        'aria-label': 'Project list';
      };
      title: 'About';
    };
    ai_translation_warning: 'ai-translation-warning';
    faq: {
      items: {
        composable: {
          answer: 'We build the interface from small, reusable, framework-neutral building blocks you can mix and match.';
          question: "What does 'composable' mean?";
        };
        deploy: {
          answer: 'The platform is designed to deploy to Cloudflare Workers and other serverless or static hosting environments.';
          question: 'How do I deploy this?';
        };
        frameworks: {
          answer: 'Components are authored once in the framework-agnostic Forge runtime and built for Vue, React, Svelte, Solid and Web Components.';
          question: 'Which frameworks are supported?';
        };
      };
      title: 'FAQ';
    };
    features: {
      barcode: {
        description: 'Generate and scan QR, Data Matrix and 1D barcodes, powered by WebAssembly.';
        title: 'Scanning & Codes';
      };
      composable: {
        description: 'Author your UI once in the framework-agnostic Forge runtime, then build for Vue, React, Svelte, Solid and Web Components.';
        title: 'Write Once, Run Anywhere';
      };
      debugging: {
        description: 'End-to-end TypeScript across every package, app and worker.';
        title: 'Type-Safe';
      };
      global: {
        description: 'Built to deploy to Cloudflare Workers and other serverless platforms.';
        title: 'Edge-Ready';
      };
      i18n: {
        description: 'Built-in i18next translation with full right-to-left language support.';
        title: 'Internationalization';
      };
      performance: {
        description: 'Rust and AssemblyScript compiled to WebAssembly for near-native speed.';
        title: 'Performance';
      };
      search: {
        description: 'Forms, tables, scheduling, maps, charts and rich-text editing out of the box.';
        title: 'Batteries Included';
      };
      theming: {
        description: 'Design tokens and SCSS themes with first-class light and dark modes.';
        title: 'Theming';
      };
      title: 'Features';
    };
    footer: {
      copyright: '© {year} Mission Platform.';
    };
    hero: {
      badge: 'Open Source';
      'cta-primary': 'Get Started';
      'cta-secondary': 'Documentation';
      lead: 'Author your interface once in the framework-agnostic Forge runtime, then build for Vue, React, Svelte, Solid and Web Components.';
      title: 'Composable. Mission Ready.';
    };
    nav: {
      about: 'About';
      faq: 'FAQ';
      features: 'Features';
      packages: 'Packages';
    };
    packages: {
      items: {
        barcode: '1D barcode encoder and decoder in WebAssembly.';
        breakpoints: 'Responsive breakpoint utilities and components.';
        'code-scanner': 'Scan QR, Data Matrix and barcodes from image or camera.';
        components: 'Write-once UI components for every supported framework.';
        d3: 'Framework-neutral D3 integration.';
        forms: 'Write-once form builder and schema-driven forms.';
        'forms-core': 'Framework-agnostic JSON Schema forms engine.';
        harper: 'Harper grammar and style checking for Monaco.';
        hunspell: 'Hunspell spell checking in WebAssembly.';
        i18n: 'Internationalization powered by i18next.';
        icons: 'SVG icons authored once in JSX.';
        jsx: 'Framework-neutral JSX runtime with adapters for each framework.';
        layouts: 'Write-once application layouts.';
        map: 'MapLibre GL map components and composables.';
        'matrix-code': 'Data Matrix encoder and decoder in WebAssembly.';
        observers: 'Write-once Intersection, Mutation and Performance observer hooks.';
        'phone-number': 'Phone number parsing, validation and formatting.';
        'qr-code': 'QR Code encoder and decoder in WebAssembly.';
        router: 'Routing utilities.';
        rxjs: 'Bridge RxJS observables to component state.';
        'scheduler-core': 'iCalendar event model and recurrence engine.';
        seo: 'Structured data, meta tags and sitemap helpers.';
        'speech-audio': 'Speech synthesis, recognition, audio and Web MIDI hooks.';
        three: 'Framework-neutral Three.js integration.';
        tokens: 'CSS design tokens and SCSS themes.';
        wysiwyg: 'Write-once rich-text editor.';
      };
      lead: 'Composable building blocks — from UI and forms to WebAssembly-powered tooling.';
      title: 'Packages';
    };
    projects: {
      items: {
        'my-care-notes': {
          cta: 'Learn More';
          description: 'A patient-centric care notes application built on the Mission Platform.';
          name: 'My Care Notes';
        };
      };
    };
  };
}
