// This file is automatically generated by i18next-cli. Do not edit manually.
export default interface Resources {
  'mp.website': {
    about: {
      lead: 'The Mission Platform is a set of reusable UI building blocks and tools for building applications.';
      projects: {
        'aria-label': 'Project list';
      };
      title: 'About';
    };
    ai_translation_warning: 'ai-translation-warning';
    faq: {
      items: {
        affiliation: {
          answer: 'We are an independent implementation of the Mission Platform architecture.';
          question: 'Are you affiliated with the Mission Platform project?';
        };
        composable: {
          answer: 'It means we build the UI from small, reusable, and independent building blocks.';
          question: "What does 'composable' mean?";
        };
        deploy: {
          answer: 'The platform is designed to be deployed to Cloudflare Workers or similar serverless environments.';
          question: 'How do I deploy this?';
        };
        'vue-version': {
          answer: 'We use Vue 3 with the Composition API.';
          question: 'Which version of Vue is used?';
        };
      };
      title: 'FAQ';
    };
    features: {
      barcode: {
        description: 'Support for barcode and QR code scanning.';
        title: 'Barcode';
      };
      composable: {
        description: 'Build applications from small, independent building blocks.';
        title: 'Composable';
      };
      debugging: {
        description: 'Advanced debugging tools integrated into the platform.';
        title: 'Debugging';
      };
      global: {
        description: 'Ready for global deployment.';
        title: 'Global Scale';
      };
      i18n: {
        description: 'Built-in support for multiple languages.';
        title: 'Internationalization';
      };
      performance: {
        description: 'Optimized for speed and minimal load times.';
        title: 'Performance';
      };
      search: {
        description: 'Powerful integrated search functionality.';
        title: 'Search';
      };
      theming: {
        description: 'Easily customizable look and feel.';
        title: 'Theming';
      };
      title: 'Features';
    };
    footer: {
      brand: 'Mission Platform';
      copyright: '© {year} Mission Platform.';
      'disclaimer-end': '.';
      'disclaimer-start': 'is an independent project.';
      'not-affiliated': 'Not affiliated with the Mission Platform project.';
    };
    hero: {
      badge: 'Beta';
      'cta-primary': 'Get Started';
      'cta-secondary': 'Documentation';
      lead: 'A platform for building applications from small, independent building blocks.';
      title: 'Composable. Mission Ready.';
    };
    nav: {
      about: 'About';
      faq: 'FAQ';
      features: 'Features';
      packages: 'Packages';
    };
    packages: {
      items: {
        barcode: 'Barcode support.';
        'base-spa': 'Base SPA setup.';
        breakpoints: 'Responsive breakpoints.';
        'code-scanner': 'Code scanning utilities.';
        components: 'Reusable UI building blocks.';
        d3: 'D3 integration.';
        forms: 'Form handling utilities.';
        'forms-core': 'Core form logic.';
        harper: 'Data handling utilities.';
        hunspell: 'Spell checking support.';
        i18n: 'Internationalization support.';
        icons: 'Icon library.';
        jsx: 'JSX support for Vue.';
        layouts: 'Pre-built application layouts.';
        map: 'Map component.';
        'matrix-code': 'Matrix code generation.';
        'phone-number': 'Phone number formatting.';
        'qr-code': 'QR code generation.';
        router: 'Routing utilities.';
        rxjs: 'RxJS support.';
        'scheduler-core': 'Task scheduling.';
        seo: 'SEO management.';
        tokens: 'Design tokens and theming.';
      };
      lead: 'Reusable building blocks for your applications.';
      title: 'Packages';
    };
    projects: {
      items: {
        'my-care-notes': {
          cta: 'Learn More';
          description: 'A patient-centric care notes application built on the Mission Platform.';
          name: 'My Care Notes';
        };
      };
    };
  };
}
