/**
 * Generate `public/robots.txt` and `public/sitemap.xml` for the website using
 * the deterministic builders from `@mission-platform/seo`.
 *
 * Run automatically before `build` / `build:spa` via the `prebuild` script in
 * `package.json` so the prerendered SSG output ships fresh crawler-facing
 * companion files that match the current router locale table.
 */
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { buildRobotsTxt, buildSitemapXml, type SitemapAlternate, type SitemapUrl } from '@mission-platform/seo';

// Inlined from `src/router/index.ts` and `src/seo-site.ts` — Node's
// `--experimental-strip-types` runner doesn't resolve extensionless `.ts`
// imports between source modules, so the SEO generator keeps its own copy
// of the locale table. Keep these in sync with the runtime source.
const SUPPORTED_LOCALES = ['en', 'es', 'fr', 'nl', 'it', 'de', 'ko', 'ja', 'zh', 'ar', 'he'] as const;
type SupportedLocale = (typeof SUPPORTED_LOCALES)[number];
const DEFAULT_LOCALE: SupportedLocale = 'en';

const SITE_ORIGIN = 'https://mission-platform.dev';

const LOCALE_BCP47: Record<SupportedLocale, string> = {
  en: 'en-AU',
  es: 'es-ES',
  fr: 'fr-FR',
  nl: 'nl-NL',
  it: 'it-IT',
  de: 'de-DE',
  ko: 'ko-KR',
  ja: 'ja-JP',
  zh: 'zh-CN',
  ar: 'ar',
  he: 'he-IL',
};

const canonicalFor = (locale: SupportedLocale): string =>
  locale === DEFAULT_LOCALE ? `${SITE_ORIGIN}/` : `${SITE_ORIGIN}/${locale}/`;

const HERE = path.dirname(fileURLToPath(import.meta.url));
const PUBLIC_DIR = path.resolve(HERE, '..', 'public');

const SITEMAP_URL = `${SITE_ORIGIN}/sitemap.xml`;

const alternates: SitemapAlternate[] = [
  ...SUPPORTED_LOCALES.map((locale: SupportedLocale) => ({
    hreflang: LOCALE_BCP47[locale],
    href: canonicalFor(locale),
  })),
  { hreflang: 'x-default', href: canonicalFor(DEFAULT_LOCALE) },
];

const HASH_ANCHORS: Array<{ hash: string; changefreq: SitemapUrl['changefreq']; priority: number }> = [
  { hash: '#features', changefreq: 'weekly', priority: 0.8 },
  { hash: '#packages', changefreq: 'weekly', priority: 0.8 },
  { hash: '#about', changefreq: 'monthly', priority: 0.6 },
  { hash: '#faq', changefreq: 'monthly', priority: 0.6 },
];

const urls: SitemapUrl[] = [
  {
    loc: canonicalFor(DEFAULT_LOCALE),
    changefreq: 'weekly',
    priority: 1,
    alternates,
  },
  ...SUPPORTED_LOCALES.filter((locale) => locale !== DEFAULT_LOCALE).map<SitemapUrl>((locale) => ({
    loc: canonicalFor(locale),
    changefreq: 'weekly',
    priority: 0.9,
  })),
  ...HASH_ANCHORS.map<SitemapUrl>((entry) => ({
    loc: `${canonicalFor(DEFAULT_LOCALE)}${entry.hash}`,
    changefreq: entry.changefreq,
    priority: entry.priority,
  })),
];

const sitemap = buildSitemapXml({ urls });

const robots = buildRobotsTxt({
  comments: ['Mission Platform website', `Generated by @mission-platform/seo at ${new Date().toISOString()}`],
  groups: [{ userAgent: '*', allow: ['/'] }],
  sitemaps: [SITEMAP_URL],
  host: new URL(SITE_ORIGIN).host,
});

mkdirSync(PUBLIC_DIR, { recursive: true });
writeFileSync(path.resolve(PUBLIC_DIR, 'sitemap.xml'), sitemap, 'utf8');
writeFileSync(path.resolve(PUBLIC_DIR, 'robots.txt'), robots, 'utf8');

process.stdout.write(`[seo] wrote ${PUBLIC_DIR}/robots.txt and sitemap.xml (${urls.length} URLs)\n`);
